Repository grpc/grpc-go, pull requests merged in 2018-09, with the labels that each got.

#2286 Make all error strings use lowercased first letter per Go style
  resolver/dns/dns_resolver.go
  test/rawConnWrapper.go
Labels: Type: Internal Cleanup

#2283 Travis/Makefile/vet cleanups
  .travis.yml
  Makefile
  vet.sh
Labels: Type: Internal Cleanup

#2289 change 'if x == true' to 'if x'
  test/end2end_test.go
Labels: Type: Internal Cleanup

#2291 Miscellaneous small cleanups
  internal/channelz/types_linux.go
  internal/channelz/util_test.go
Labels: Type: Internal Cleanup

#2290 Remove shadowing of built-ins
  balancer/grpclb/grpclb_test.go
  benchmark/benchmain/main.go
  benchmark/worker/benchmark_client.go
  credentials/alts/core/handshaker/handshaker_test.go
  internal/transport/http2_server.go
  metadata/metadata_test.go
Labels: Type: Internal Cleanup

#2287 Remove unused symbols
  balancer.go
  balancer_test.go
  channelz/service/service.go
  clientconn.go
  credentials/alts/utils.go
  internal/transport/controlbuf.go
  internal/transport/handler_server_test.go
  internal/transport/log.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  interop/alts/client/client.go
  rpc_util.go
  stats/stats_test.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#2293 credentials/alts: Export test APIs
  credentials/alts/internal/conn/aes128gcm.go
  credentials/alts/internal/conn/aes128gcm_test.go
  credentials/alts/internal/conn/aes128gcmrekey.go
  credentials/alts/internal/conn/aes128gcmrekey_test.go
  credentials/alts/internal/conn/counter.go
  credentials/alts/internal/conn/counter_test.go
  credentials/alts/internal/conn/utils.go
Labels: Type: Internal Cleanup

#2274 Check error when calling compressor.Compress
  rpc_util.go
Labels: Type: Bug

#2312 stream: never return errors from CloseSend
  stream.go
Labels: Type: Bug

#2265 resolver/dns: support custom dns authority
  resolver/dns/dns_resolver.go
  resolver/dns/dns_resolver_go19_test.go
  resolver/dns/dns_resolver_test.go
  resolver/dns/go17.go
  resolver/dns/go18.go
  resolver/dns/go18_test.go
  resolver/dns/go19.go
  resolver/dns/pre_go18_test.go
  resolver/dns/pre_go19.go
Labels: Type: Feature

#2331 Add lock.yml for locking closed, stale PRs/issues
  .github/lock.yml
Labels: no release notes

#2337 client: read from Conn while writing preface to unblock synchronous Conns
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Bug, no release notes
