Repository grpc/grpc-go, pull requests merged in 2018-05, with the labels that each got.

#2027 Fix "deprecated" function godoc comments to match standard formatting
  benchmark/client/main.go
  benchmark/server/main.go
  benchmark/worker/benchmark_client.go
  benchmark/worker/benchmark_server.go
  benchmark/worker/main.go
  call.go
  clientconn.go
  grpclb.go
  grpclb/grpclb_test.go
  grpclog/grpclog.go
  grpclog/logger.go
  interop/client/client.go
  interop/http2/negative_http2_client.go
  interop/test_utils.go
  metadata/metadata.go
  server.go
  service_config.go
  stress/client/main.go
  stress/metrics_client/main.go
Labels: Type: Internal Cleanup

#2026 client: ignore "user-agent" if set in outgoing metadata
  transport/handler_server.go
  transport/http_util.go
  transport/transport_test.go
Labels: Type: Bug

#2051 fix flaky test caused by race in channelz test
  test/channelz_test.go
Labels: Type: Testing

#2010 client: introduce WithDisableServiceConfig DialOption
  clientconn.go
  clientconn_test.go
  resolver/dns/dns_resolver.go
  resolver/dns/dns_resolver_test.go
  resolver/resolver.go
  resolver_conn_wrapper.go
Labels: Type: Feature

#2057 status: Introduce FromContextError convenience function
  status/go16.go
  status/go17.go
  status/go17_test.go
  status/status_test.go
Labels: Type: Feature

#2058 split encode into three functions
  call_test.go
  rpc_util.go
  rpc_util_test.go
  server.go
  stream.go
Labels: Type: Internal Cleanup

#1993 Fix possible data loss; Only let reader goroutine handle connection errors.
  test/gracefulstop_test.go
  transport/controlbuf.go
  transport/http2_client.go
  transport/http2_server.go
Labels: Type: Bug

#1952 Benchmarks that runs server and client and separate processes.
  benchmark/benchmark.go
  benchmark/client/main.go
  benchmark/run_bench.sh
  benchmark/server/main.go
Labels: Type: Testing

#2106 internal/grpcrand: New package for concurrency-safe randoms
  backoff.go
  internal/grpcrand/grpcrand.go
  resolver/dns/dns_resolver.go
  transport/http2_server.go
  vet.sh
Labels: Type: Bug
