Repository grpc/grpc-go, pull requests merged in 2018-06, with the labels that each got.

#2109 status: handle invalid utf-8 characters
  test/end2end_test.go
  transport/http2_server.go
  transport/http_util.go
  transport/http_util_test.go
Labels: Cherry Pick, Type: Bug

#2135 resolver_conn_wrapper.go: fix minor typo
  resolver_conn_wrapper.go
Labels: Type: Internal Cleanup

#2033 Documentation: create doc describing grpc-go's log levels and their usages
  Documentation/log_levels.md
Labels: Type: Documentation

#2142 internal: Change Lock to RLock since no mutation is performed
  clientconn.go
Labels: Type: Internal Cleanup

#2139 fix: do not percent encode character tilde
  transport/http_util.go
  transport/http_util_test.go
Labels: Type: Bug

#2155 Import grpclb package in the interop client
  interop/client/client.go
Labels: Type: Testing

#2158 transport: notify controlbuf that transport is gracefully closing to ensure proper cleanup
  transport/http2_client.go
  transport/transport_test.go
Labels: Type: Bug

#2165 interop: set dns as default scheme in interop client
  interop/client/client.go
Labels: Type: Testing

#2150 resolver/dns: error if target ends with a colon instead of assuming the default port
  resolver/dns/dns_resolver.go
  resolver/dns/dns_resolver_test.go
Labels: Type: Behavior Change

#2172 balancer/grpclb: update to latest lb proto
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
Labels: Type: Internal Cleanup

#2175 Revert stickiness
  Documentation/stickiness.md
  clientconn.go
  envconfig.go
  picker_wrapper.go
  service_config.go
  stickiness_linkedmap.go
  stickiness_linkedmap_test.go
  stickiness_test.go
Labels: Type: Behavior Change

#2147 client, server: update dial/server buffer options to support a "disable" setting
  clientconn.go
  server.go
  test/end2end_test.go
  transport/http2_client.go
  transport/http2_server.go
  transport/http_util.go
  transport/transport_test.go
Labels: Type: Feature

#2178 credentials: cleanup version-specific files
  credentials/credentials.go
  credentials/credentials_util_go18.go
  credentials/credentials_util_go19.go
  credentials/credentials_util_pre_go18.go
  credentials/go16.go
  credentials/go17.go
  credentials/go18.go
  credentials/go19.go
Labels: Type: Internal Cleanup

#2111 client: Implement gRFC A6: configurable client-side retry support
  .travis.yml
  call.go
  clientconn.go
  internal/envconfig/envconfig.go
  rpc_util.go
  service_config.go
  stream.go
  test/end2end_test.go
  test/retry_test.go
  transport/go16.go
  transport/go17.go
  transport/http2_client.go
  transport/http_util.go
  transport/transport.go
  transport/transport_test.go
Labels: Type: Feature

#2185 Allow interop client to use call creds on any secure channel
  interop/client/client.go
Labels: Type: Testing
