Repository grpc/grpc-go, pull requests merged in 2018-10, with the labels that each got.

#2358 test: add test for picker DoneInfo.Err
  test/balancer_test.go
Labels: Type: Testing, no release notes

#2359 balancer: add trailer metadata to DoneInfo
  balancer/balancer.go
  internal/transport/http2_client.go
  stream.go
  test/balancer_test.go
Labels: Type: Feature

#2345 travis: Retry go get when it fails
  .travis.yml
Labels: Type: Testing, no release notes

#2376 balancer: add header metadata to PickOptions
  balancer/balancer.go
  clientconn.go
  test/balancer_test.go
Labels: Type: Feature

#2379 server: fix handling of RPC timeouts that overflow int64 nanos
  internal/transport/http_util.go
  test/end2end_test.go
Labels: Type: Bug

#2385 cleanup: remove ac.events (unused) and related dead code
  clientconn.go
Labels: Type: Internal Cleanup, no release notes

#2396 internal: add check for import of ptypes proto packages
  vet.sh
Labels: Type: Testing, no release notes

#2405 internal: vet cleanups
  test/go_vet/vet.go
  vet.sh
Labels: Type: Testing, no release notes

#2410 channelz: update generated proto stubs
  channelz/grpc_channelz_v1/channelz.pb.go
Labels: Type: Internal Cleanup, no release notes
