Repository grpc/grpc-go, pull requests merged in 2018-07, with the labels that each got.

#2192 Fix flaky test: TestClientStreamingError
  stream.go
Labels: Type: Bug

#2199 stream: in withRetry, block until Status is valid and check on io.EOF
  stream.go
  transport/transport.go
Labels: Type: Bug

#2200 internal: changes to travis to make it do less work
  .travis.yml
  vet.sh
Labels: Type: Testing, no release notes

#2198 deprecate stream, move documentation to client|server stream
  stream.go
Labels: Type: Documentation

#2211 transport: double-check deadline when processing server cancelation
  transport/http2_client.go
Labels: Type: Bug

#2212 transport: move to internal to make room for new, public transport API
  call_test.go
  clientconn.go
  go16.go
  go17.go
  internal/transport/bdp_estimator.go
  internal/transport/controlbuf.go
  internal/transport/defaults.go
  internal/transport/flowcontrol.go
  internal/transport/go16.go
  internal/transport/go17.go
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
  internal/transport/log.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  picker_wrapper.go
  picker_wrapper_test.go
  rpc_util.go
  rpc_util_test.go
  server.go
  server_test.go
  stream.go
  vet.sh
Labels: Type: API Change

#2193 internal: move DialOptions to a new file
  clientconn.go
  dialoptions.go
Labels: Type: Internal Cleanup, no release notes

#2213 internal/transport: remove some unused fields from structs
  clientconn.go
  dialoptions.go
  internal/transport/handler_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  server.go
  stream.go
Labels: Type: Internal Cleanup, no release notes

#2220 addrconn: remove unused wait() method
  clientconn.go
Labels: Type: Internal Cleanup

#2217 resolver: document that SetDefaultScheme should be called at init time
  resolver/resolver.go
Labels: Type: Documentation

#2225 internal/transport: minor typo fix
  internal/transport/transport.go
Labels: Type: Internal Cleanup, no release notes

#2224 internal/transport: remove unnecessary ServerTransport method
  internal/transport/transport.go
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup, no release notes

#2231 interop: loosen restrictions on creds per test in interop client
  interop/client/client.go
Labels: Type: Testing

#2237 disable go1.6 travis tests
  .travis.yml
Labels: Type: Testing, no release notes

#2238 transport: replace ClientTransport with *http2Client for internal usage
  internal/transport/http2_client.go
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup, no release notes

#2239 transport: eliminate StreamError; use status errors instead
  go16.go
  go17.go
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  rpc_util.go
  rpc_util_test.go
  server.go
Labels: Type: Internal Cleanup, no release notes

#2244 internal/grpcsync: introduce package for synchronization
  internal/grpcsync/event.go
  internal/grpcsync/event_test.go
Labels: Type: Internal Cleanup, no release notes

#2241 interop: implement special_status_message interop test
  interop/client/client.go
  interop/test_utils.go
Labels: Type: Testing
