Repository grpc/grpc-go, pull requests merged in 2019-07, with the labels that each got.

#2896 xds: update proto
  balancer/xds/edsbalancer/balancergroup.go
  balancer/xds/edsbalancer/balancergroup_test.go
  balancer/xds/internal/proto/envoy/api/v2/cds/cds.pb.go
  balancer/xds/internal/proto/envoy/api/v2/cluster/circuit_breaker/circuit_breaker.pb.go
  balancer/xds/internal/proto/envoy/api/v2/cluster/outlier_detection/outlier_detection.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/base/base.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/health_check/health_check.pb.go
  balancer/xds/internal/proto/envoy/api/v2/discovery/discovery.pb.go
  balancer/xds/internal/proto/envoy/api/v2/eds/eds.pb.go
  balancer/xds/internal/proto/envoy/api/v2/endpoint/endpoint/endpoint.pb.go
  balancer/xds/internal/proto/envoy/api/v2/endpoint/load_report/load_report.pb.go
  balancer/xds/internal/proto/udpa/data/orca/v1/orca_load_report/orca_load_report.pb.go
  balancer/xds/internal/proto/validate/validate.pb.go
  balancer/xds/internal/regenerate_scripts/README.md
  balancer/xds/internal/regenerate_scripts/envoy-proto-gen.sh
  balancer/xds/internal/regenerate_scripts/utils/WORKSPACE
  balancer/xds/internal/regenerate_scripts/utils/protoc-gen-validate.patch
  balancer/xds/orca/orca_test.go
Labels: Type: Internal Cleanup, no release notes

#2900 docs: clarify "deprecated" to indicate whether some features may be removed in 1.x
  balancer.go
  dialoptions.go
  vet.sh
Labels: Type: Documentation

#2906 client: fix canceled vs deadline exceeded double-check logic
  internal/transport/http2_client.go
Labels: Type: Bug

#2907 balancer: filter out grpclb addresses if balancer is not grpclb
  balancer_conn_wrappers.go
  test/balancer_test.go
Labels: Type: Bug

#2898 xds: instructions for regenerating proto
  balancer/xds/internal/regenerate_scripts/README.md
Labels: Type: Internal Cleanup, no release notes

#2920 server: avoid an unnecessary allocation per-RPC for OK status
  server.go
Labels: Type: Performance

#2919 client: fix race between transport draining and new RPCs
  balancer/grpclb/grpclb_test.go
  clientconn.go
  clientconn_state_transition_test.go
  internal/transport/http2_client.go
  stream.go
  test/end2end_test.go
  test/goaway_test.go
Labels: Type: Bug

#2929 status: avoid allocations when returning an OK status
  status/status.go
Labels: Type: Performance

#2868 status: Implement *statusError.Is
  status/status.go
  status/status_ext_test.go
Labels: Type: Feature

#2926 server: avoid call to trace.FromContext and resulting allocations when tracing is disabled
  server.go
Labels: Type: Performance
