Repository grpc/grpc-go, pull requests merged in 2019-04, with the labels that each got.

#2764 internal: clean up README
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.md
  README.md
  examples/README.md
Labels: Type: Internal Cleanup, no release notes

#2765 transport: fix a race that could lead to memory leaks
  internal/transport/http2_server.go
Labels: Cherry Pick, Type: Bug

#2750 xds: make local proto generated files
  balancer/xds/edsbalancer/edsbalancer.go
  balancer/xds/edsbalancer/edsbalancer_test.go
  balancer/xds/internal/proto/envoy/api/v2/auth/cert/cert.pb.go
  balancer/xds/internal/proto/envoy/api/v2/cds/cds.pb.go
  balancer/xds/internal/proto/envoy/api/v2/cluster/circuit_breaker/circuit_breaker.pb.go
  balancer/xds/internal/proto/envoy/api/v2/cluster/outlier_detection/outlier_detection.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/address/address.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/base/base.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/config_source/config_source.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/grpc_service/grpc_service.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/health_check/health_check.pb.go
  balancer/xds/internal/proto/envoy/api/v2/core/protocol/protocol.pb.go
  balancer/xds/internal/proto/envoy/api/v2/discovery/discovery.pb.go
  balancer/xds/internal/proto/envoy/api/v2/eds/eds.pb.go
  balancer/xds/internal/proto/envoy/api/v2/endpoint/endpoint/endpoint.pb.go
  balancer/xds/internal/proto/envoy/service/discovery/v2/ads/ads.pb.go
  balancer/xds/internal/proto/envoy/type/percent/percent.pb.go
  balancer/xds/internal/proto/envoy/type/range/range.pb.go
  balancer/xds/internal/proto/validate/validate.pb.go
  balancer/xds/xds.go
  balancer/xds/xds_client.go
  balancer/xds/xds_client_test.go
  balancer/xds/xds_test.go
  go.mod
  go.sum
  vet.sh
Labels: Cherry Pick

#2560 grpc: implementation of PreparedMsg API
  benchmark/benchmain/main.go
  benchmark/stats/stats.go
  preloader.go
  rpc_util.go
  stream.go
  test/end2end_test.go
Labels: Type: Feature

#2784 server: define ServerOption as interfaces
  server.go
Labels: Type: Internal Cleanup

#2791 internal: seed random for wrr tests
  balancer/internal/wrr/random.go
  balancer/internal/wrr/wrr_test.go
  vet.sh
Labels: Type: Testing, no release notes
