Repository grpc/grpc-go, pull requests merged in 2019-06, with the labels that each got.

#2850 xds: rename balancer to xds_experimental during testing
  balancer/xds/xds.go
  balancer/xds/xds_lrs_test.go
  balancer/xds/xds_test.go
Labels: Type: Testing, no release notes

#2852 serviceconfig: mark new package experimental
  serviceconfig/serviceconfig.go
Labels: Type: Internal Cleanup, no release notes

#2862 client: update state earlier to prevent resetTransport calls from killing good transports
  clientconn.go
Labels: Type: Bug, no release notes

#2866 Fix a typo in the comment.
  test/end2end_test.go
Labels: no release notes

#2861 test: extend RPC timeout for TestHTTPHeaderFrameErrorHandlingHTTPMode
  test/end2end_test.go
Labels: Type: Internal Cleanup, no release notes

#2871 internal: update channelz.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
Labels: no release notes

#2879 metadata: write original md before appended md
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Bug
