Repository grpc/grpc-go, pull requests merged in 2019-12, with the labels that each got.

#3222 credentials/alts: Set the handshake extra slice correctly
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Bug

#3223 alts: Update handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
Labels: Type: Dependencies

#3221 credentials/alts: Simplify ALTS acquire and release APIs
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Internal Cleanup, no release notes

#3225 credentials/alts: Ensure that GetBytesConsumed is in-bound
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Bug, no release notes

#3229 travis: run interop tests with examples
  .travis.yml
  interop/interop_test.sh
Labels: Type: Testing, no release notes

#3228 dns: reapply "dns: stop polling for updates; use UpdateState API"
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/resolver/dns/go113.go
Labels: Type: Internal Cleanup, no release notes

#3224 xds: Implementation of the CDS LB policy.
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/xds.go
Labels: Type: Feature

#3208 server.go: combine defers to reduce stack usage
  server.go
Labels: Type: Performance

#3232 xds/resolver: Add missing double quote in json SC
  xds/internal/resolver/xds_resolver.go
Labels: Type: Bug

#3239 xds: Update the check for match field when handling an RDS response.
  xds/internal/client/rds.go
  xds/internal/client/rds_test.go
  xds/internal/client/v2client_test.go
Labels: Type: Bug

#3233 xds: resolver test cleanup
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/channel.go
  xds/internal/testutils/xdsclient.go
Labels: Type: Internal Cleanup

#3238 xds: small fixes
  xds/experimental/xds_experimental.go
  xds/internal/client/rds.go
  xds/internal/client/rds_test.go
Labels: Type: Internal Cleanup, no release notes

#3241 internal: Improve documentation around buffer.Unbounded
  internal/buffer/unbounded.go
  internal/transport/transport.go
Labels: Type: Internal Cleanup

#3240 xds: skip callback if xds client reports error
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_client_wrapper.go
Labels: Type: Internal Cleanup, no release notes

#3158 profiling: add internal changes to support profiling of gRPC
  internal/profiling/buffer/buffer.go
  internal/profiling/buffer/buffer_appengine.go
  internal/profiling/buffer/buffer_test.go
  internal/profiling/goid_modified.go
  internal/profiling/goid_regular.go
  internal/profiling/profiling.go
  internal/profiling/profiling_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
Labels: Type: Performance

#3243 credentials: move TLS implementation to a separate file
  credentials/credentials.go
  credentials/go12.go
  credentials/tls.go
  dialoptions.go
Labels: Type: Internal Cleanup, no release notes

#3231 Fix typo in README.md
  examples/features/interceptor/README.md
Labels: Type: Internal Cleanup, no release notes

#3251 xds: Improve xds_lrs_test.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/testutils/channel.go
  xds/internal/testutils/fakexds/client.go
Labels: Type: Internal Cleanup

#3242 benchmark: include go and grpc version in result files
  benchmark/benchresult/main.go
  benchmark/stats/stats.go
Labels: Type: Internal Cleanup

#3226 godoc: clarify WithTimeout deprecation note
  dialoptions.go
Labels: Status: Requires Reporter Clarification, Type: Documentation

#3227 xds: support ack/nack
  xds/internal/client/cds.go
  xds/internal/client/cds_test.go
  xds/internal/client/client_test.go
  xds/internal/client/eds.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds.go
  xds/internal/client/rds.go
  xds/internal/client/types.go
  xds/internal/client/v2client.go
  xds/internal/client/v2client_ack_test.go
  xds/internal/client/v2client_test.go
Labels: Type: Feature, no release notes

#3249 grpclb: do not send redundant empty load reports to remote LB
  balancer/grpclb/grpclb_picker.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer/grpclb/grpclb_test.go
Labels: Type: Feature

#3255 grpc: Defer the unlock in newCCResolverWrapper
  resolver_conn_wrapper.go
Labels: Type: Internal Cleanup, no release notes

#3254 profiling: Fix a data race in the circular buffer.
  internal/profiling/buffer/buffer.go
  internal/profiling/buffer/buffer_appengine.go
  internal/profiling/profiling.go
Labels: Type: Bug, no release notes

#3256 xds: Improve balancer/xds_test.go.
  xds/internal/balancer/xds_test.go
  xds/internal/testutils/channel.go
  xds/internal/testutils/fakexds/client.go
Labels: Type: Internal Cleanup, no release notes

#3263 Change version to 1.27.0-dev
  version.go
Labels: Type: Internal Cleanup, no release notes

#3266 xds test: read ACK to clear req chan
  xds/internal/client/rds_test.go
Labels: Type: Internal Cleanup, no release notes

#3269 dns: fix timing-based test to be more reliable
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Testing, no release notes

#3247 xds: support multiple xds servers in bootstrap file
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
Labels: Type: Internal Cleanup, no release notes

#3270 xds: Improve xds_client_test.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/testutils/fakexds/client.go
  xds/internal/testutils/fakexds/server.go
Labels: Type: Internal Cleanup, Type: Testing

#3258 dns: report errors from A record lookups instead of zero addresses
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Bug

#3160 profiling: add proto and service
  internal/profiling/profiling.go
  profiling/profiling.go
  profiling/proto/service.pb.go
  profiling/proto/service.proto
  profiling/service/service.go
Labels: Type: Performance

#3259 xds: Improve xds_resolver_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/xdsclient.go
Labels: Type: Testing

#3216 trace: fix getting family for the method
  trace.go
  trace_test.go
Labels: Type: Bug

#3277 xds: Improve cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/testutils/fakexds/client.go
Labels: Type: Testing

#3167 codec/proto: reuse of marshal byte buffers
  Documentation/encoding.md
  codec.go
  encoding/encoding.go
  encoding/proto/proto.go
  encoding/proto/proto_test.go
  internal/leakcheck/leakcheck.go
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  preloader.go
  server.go
  stream.go
  vet.sh
Labels: Type: Performance

#3271 credentials/alts: Add Client Authorization Utility API
  credentials/alts/utils.go
  credentials/alts/utils_test.go
Labels: Type: Feature, no release notes

#3265 examples: add profiling
  examples/features/profiling/README.md
  examples/features/profiling/client/main.go
  examples/features/profiling/server/main.go
Labels: Type: Documentation

#3267 xds: client test cleanup
  xds/internal/client/cds_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/testutil_test.go
Labels: Type: Internal Cleanup, no release notes

#3279 xds: fix RDS flaky tests due to ACK
  xds/internal/client/rds_test.go
Labels: Type: Internal Cleanup, no release notes

#3285 internal: fix profiling go generate proto file path
  profiling/service/service.go
Labels: Type: Internal Cleanup, no release notes

#3284 xds: client test cleanup.
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/client/cds_test.go
  xds/internal/client/client_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/fakexds/fakexds.go
  xds/internal/client/fakexds/lrsserver.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/testutil_test.go
  xds/internal/client/v2client_ack_test.go
  xds/internal/client/v2client_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Internal Cleanup, Type: Testing

#3288 Fix resolver.ClientConnection to resolver.ClientConn
  resolver_conn_wrapper.go
Labels: Type: Internal Cleanup
