Repository grpc/grpc-go, pull requests merged in 2019-09, with the labels that each got.

#3001 doc: clarify client concurrency
  Documentation/concurrency.md
Labels: Type: Documentation, no release notes

#3007 github: add stalebot config
  .github/stale.yml
Labels: no release notes

#3008 github: add mergeable config
  .github/mergeable.yml
Labels: Type: Testing, no release notes

#3013 modules: add go 1.11 to go.mod
  go.mod
Labels: Type: Internal Cleanup, no release notes

#3016 vet: ignore status code from grep -L
  vet.sh
Labels: Type: Testing, no release notes

#3017 grpclb: fix deadlock in grpclb connection cache
  balancer/grpclb/grpclb_util.go
  balancer/grpclb/grpclb_util_test.go
Labels: Type: Bug

#3018 server: set and advertise max frame size of 16KB
  internal/transport/http2_server.go
  internal/transport/http_util.go
  test/channelz_test.go
Labels: Cherry Pick, Type: Security

#3025 internal: update proto library version
  .travis.yml
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  benchmark/grpc_testing/control.pb.go
  benchmark/grpc_testing/messages.pb.go
  benchmark/grpc_testing/payloads.pb.go
  benchmark/grpc_testing/services.pb.go
  benchmark/grpc_testing/stats.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  interop/grpc_testing/test.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  stats/grpc_testing/test.pb.go
  stress/grpc_testing/metrics.pb.go
  test/codec_perf/perf.pb.go
  test/grpc_testing/test.pb.go
  vet.sh
Labels: Type: Dependencies

#3031 test: fix channelz test for violating flow control
  test/channelz_test.go
Labels: Type: Testing, no release notes

#3034 client: consider service config invalid if loadBalancingConfig contains no supported policy
  service_config.go
  service_config_test.go
Labels: Type: Bug

#3033 Update governance, contributing, code of conduct docs
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: Type: Internal Cleanup

#3037 docs: fix debugging README typo
  examples/features/debugging/README.md
Labels: Type: Documentation, no release notes

#3041 Change version to 1.24.0
  version.go
Labels: Type: Documentation, no release notes

#3042 Change version to 1.24.1-dev
  version.go
Labels: Type: Documentation, no release notes

#3043 Change version to 1.25.0-dev
  version.go
Labels: Type: Documentation, no release notes

#3050 travis: add go1.13 and remove go1.10 and go1.9 without GAE
  .travis.yml
Labels: Type: Testing, no release notes

#3051 clientconn: fix potential deadlock caused by ResetConnectBackoff
  clientconn.go
Labels: Type: Bug

#3052 test: fix flake in GoAwayThenClose
  test/end2end_test.go
Labels: Type: Testing, no release notes

#3014 Move keepalive tests to a separate test file.
  internal/transport/keepalive_test.go
  internal/transport/transport_test.go
Labels: Type: Testing, no release notes

#3046 internal: fix typos in comments
  clientconn.go
  grpclog/grpclog.go
Labels: Type: Internal Cleanup, no release notes
