Repository grpc/grpc-go, pull requests merged in 2019-11, with the labels that each got.

#3136 transport: minor code simplification
  internal/transport/http2_client.go
Labels: Type: Internal Cleanup, no release notes

#3133 test & testutils: prevent goroutine leaks in test functions
  internal/testutils/pipe_listener_test.go
  test/bufconn/bufconn_test.go
  test/end2end_test.go
Labels: Type: Testing

#3138 docs: fix reflection doc
  Documentation/server-reflection-tutorial.md
Labels: Type: Documentation, no release notes

#3098 resolver: Add new fields to resolver.BuildOption struct to support dialing a remote name resolver
  resolver/resolver.go
  resolver_conn_wrapper.go
Labels: Type: Feature

#3099 Add a general purpose unbounded buffer implementation
  balancer_conn_wrappers.go
  internal/buffer/unbounded.go
  internal/buffer/unbounded_test.go
Labels: Type: Internal Cleanup

#3137 eds: skip unhealthy endpoints
  xds/internal/balancer/edsbalancer/balancergroup_test.go
  xds/internal/balancer/edsbalancer/edsbalancer.go
  xds/internal/balancer/edsbalancer/edsbalancer_test.go
Labels: Type: Feature

#3100 xds: add new fields to XDSConfig
  internal/proto/grpc_service_config/example_test.go
  internal/proto/grpc_service_config/regenerate.sh
  internal/proto/grpc_service_config/service_config.pb.go
  xds/internal/balancer/config.go
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_client.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/internal.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#3143 travis: move example tests to a separate run
  .travis.yml
Labels: Type: Internal Cleanup, no release notes

#3141 test: add test of malformed gzip payload
  test/end2end_test.go
Labels: Type: Testing, no release notes

#3148 Change version to 1.26.0-dev
  version.go
Labels: Type: Internal Cleanup, no release notes

#3066 xds: support priority
  xds/internal/balancer/edsbalancer/balancergroup.go
  xds/internal/balancer/edsbalancer/edsbalancer.go
  xds/internal/balancer/edsbalancer/edsbalancer_test.go
  xds/internal/balancer/edsbalancer/priority.go
  xds/internal/balancer/edsbalancer/priority_test.go
  xds/internal/balancer/edsbalancer/test_util_test.go
Labels: Type: Feature

#3153 cleanup: fix generic comparisons on protobuf messages
  status/status_test.go
  test/end2end_test.go
  test/retry_test.go
  xds/internal/balancer/lrs/lrs_test.go
Labels: Type: Internal Cleanup, no release notes

#3151 resolver: introduce attributes package and use it for Address and State
  attributes/attributes.go
  attributes/attributes_test.go
  resolver/resolver.go
  vet.sh
Labels: Type: API Change

#3154 internal: fix EDS test race in cmp/sort
  xds/internal/balancer/edsbalancer/edsbalancer_test.go
Labels: Type: Internal Cleanup, no release notes

#3140 xds: set client node.BuildVersion to gRPC version
  xds/internal/client/config.go
  xds/internal/client/config_test.go
Labels: Type: Internal Cleanup, no release notes

#3117 more detailed log message
  internal/binarylog/binarylog.go
Labels: Type: Internal Cleanup

#3166 examples: enable debugging to help determine why tests are hanging
  examples/examples_test.sh
Labels: Type: Testing, no release notes

#3162 resolver: re-add dns and passthrough packages as references to internal versions
  resolver/dns/dns_resolver.go
  resolver/passthrough/passthrough.go
Labels: Cherry Pick, Type: Dependencies

#3156 resolver: add deprecation note to AddressType and its values
  resolver/resolver.go
  vet.sh
Labels: Type: Documentation, no release notes

#2994 interop: add grpclb fallback test
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test.proto
  interop/grpclb_fallback/client.go
Labels: Type: Testing, no release notes

#3168 examples: change wait into job polling loop after killing tests
  examples/examples_test.sh
Labels: Type: Testing, no release notes

#3152 vet: revise staticcheck strategy
  clientconn.go
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#3149 dns: disable SRV record lookups unless grpclb is imported
  balancer/grpclb/grpclb.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Behavior Change

#3144 xds: Initial implementation of a client using the v2 API
  go.mod
  go.sum
  xds/internal/client/fakexds/fakexds.go
  xds/internal/client/lds.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds.go
  xds/internal/client/rds_test.go
  xds/internal/client/types.go
  xds/internal/client/v2client.go
  xds/internal/client/v2client_test.go
Labels: Type: Feature

#3175 resolver: rename Option to Options, leaving type aliases for now
  balancer/balancer.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer/grpclb/grpclb_test.go
  balancer/grpclb/grpclb_util.go
  balancer_conn_wrappers.go
  clientconn.go
  examples/features/load_balancing/client/main.go
  examples/features/name_resolving/client/main.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/resolver/passthrough/passthrough.go
  resolver/manual/manual.go
  resolver/resolver.go
  resolver_conn_wrapper.go
  resolver_conn_wrapper_test.go
  xds/internal/balancer/edsbalancer/test_util_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: API Change

#3176 xds: Move bootstrap functionality to a new package.
  xds/internal/balancer/xds_client.go
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
Labels: Type: Internal Cleanup

#3174 xds: replace eds proto message with xdsclient defined struct in eds balancer
  xds/internal/balancer/edsbalancer/edsbalancer.go
  xds/internal/balancer/edsbalancer/edsbalancer_test.go
  xds/internal/balancer/edsbalancer/priority_test.go
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_client.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/client/eds.go
  xds/internal/client/eds_test.go
  xds/internal/client/eds_testutil.go
  xds/internal/internal.go
Labels: Type: Internal Cleanup, no release notes

#3169 stats: attach metadata to In/Out Headers/Trailers
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  stats/stats.go
  stats/stats_test.go
Labels: Type: Feature

#3139 client: set grpc-accept-encoding header based on outgoing compressor
  internal/transport/http2_client.go
Labels: Type: Bug

#3181 xds: handle EDS in xds client
  xds/internal/balancer/xds_client.go
  xds/internal/client/eds.go
  xds/internal/client/eds_test.go
  xds/internal/client/eds_testutil.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds.go
  xds/internal/client/rds_test.go
  xds/internal/client/types.go
  xds/internal/client/v2client.go
  xds/internal/client/v2client_test.go
Labels: Type: Internal Cleanup, no release notes

#3183 xds: Implementation of xds_resolver using LDS/RDS
  xds/experimental/xds_experimental.go
  xds/internal/balancer/xds.go
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/client/fakexds/fakexds.go
  xds/internal/internal.go
  xds/internal/resolver/old/xds_resolver_old.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#3195 server: correct doc regarding unknown handlers and interceptors
  server.go
Labels: Type: Documentation, no release notes

#3172 server: Keepalive pings should be sent every [Time] period
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  test/channelz_test.go
Labels: Type: Bug

#3191 xds: Don't override dialFunc in xdsClient in tests.
  vet.sh
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/fakexds/fakexds.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/v2client_test.go
Labels: Type: Internal Cleanup

#3196 benchmark: Enable server keepalive in benchmarks
  benchmark/benchmain/main.go
Labels: Type: Internal Cleanup

#3186 balancer: add V2Picker, ClientConn.UpdateState, SubConnState.ConnectionError
  balancer/balancer.go
  balancer/base/balancer.go
  balancer/base/base.go
  balancer/grpclb/grpclb.go
  balancer/grpclb/grpclb_picker.go
  balancer/grpclb/grpclb_test.go
  balancer/grpclb/grpclb_util.go
  balancer/roundrobin/roundrobin.go
  balancer_conn_wrappers.go
  balancer_conn_wrappers_test.go
  balancer_switching_test.go
  balancer_test.go
  balancer_v1_wrapper.go
  clientconn.go
  grpc_test.go
  health/client.go
  health/client_test.go
  internal/internal.go
  picker_wrapper.go
  picker_wrapper_test.go
  pickfirst.go
  resolver_conn_wrapper_test.go
  test/balancer_test.go
  test/healthcheck_test.go
  vet.sh
  xds/internal/balancer/edsbalancer/balancergroup.go
  xds/internal/balancer/edsbalancer/balancergroup_test.go
  xds/internal/balancer/edsbalancer/edsbalancer.go
  xds/internal/balancer/edsbalancer/edsbalancer_test.go
  xds/internal/balancer/edsbalancer/priority.go
  xds/internal/balancer/edsbalancer/priority_test.go
  xds/internal/balancer/edsbalancer/test_util_test.go
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_test.go
Labels: Type: API Change

#3202 github: make stalebot monitor PRs, too
  .github/stale.yml
Labels: Type: Internal Cleanup, no release notes

#3197 xds: use the shared xds client in eds balancer
  xds/internal/balancer/config.go
  xds/internal/balancer/edsbalancer/test_util_test.go
  xds/internal/balancer/lrs/lrs.go
  xds/internal/balancer/lrs/lrs_test.go
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_client.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_client_wrapper.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/balancer/xds_old.go
  xds/internal/balancer/xds_test.go
  xds/internal/client/client.go
  xds/internal/client/client_loadreport.go
  xds/internal/client/eds.go
Labels: Type: Internal Cleanup, no release notes

#3201 dns: do not call NewServiceConfig when lookups are disabled
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  resolver_conn_wrapper.go
Labels: Type: Bug

#3165 dns: stop polling for updates; use UpdateState API
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Behavior Change

#3203 xds: CDS implementation in v2Client.
  xds/internal/client/cds.go
  xds/internal/client/cds_test.go
  xds/internal/client/eds.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds.go
  xds/internal/client/rds_test.go
  xds/internal/client/types.go
  xds/internal/client/v2client.go
Labels: Type: Feature

#3205 xds: in EDS balancer, use xds_client from attibutes
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_client_wrapper.go
  xds/internal/balancer/xds_test.go
Labels: Type: Internal Cleanup, no release notes

#3211 xds: Minor refactoring, prep for CDS LB policy
  xds/internal/client/cds.go
  xds/internal/client/cds_test.go
  xds/internal/client/client.go
  xds/internal/client/types.go
  xds/internal/client/v2client.go
Labels: Type: Internal Cleanup

#3209 xds: cleanup eds tests to use fakexds server
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/balancer/xds_test.go
  xds/internal/client/fakexds/fakexds.go
  xds/internal/client/fakexds/lrsserver.go
Labels: Type: Internal Cleanup, no release notes

#3213 Revert "dns: stop polling for updates; use UpdateState API"
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Internal Cleanup, no release notes

#3210 xds: change lrs server name field in xds balancer config to a string pointer
  xds/internal/balancer/config.go
  xds/internal/balancer/xds.go
  xds/internal/balancer/xds_client_test.go
  xds/internal/balancer/xds_client_wrapper.go
  xds/internal/balancer/xds_lrs_test.go
  xds/internal/balancer/xds_test.go
Labels: Type: Internal Cleanup, no release notes
