Repository grpc/grpc-go, pull requests merged in 2019-01, with the labels that each got.

#2545 rpc_util: update deprecated messages
  rpc_util.go
Labels: Type: Internal Cleanup, no release notes

#2552 grpctest: add example to show how it is used
  internal/grpctest/example_test.go
  internal/grpctest/grpctest.go
Labels: Type: Documentation, no release notes

#2572 cleanup: lower-case starting character of error strings
  internal/binarylog/env_config.go
Labels: Type: Internal Cleanup, no release notes

#2571 cleanup: use time.Until(t) instead of t.Sub(time.Now)
  clientconn.go
  dialoptions.go
  internal/transport/http2_client.go
  proxy_test.go
  server.go
  stream.go
  test/end2end_test.go
Labels: Type: Internal Cleanup, no release notes

#2573 cleanup: replace unnecessary loops
  internal/binarylog/binarylog_end2end_test.go
  test/healthcheck_test.go
Labels: Type: Internal Cleanup, no release notes

#2574 cleanup: more simplifications
  balancer/grpclb/grpclb_test.go
  examples/features/authentication/oauth/server/main.go
  examples/features/interceptor/server/main.go
  examples/features/load_balancing/client/main.go
  examples/features/name_resolving/client/main.go
  internal/binarylog/method_logger.go
  test/channelz_test.go
Labels: Type: Internal Cleanup, no release notes

#2581 cleanup: remove unused symbols
  clientconn.go
  credentials/alts/internal/conn/aes128gcmrekey_test.go
  credentials/alts/internal/handshaker/handshaker_test.go
  credentials/alts/internal/handshaker/service/service.go
  examples/features/metadata/server/main.go
  examples/features/name_resolving/server/main.go
  stream.go
Labels: Type: Internal Cleanup, no release notes

#2578 internal: split StateRecordingBalancer in test to balancer and builder
  clientconn_state_transition_test.go
  clientconn_test.go
Labels: Type: Testing

#2586 fix MaxSendMsgSize comments error
  server.go
Labels: Type: Internal Cleanup, no release notes

#2591 fix: typos
  backoff.go
  balancer/balancer.go
  call.go
  clientconn.go
  connectivity/connectivity.go
  naming/dns_resolver.go
  naming/naming.go
  resolver/dns/dns_resolver.go
Labels: Type: Internal Cleanup, no release notes

#2598 travis: add Go 1.12beta2 to CI
  .travis.yml
Labels: Type: Testing, no release notes

#2594 examples: reflection
  Documentation/server-reflection-tutorial.md
  examples/features/reflection/README.md
  examples/features/reflection/server/main.go
  examples/helloworld/greeter_server/main.go
Labels: Type: Documentation

#2600 Add google_default_credentials interop test case for go
  interop/client/client.go
  interop/test_utils.go
Labels: Type: Testing

#2603 client: fix handling of GRPC_GO_REQUIRE_HANDSHAKE=on to not interpret as "hybrid"
  internal/envconfig/envconfig.go
Labels: Type: Bug

#2511 client: minor v1 balancer wrapper fixes
  balancer/balancer.go
  balancer_v1_wrapper.go
  picker_wrapper.go
  test/end2end_test.go
Labels: Type: Bug

#2605 vet: use fail_on_output so user can see why git client is not porcelain
  vet.sh
Labels: Type: Testing, no release notes
