Repository grpc/grpc-go, pull requests merged in 2020-12, with the labels that each got.

#4071 xds: Handle child policy configs properly.
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/load_store_wrapper.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/testutils/balancer.go
Labels: Type: Bug, no release notes

#4046 xds: support server-side listeners in LDS response
  xds/internal/client/client.go
  xds/internal/client/client_lds_test.go
  xds/internal/client/client_rds_test.go
  xds/internal/client/client_xds.go
  xds/internal/version/version.go
Labels: Type: Feature, no release notes

#4069 advancedtls: fix default host name check issue
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/internal/testutils/testutils.go
  security/advancedtls/testdata/README.md
  security/advancedtls/testdata/localhost-openssl.cnf
  security/advancedtls/testdata/openssl-ca.cnf
  security/advancedtls/testdata/server_cert_localhost_1.pem
  security/advancedtls/testdata/server_key_localhost_1.pem
Labels: Type: Bug, no release notes

#4077 credentials/xds: Rename test file
  credentials/xds/xds_client_test.go
Labels: Type: Testing, no release notes

#4018 advancedtls: add reloading behaviors in examples
  security/advancedtls/examples/credential_reloading_from_files/README.md
  security/advancedtls/examples/credential_reloading_from_files/client/main.go
  security/advancedtls/examples/credential_reloading_from_files/server/main.go
  security/advancedtls/examples/examples_test.sh
  security/advancedtls/testdata/README.md
  security/advancedtls/testdata/another_client_cert_1.pem
  security/advancedtls/testdata/another_client_key_1.pem
Labels: no release notes

#4081 test: move stubServer to separate package in internal
  internal/stubserver/stubserver.go
  test/authority_test.go
  test/balancer_test.go
  test/channelz_test.go
  test/context_canceled_test.go
  test/end2end_test.go
  test/goaway_test.go
  test/gracefulstop_test.go
  test/insecure_creds_test.go
  test/local_creds_test.go
  test/resolver_test.go
  test/retry_test.go
  test/server_test.go
  test/stream_cleanup_test.go
Labels: Type: Testing, no release notes

#4086 eds/lrs: handle nil when LRS is disabled
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/load_store_wrapper.go
  xds/internal/balancer/lrs/balancer.go
Labels: Cherry Pick, Type: Bug

#4087 xds: `server_features` should be a child of `xds_servers` and not a sibling
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/testutils/e2e/bootstrap.go
Labels: Type: Bug

#4090 xds: Process `require_client_cert` field in security config
  xds/internal/client/client.go
  xds/internal/client/client_lds_test.go
  xds/internal/client/client_xds.go
Labels: Type: Bug, no release notes

#4082 resolver: allow config selector to return an RPC error
  clientconn.go
  internal/resolver/config_selector.go
  internal/resolver/config_selector_test.go
  stream.go
  test/resolver_test.go
Labels: Type: Feature, no release notes

#4050 xds: Implement circuit breaking support.
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/client/client.go
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_requests_counter.go
  xds/internal/client/client_requests_counter_test.go
  xds/internal/client/client_xds.go
  xds/internal/env/env.go
Labels: Type: Feature

#4088 internal/syscall: make Rusage a type alias
  internal/syscall/syscall_linux.go
  internal/syscall/syscall_nonlinux.go
Labels: Type: Internal Cleanup, no release notes

#4098 Update envoyproxy/go-control-plane
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
Labels: Type: Internal Cleanup, no release notes

#4102 github: Run only a subset of tests for Go1.11
  .github/workflows/testing.yml
Labels: Type: Testing, no release notes

#4104 github: Get tests111 to actually run subset of tests
  .github/workflows/testing.yml
Labels: Type: Testing, no release notes

#4089 credentials/xds: ServerHandshake() implementation
  credentials/xds/xds.go
  credentials/xds/xds_client_test.go
  credentials/xds/xds_server_test.go
  go.sum
Labels: Type: Feature, no release notes

#4083 xds: split routing balancer into config selector + cluster manager
  xds/internal/balancer/balancer.go
  xds/internal/balancer/clustermanager/balancerstateaggregator.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/clustermanager/config.go
  xds/internal/balancer/clustermanager/config_test.go
  xds/internal/balancer/clustermanager/picker.go
  xds/internal/balancer/xdsrouting/matcher.go
  xds/internal/balancer/xdsrouting/routing.go
  xds/internal/balancer/xdsrouting/routing_config.go
  xds/internal/balancer/xdsrouting/routing_config_test.go
  xds/internal/balancer/xdsrouting/routing_picker_test.go
  xds/internal/resolver/matcher.go
  xds/internal/resolver/matcher_header.go
  xds/internal/resolver/matcher_header_test.go
  xds/internal/resolver/matcher_path.go
  xds/internal/resolver/matcher_path_test.go
  xds/internal/resolver/matcher_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_action.go
  xds/internal/resolver/serviceconfig_action_test.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/test/xds_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/balancer.go
Labels: Type: Internal Cleanup, no release notes

#4111 xds: Expect certprovider bootstrap configs when xdsCreds are in use
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Behavior Change, no release notes

#4112 testing: stop listening on externally-visible devices
  security/advancedtls/advancedtls_integration_test.go
  xds/internal/testutils/e2e/server.go
  xds/internal/testutils/local_listener.go
Labels: Type: Testing, no release notes

#4113 xds: NACK resource when security config is not as expected
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_lds_test.go
  xds/internal/client/client_xds.go
Labels: Type: Internal Cleanup, no release notes

#4114 pemfile: Update distributor only inside of the for loop
  credentials/tls/certprovider/pemfile/watcher.go
Labels: Type: Bug, no release notes

#4092 xds: Implement server-side security
  internal/internal.go
  server.go
  xds/internal/client/client.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/e2e/bootstrap.go
  xds/server.go
  xds/server_test.go
Labels: Type: Feature, no release notes

#4115 xds: Ignore application_protocols field for now
  xds/internal/client/client_lds_test.go
  xds/internal/client/client_xds.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Internal Cleanup, no release notes

#4117 credentials/xds: Move non-user facing functionality to an internal package
  credentials/xds/xds.go
  credentials/xds/xds_client_test.go
  credentials/xds/xds_server_test.go
  internal/credentials/xds/handshake_info.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/server.go
Labels: Type: Internal Cleanup, no release notes

#4116 xds: implement RouteAction timeout support
  internal/wrr/random.go
  xds/internal/client/client.go
  xds/internal/client/client_rds_test.go
  xds/internal/client/client_xds.go
  xds/internal/env/env.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/wrr.go
Labels: Type: Feature

#4101 advancedtls: add IPv6 address to certificate SAN names
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/testdata/localhost-openssl.cnf
  security/advancedtls/testdata/server_cert_localhost_1.pem
  security/advancedtls/testdata/server_key_localhost_1.pem
Labels: Type: Testing, no release notes

#4079 support unix-abstract schema
  clientconn.go
  internal/grpcutil/target.go
  internal/grpcutil/target_test.go
  internal/resolver/unix/unix.go
  internal/transport/http2_client.go
  test/authority_test.go
Labels: Status: Requires Reporter Clarification, Type: Feature

#4130 github: improve security policy documentation
  SECURITY.md
Labels: Type: Documentation, no release notes

#4131 github: update bug template to link to the CVE process
  .github/ISSUE_TEMPLATE/bug.md
Labels: Type: Documentation, no release notes
