Repository grpc/grpc-go, pull requests merged in 2020-08, with the labels that each got.

#3788 xds: Avoid mutex copy in log statement.
  xds/internal/client/v2/client.go
Labels: Type: Internal Cleanup, no release notes

#3786 testdata: Update testdata certs.
  balancer/rls/internal/balancer_test.go
  benchmark/worker/benchmark_client.go
  benchmark/worker/benchmark_server.go
  clientconn_test.go
  credentials/credentials_test.go
  credentials/tls/certprovider/store_test.go
  examples/data/data.go
  examples/data/x509/ca_cert.pem
  examples/data/x509/server_cert.pem
  examples/data/x509/server_key.pem
  examples/features/authentication/client/main.go
  examples/features/authentication/server/main.go
  examples/features/encryption/README.md
  examples/features/encryption/TLS/client/main.go
  examples/features/encryption/TLS/server/main.go
  examples/features/interceptor/client/main.go
  examples/features/interceptor/server/main.go
  examples/route_guide/client/client.go
  examples/route_guide/server/server.go
  interop/client/client.go
  interop/fake_grpclb/fake_grpclb.go
  interop/interop_test.sh
  interop/server/server.go
  stress/client/main.go
  test/balancer_test.go
  test/channelz_test.go
  test/creds_test.go
  test/end2end_test.go
  testdata/ca.pem
  testdata/server1.key
  testdata/server1.pem
  testdata/x509/README.md
  testdata/x509/client1_cert.pem
  testdata/x509/client1_key.pem
  testdata/x509/client2_cert.pem
  testdata/x509/client2_key.pem
  testdata/x509/client_ca_cert.pem
  testdata/x509/client_ca_key.pem
  testdata/x509/create.sh
  testdata/x509/openssl.cnf
  testdata/x509/server1_cert.pem
  testdata/x509/server1_key.pem
  testdata/x509/server2_cert.pem
  testdata/x509/server2_key.pem
  testdata/x509/server_ca_cert.pem
  testdata/x509/server_ca_key.pem
Labels: Type: Internal Cleanup, no release notes

#3784 xds: Pass WatchExpiryTimeout to Client via Options.
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/client/client_watchers.go
  xds/internal/client/client_watchers_cluster_test.go
  xds/internal/client/client_watchers_endpoints_test.go
  xds/internal/client/client_watchers_lds_test.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service_test.go
Labels: Type: Testing, no release notes

#3777 advancedtls: add spiffe support in aTLS
  security/advancedtls/advancedtls.go
  security/advancedtls/go.mod
  security/advancedtls/go.sum
Labels: Type: Feature

#3774 advancedtls: fixed SNI testing and put SNI functions back in advancedtls.go
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/sni.go
  security/advancedtls/sni_test_disabled.go
Labels: Type: Testing, no release notes

#3779 grpc: Minor refactor in server code.
  server.go
Labels: Type: Internal Cleanup, no release notes

#3719 internal: clean up all usages of grpclog, and replace with component
  benchmark/benchmain/main.go
  benchmark/benchmark.go
  benchmark/client/main.go
  benchmark/server/main.go
  benchmark/worker/benchmark_client.go
  benchmark/worker/benchmark_server.go
  benchmark/worker/main.go
  connectivity/connectivity.go
  credentials/google/google.go
  credentials/sts/sts.go
  grpclog/component.go
  health/logging.go
  health/server.go
  internal/binarylog/binarylog_end2end_test.go
  internal/credentials/spiffe.go
  internal/serviceconfig/serviceconfig.go
  interop/alts/client/client.go
  interop/alts/server/server.go
  interop/client/client.go
  interop/fake_grpclb/fake_grpclb.go
  interop/http2/negative_http2_client.go
  interop/server/server.go
  interop/test_utils.go
  interop/xds/client/client.go
  interop/xds/server/server.go
  profiling/cmd/catapult.go
  profiling/cmd/local.go
  profiling/cmd/main.go
  profiling/cmd/remote.go
  profiling/service/service.go
  stress/client/main.go
  stress/metrics_client/main.go
  test/balancer_test.go
  test/end2end_test.go
  test/logging.go
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#3783 xds: Improve TestClientWrapperWatchEDS.
  xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Testing, no release notes

#3707 security/authorization: Added CEL-based authorization engine
  Makefile
  security/authorization/engine/engine.go
  security/authorization/engine/engine_test.go
  security/authorization/go.mod
  security/authorization/go.sum
Labels: no release notes

#3780 credentials: Migrate helper functions to /internal/credentials for future cleanup
  credentials/credentials_test.go
  credentials/tls.go
  internal/credentials/syscallconn.go
  internal/credentials/syscallconn_test.go
  internal/credentials/util.go
  internal/credentials/util_test.go
Labels: Type: Internal Cleanup, no release notes

#3804 internal: fix interop tests which rely on the old certs/keys
  interop/client/client.go
  interop/fake_grpclb/fake_grpclb.go
  interop/interop_test.sh
  interop/server/server.go
  testdata/README.md
  testdata/ca.pem
  testdata/server1.key
  testdata/server1.pem
Labels: Type: Bug, no release notes

#3802 internal/serviceconfig: Fix typo and improve docs.
  internal/serviceconfig/serviceconfig.go
Labels: Type: Documentation, no release notes

#3800 internal/wrr: introduce order offset to edf scheduler as a tiebreaker for entries with same deadline
  internal/wrr/edf.go
  internal/wrr/edf_test.go
Labels: Type: Behavior Change

#3807 meshca: Pull in the MeshCA config proto from grpc-proto repo.
  credentials/tls/certprovider/meshca/internal/meshca_experimental/config.pb.go
  regenerate.sh
  vet.sh
Labels: Type: Feature, no release notes

#3799 xds: add LRS balancing policy
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/balancer/lrs/config.go
  xds/internal/balancer/lrs/config_test.go
  xds/internal/balancer/lrs/logging.go
  xds/internal/balancer/lrs/picker.go
  xds/internal/balancer/lrs/store.go
  xds/internal/balancer/lrs/store_test.go
  xds/internal/internal.go
Labels: Type: Feature

#3814 meshca: Pull in the MeshCA service proto from istio repo.
  credentials/tls/certprovider/meshca/internal/v1/meshca.pb.go
  credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
  regenerate.sh
Labels: Type: Feature, no release notes

#3815 xds: Fix TestV2ClientBackoffAfterRecvError
  xds/internal/client/v2/client_test.go
Labels: Type: Testing, no release notes

#3813 examples: update grpc version
  examples/features/debugging/client/main.go
  examples/features/load_balancing/README.md
  examples/features/load_balancing/client/main.go
  examples/go.mod
  examples/go.sum
Labels: Type: Documentation, no release notes

#3816 server: Add ServiceRegistrar interface.
  server.go
Labels: Type: API Change, no release notes

#3818 grpc: Bump up support package version.
  rpc_util.go
Labels: Type: API Change, no release notes

#3817 xds: Export a WatchListener() method on the xdsClient.
  xds/internal/client/client.go
  xds/internal/client/client_callback.go
  xds/internal/client/client_test.go
  xds/internal/client/client_watchers.go
  xds/internal/client/client_watchers_cluster_test.go
  xds/internal/client/client_watchers_endpoints_test.go
  xds/internal/client/client_watchers_lds_test.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service_test.go
  xds/internal/client/client_xds.go
  xds/internal/client/transport_helper.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/client_ack_test.go
  xds/internal/client/v2/client_cds_test.go
  xds/internal/client/v2/client_eds_test.go
  xds/internal/client/v2/client_lds_test.go
  xds/internal/client/v2/client_rds_test.go
  xds/internal/client/v2/client_test.go
  xds/internal/client/v3/client.go
  xds/xds.go
Labels: Type: Feature, no release notes

#3822 security/authorization: util function for converting CEL expression string
  security/authorization/engine/engine.go
  security/authorization/util/util.go
  security/authorization/util/util_test.go
Labels: Type: Feature, no release notes

#3831 transport: use escaped string instead of int->string conversion
  internal/transport/http_util_test.go
Labels: Type: Testing, no release notes

#3830 eds: fix priority timeout failure when EDS removes all priorities
  xds/internal/balancer/edsbalancer/eds_impl_priority.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Labels: Cherry Pick, Type: Bug

#3839 eds: fix priority timeout failure when EDS removes all priorities (cherry pick of #3830)
  xds/internal/balancer/edsbalancer/eds_impl_priority.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Labels: no release notes

#3840 eds: fix priority timeout failure when EDS removes all priorities (cherry pick of #3830)
  xds/internal/balancer/edsbalancer/eds_impl_priority.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Labels: no release notes

#3838 internal: reintroduce legacy appengine build constraints
  internal/channelz/types_linux.go
  internal/channelz/types_nonlinux.go
  internal/channelz/util_linux.go
  internal/channelz/util_test.go
  internal/credentials/spiffe.go
  internal/credentials/syscallconn.go
  internal/credentials/syscallconn_test.go
  internal/profiling/buffer/buffer.go
  internal/profiling/buffer/buffer_appengine.go
  internal/profiling/buffer/buffer_test.go
  internal/syscall/syscall_linux.go
  internal/syscall/syscall_nonlinux.go
  interop/grpclb_fallback/client.go
  test/go_vet/vet.go
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#3846 Change version to 1.33.0-dev
  version.go
Labels: no release notes

#3809 security/authorization: add integration tests
  security/authorization/engine/engine.go
  security/authorization/engine/engine_test.go
  security/authorization/engine/util.go
  security/authorization/engine/util_test.go
  security/authorization/go.mod
Labels: no release notes

#3849 cmd/protoc-gen-go-grpc: call interceptor even if handler is unset
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  benchmark/grpc_testing/services_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stats/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/grpc_testing/test_grpc.pb.go
Labels: Type: Bug, no release notes

#3835 testutils: Add a context parameter to the Receive() method.
  balancer/rls/internal/balancer_test.go
  balancer/rls/internal/client_test.go
  balancer/rls/internal/picker_test.go
  credentials/sts/sts_test.go
  credentials/tls/certprovider/store_test.go
  internal/testutils/channel.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/client/client_test.go
  xds/internal/client/client_watchers_cluster_test.go
  xds/internal/client/client_watchers_endpoints_test.go
  xds/internal/client/client_watchers_lds_test.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service_test.go
  xds/internal/client/v2/client_ack_test.go
  xds/internal/client/v2/client_rds_test.go
  xds/internal/client/v2/client_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/balancer.go
  xds/internal/testutils/channel.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Internal Cleanup, no release notes

#3852 internal: fix build for gae
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/advancedtls/sni.go
Labels: no release notes
