Repository grpc/grpc-go, pull requests merged in 2020-10, with the labels that each got.

#3919 internal/balancer: Remove a TODO in stub balancer.
  internal/balancer/stub/stub.go
Labels: Type: Internal Cleanup, no release notes

#3917 cleanup: standardize "experimental" warnings across all packages
  attributes/attributes.go
  backoff.go
  balancer/weightedroundrobin/weightedroundrobin.go
  clientconn.go
  credentials/local/local.go
  credentials/tls.go
  dialoptions.go
  encoding/encoding.go
  encoding/gzip/gzip.go
  grpclog/loggerv2.go
  interceptor.go
  internal/grpclog/grpclog.go
  preloader.go
  profiling/profiling.go
  profiling/service/service.go
  resolver/resolver.go
  rpc_util.go
  server.go
  serviceconfig/serviceconfig.go
  tap/tap.go
Labels: Type: Documentation, no release notes

#3921 cmd/protoc-gen-go-grpc: add --version flag support
  cmd/protoc-gen-go-grpc/main.go
Labels: Type: Feature, no release notes

#3922 xds/bootstrap: Use correct format for "certificate_providers" field.
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
Labels: Type: Bug, no release notes

#3923 stalebot: send first ping after 6 days
  .github/stale.yml
Labels: Type: Internal Cleanup, no release notes

#3920 xds: Refactor/cleanup xds client tests.
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_test.go
  xds/internal/client/client_watchers_cluster_test.go
  xds/internal/client/client_watchers_endpoints_test.go
  xds/internal/client/client_watchers_lds_test.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service_test.go
Labels: Type: Testing, no release notes

#3926 http2_client: fix reader segfault on PROTOCOL_ERRORs
  internal/transport/http2_client.go
Labels: Type: Bug

#3916 xds: Cleanup CDS balancer code and tests.
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Labels: Type: Internal Cleanup, no release notes

#3925 channelz: remove redundant case from AddTraceEvent and remove caps from severities
  channelz/service/service_test.go
  clientconn.go
  internal/channelz/funcs.go
  internal/channelz/logging.go
  internal/channelz/types.go
  resolver_conn_wrapper.go
Labels: Type: Internal Cleanup

#3905 lrs: add Store.Stats() to report loads for multiple clusters
  xds/internal/balancer/balancergroup/balancergroup_test.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/client/load/store.go
  xds/internal/client/load/store_test.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/loadreport.go
  xds/internal/client/v3/client.go
  xds/internal/client/v3/loadreport.go
Labels: Type: Feature, no release notes

#3938 Change version to 1.33.0
  version.go
Labels: no release notes

#3942 Revert "Change version to 1.33.0"
  version.go
Labels: no release notes

#3941 Change version to 1.34.0-dev
  version.go
Labels: no release notes

#3931 xds/client: Process security configuration from Cluster resource
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/go.sum
  vet.sh
  xds/internal/client/client.go
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_xds.go
  xds/internal/version/version.go
Labels: Type: Feature, no release notes

#3889 cmd/protoc-gen-go-grpc: fix method name in interceptor info
  cmd/protoc-gen-go-grpc/grpc.go
Labels: Status: Requires Reporter Clarification, Type: Bug, no release notes

#3940 Change version to 1.33.1-dev
  version.go
Labels: no release notes

#3929 internal/credentials: fix a bug and add one more helper function SPIFFEIDFromCert
  internal/credentials/spiffe.go
  internal/credentials/spiffe_test.go
  testdata/x509/create.sh
  testdata/x509/multiple_uri_cert.pem
  testdata/x509/multiple_uri_key.pem
  testdata/x509/spiffe_cert.pem
  testdata/x509/spiffe_key.pem
Labels: Type: Bug

#3897 advancedtls: clean up test files and shared code
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/internal/testutils/testutils.go
  security/advancedtls/pemfile_provider_test.go
Labels: Type: Internal Cleanup, no release notes

#3954 meshca: Use grpc suffix for grpc specific generated code.
  credentials/tls/certprovider/meshca/plugin.go
Labels: Type: Internal Cleanup, no release notes

#3958 encoding/proto: simplify & optimize proto codec
  encoding/proto/proto.go
Labels: Type: Performance

#3959 advancedtls: Get Instant Updates Before Ticker Runs
  security/advancedtls/pemfile_provider.go
Labels: Type: Bug, no release notes

#3944 xdsClient: change WatchRDS to return all virtual hosts
  xds/internal/client/client.go
  xds/internal/client/client_rds_test.go
  xds/internal/client/client_watchers.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service_test.go
  xds/internal/client/client_xds.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/client_rds_test.go
  xds/internal/client/v2/client_test.go
  xds/internal/client/v3/client.go
Labels: Type: Feature

#3934 advancedtls: add PemFileProvider integration tests
  security/advancedtls/advancedtls_integration_test.go
Labels: Type: Testing, no release notes

#3968 cmd/protoc-gen-go-grpc: use grpc.ServiceRegistrar instead of *grpc.Server
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  benchmark/grpc_testing/services_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stats/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/grpc_testing/test_grpc.pb.go
Labels: Type: Bug, no release notes

#3964 credentials/insecure: Implement insecure credentials.
  credentials/insecure/insecure.go
  test/insecure_creds_test.go
Labels: Type: Feature

#3932 protobuf: update all generated code to google.golang.org/protobuf
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_config.pb.go
  benchmark/grpc_testing/control.pb.go
  benchmark/grpc_testing/messages.pb.go
  benchmark/grpc_testing/payloads.pb.go
  benchmark/grpc_testing/services.pb.go
  benchmark/grpc_testing/stats.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  credentials/tls/certprovider/meshca/internal/meshca_experimental/config.pb.go
  credentials/tls/certprovider/meshca/internal/v1/meshca.pb.go
  encoding/proto/proto_test.go
  examples/examples_test.sh
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/client/client.go
  examples/route_guide/routeguide/route_guide.pb.go
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_service_config/service_config.pb.go
  interop/grpc_testing/test.pb.go
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  regenerate.sh
  stats/grpc_testing/test.pb.go
  stress/grpc_testing/metrics.pb.go
  test/codec_perf/perf.pb.go
  test/grpc_testing/test.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: no release notes

#3960 manual resolver: delete GenerateAndRegisterManualResolver
  resolver/manual/manual.go
Labels: no release notes

#3975 xdsclient: populate error details for NACK
  xds/internal/client/client_xds.go
  xds/internal/client/transport_helper.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/client_ack_test.go
  xds/internal/client/v3/client.go
Labels: Type: Bug

#3965 credentials/xds: Handle unspecified acceptedSANs correctly.
  credentials/xds/xds.go
  credentials/xds/xds_test.go
Labels: Type: Bug, no release notes

#3962 Add GitHub release action
  .github/workflows/release.yml
Labels: Type: Feature, no release notes

#3984 cmd/protoc-gen-go-grpc: bump -version to 1.0.1 for release
  cmd/protoc-gen-go-grpc/main.go
Labels: Type: Documentation, no release notes

#3948 Remove experimental comment from client interceptors
  interceptor.go
Labels: Status: Requires Reporter Clarification, Type: Documentation

#3935 lrs: handle multiple clusters in LRS stream
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/client/client.go
  xds/internal/client/client_loadreport.go
  xds/internal/client/client_loadreport_test.go
  xds/internal/client/client_test.go
  xds/internal/client/transport_helper.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/loadreport.go
  xds/internal/client/v3/client.go
  xds/internal/client/v3/loadreport.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Feature

#3976 advancedtls: add examples for reloading from file system
  .travis.yml
  security/advancedtls/examples/credential_reloading_from_files/README.md
  security/advancedtls/examples/credential_reloading_from_files/client/main.go
  security/advancedtls/examples/credential_reloading_from_files/server/main.go
  security/advancedtls/examples/examples_test.sh
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
Labels: no release notes

#3979 Documentation: fix outgoing metadata example code
  Documentation/grpc-metadata.md
Labels: Status: Requires Reporter Clarification, Type: Documentation

#3989 xds: Minor cleanup in client/v2 tests.
  xds/internal/client/v2/client_ack_test.go
  xds/internal/client/v2/client_rds_test.go
  xds/internal/client/v2/client_test.go
Labels: Type: Testing, no release notes

#3993 doc: update keepalive.md to add why
  Documentation/keepalive.md
Labels: Type: Documentation

#3936 priority: add policy config parsing
  xds/internal/balancer/priority/config.go
  xds/internal/balancer/priority/config_test.go
  xds/internal/balancer/priority/doc.go
Labels: Type: Feature

#3985 internal/transport: fix a bug causing -bin metadata to be incorrectly encoded
  internal/transport/http2_client.go
Labels: Type: Bug

#3988 xds: check name of transport socket received in Cluster response.
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_xds.go
Labels: Type: Bug, no release notes

#4005 github: add Github Actions workflow for tests; support in vet.sh
  .github/workflows/testing.yml
  vet.sh
Labels: Type: Testing, no release notes

#3955 xds: CDS balancer security integration.
  credentials/tls/certprovider/store.go
  credentials/xds/xds.go
  credentials/xds/xds_test.go
  internal/internal.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/client/client.go
  xds/internal/testutils/balancer.go
  xds/internal/testutils/fakeclient/client.go
Labels: Type: Feature, no release notes

#3981 pemfile: Move file watcher plugin from advancedtls to gRPC
  credentials/tls/certprovider/pemfile/watcher.go
  credentials/tls/certprovider/pemfile/watcher_test.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/pemfile_provider.go
  security/advancedtls/pemfile_provider_test.go
Labels: Type: Internal Cleanup, no release notes
