Repository grpc/grpc-go, pull requests merged in 2020-07, with the labels that each got.

#3684 service config: add default method config support
  clientconn.go
  clientconn_test.go
  service_config.go
  service_config_test.go
Labels: Type: Feature

#3696 credentials/sts: PerRPCCreds Implementation
  credentials/sts/sts.go
  credentials/sts/sts_test.go
Labels: Type: Feature

#3731 cleanup: fix mention of healthcheck to health
  clientconn.go
Labels: Type: Internal Cleanup, no release notes

#3699 codes: document which error codes can be returned by the framework
  codes/codes.go
Labels: Type: Documentation, no release notes

#3702 doc: fix references to status methods
  Documentation/rpc-errors.md
Labels: Type: Documentation

#3723 xds: Add v3 support for client bootstrap.
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/protos.go
  xds/internal/version/version.go
Labels: Type: Feature, no release notes

#3738 examples: cleanup README.md
  examples/README.md
Labels: Type: Documentation

#3736 README: adjust links, and slight rework of page
  README.md
Labels: Type: Documentation, no release notes

#3741 credentials/alts: Change ALTS hsConn to a map
  credentials/alts/internal/handshaker/service/service.go
  credentials/alts/internal/handshaker/service/service_test.go
Labels: Type: Bug, no release notes

#3626 credentials: check and expose SPIFFE ID
  credentials/tls.go
  internal/credentials/go110.go
  internal/credentials/go110_test.go
  internal/credentials/gobefore110.go
Labels: Type: Feature

#3742 balancer: remove deprecated type aliases as planned
  balancer/balancer.go
  balancer/base/base.go
  balancer/rls/internal/balancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Labels: Type: API Change

#3729 xds: delete experimental package and experimental scheme
  xds/experimental/xds_experimental.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Internal Cleanup, no release notes

#3745 examples: change xds example to import xds instead of experimental
  examples/features/xds/client/main.go
Labels: Type: Internal Cleanup, no release notes

#3733 xdsrouting: all matchers
  xds/internal/balancer/xdsrouting/doc.go
  xds/internal/balancer/xdsrouting/matcher.go
  xds/internal/balancer/xdsrouting/matcher_header.go
  xds/internal/balancer/xdsrouting/matcher_header_test.go
  xds/internal/balancer/xdsrouting/matcher_path.go
  xds/internal/balancer/xdsrouting/matcher_path_test.go
  xds/internal/balancer/xdsrouting/matcher_test.go
Labels: Type: Feature

#3734 xdsrouting: balancer config parsing
  xds/internal/balancer/xdsrouting/routing_config.go
  xds/internal/balancer/xdsrouting/routing_config_test.go
  xds/internal/client/client_watchers_rds.go
Labels: Type: Feature

#3748 xdsrouting: add fake headers
  internal/grpcutil/encode_duration.go
  internal/grpcutil/encode_duration_test.go
  internal/grpcutil/metadata.go
  internal/grpcutil/method.go
  internal/grpcutil/method_test.go
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
  stream.go
  test/balancer_test.go
  xds/internal/balancer/xdsrouting/matcher.go
  xds/internal/balancer/xdsrouting/matcher_test.go
  xds/internal/balancer/xdsrouting/routing_config.go
Labels: Type: Feature

#3747 xdsrouting: handle route fields in xds_client
  xds/internal/client/client_watchers_rds.go
  xds/internal/client/client_watchers_service.go
  xds/internal/client/client_watchers_service_test.go
  xds/internal/client/envconfig.go
  xds/internal/client/v2client_rds.go
  xds/internal/client/v2client_rds_test.go
Labels: Type: Feature

#3730 client: set auth header to localhost for unix target
  clientconn.go
  test/authority_test.go
  test/end2end_test.go
Labels: Type: Bug

#3751 xdsrouting: resolver to generate service config with routes, and pick routing balancer
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_action.go
  xds/internal/resolver/serviceconfig_action_test.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#3757 Change version to 1.32.0-dev
  version.go
Labels: Type: Internal Cleanup, no release notes

#3754 xdsrouting: remove env variable for routing
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/client_watchers_rds.go
  xds/internal/client/client_watchers_rds_test.go
  xds/internal/client/client_watchers_service.go
  xds/internal/client/client_watchers_service_test.go
  xds/internal/client/envconfig.go
  xds/internal/client/v2client_rds.go
  xds/internal/client/v2client_rds_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Cherry Pick, Type: Feature

#3737 xds interop: update interop client to support new tests
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test.proto
  interop/xds/client/client.go
  interop/xds/server/server.go
Labels: Cherry Pick, Type: Testing, no release notes

#3697 advancedtls: Add SNI logic to ServerOptions.GetCertificate
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/go.mod
  security/advancedtls/sni_110.go
  security/advancedtls/sni_before_110.go
  security/advancedtls/sni_test_110.go
  security/advancedtls/sni_test_before_110.go
  security/advancedtls/testdata/server_cert_1.txt
  security/advancedtls/testdata/server_cert_2.txt
  security/advancedtls/testdata/server_cert_3.pem
  security/advancedtls/testdata/server_cert_3.txt
  security/advancedtls/testdata/server_key_3.pem
Labels: Type: Feature

#3764 xds testing: add path_matching and header_matching
  test/kokoro/xds.sh
Labels: Cherry Pick, no release notes

#3763 interop: update --fail_on_failed_rpc to wait for initial success
  interop/xds/client/client.go
Labels: Cherry Pick, Type: Testing, no release notes

#3765 typo: upate->update
  xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
  xds/internal/balancer/xdsrouting/balancerstateaggregator.go
  xds/internal/client/client_watchers_cluster_test.go
  xds/internal/client/client_watchers_endpoints_test.go
  xds/internal/client/client_watchers_lds_test.go
  xds/internal/client/client_watchers_rds_test.go
Labels: Type: Internal Cleanup, no release notes

#3766 internal: delete mock from examples
  Documentation/gomock-example.md
  examples/go.mod
  examples/helloworld/mock_helloworld/hw_mock.go
  examples/helloworld/mock_helloworld/hw_mock_test.go
  examples/route_guide/mock_routeguide/rg_mock.go
  examples/route_guide/mock_routeguide/rg_mock_test.go
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#3768 README: change badge to pkg.go.dev
  README.md
Labels: Type: Documentation, no release notes

#3772 examples: break from 'PerRPCCredsCallOption' status checking loop
  examples/features/interceptor/client/main.go
Labels: Type: Internal Cleanup, no release notes

#3773 advancedtls: migrate testing to grpctest
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Testing, no release notes

#3767 Remove Go 1.9 / AppEngine support; assume go1.12 build tag
  .travis.yml
  CONTRIBUTING.md
  Makefile
  balancer/rls/internal/balancer.go
  balancer/rls/internal/balancer_test.go
  balancer/rls/internal/builder.go
  balancer/rls/internal/client_test.go
  balancer/rls/internal/config.go
  balancer/rls/internal/config_test.go
  balancer/rls/internal/keys/builder.go
  balancer/rls/internal/keys/builder_test.go
  balancer/rls/internal/picker.go
  balancer/rls/internal/picker_test.go
  channelz/service/func_linux.go
  channelz/service/func_nonlinux.go
  channelz/service/service_sktopt_test.go
  channelz/service/service_test.go
  channelz/service/util_sktopt_386_test.go
  channelz/service/util_sktopt_amd64_test.go
  credentials/go12.go
  credentials/internal/syscallconn.go
  credentials/internal/syscallconn_appengine.go
  credentials/internal/syscallconn_test.go
  credentials/tls.go
  examples/features/xds/client/main.go
  examples/features/xds/server/main.go
  install_gae.sh
  internal/channelz/types_linux.go
  internal/channelz/types_nonlinux.go
  internal/channelz/util_linux.go
  internal/channelz/util_nonlinux.go
  internal/channelz/util_test.go
  internal/credentials/gobefore110.go
  internal/credentials/spiffe.go
  internal/credentials/spiffe_test.go
  internal/profiling/buffer/buffer.go
  internal/profiling/buffer/buffer_appengine.go
  internal/profiling/buffer/buffer_test.go
  internal/profiling/profiling_test.go
  internal/syscall/syscall_linux.go
  internal/syscall/syscall_nonlinux.go
  interop/grpclb_fallback/client.go
  security/advancedtls/sni.go
  security/advancedtls/sni_110.go
  security/advancedtls/sni_test_before_110.go
  security/advancedtls/sni_test_disabled.go
  test/channelz_linux_go110_test.go
  test/go_vet/vet.go
  vet.sh
  xds/internal/client/bootstrap/bootstrap_test.go
Labels: Type: Dependencies

#3776 Re-add Go1.11 support
  .travis.yml
  credentials/go12.go
  credentials/tls.go
Labels: Type: Dependencies, no release notes
