Repository grpc/grpc-go, pull requests merged in 2021-02, with the labels that each got.

#4182 examples: delete profiling example since profiling support was rolled back
  examples/features/profiling/README.md
  examples/features/profiling/client/main.go
  examples/features/profiling/server/main.go
Labels: Type: Documentation, no release notes

#4188 xds: rename internal/client files to remove client prefix
  xds/internal/client/callback.go
  xds/internal/client/cds_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/loadreport.go
  xds/internal/client/loadreport_test.go
  xds/internal/client/logging.go
  xds/internal/client/rds_test.go
  xds/internal/client/requests_counter.go
  xds/internal/client/requests_counter_test.go
  xds/internal/client/singleton.go
  xds/internal/client/v2/ack_test.go
  xds/internal/client/v2/cds_test.go
  xds/internal/client/v2/eds_test.go
  xds/internal/client/v2/lds_test.go
  xds/internal/client/v2/rds_test.go
  xds/internal/client/watchers.go
  xds/internal/client/watchers_cluster_test.go
  xds/internal/client/watchers_endpoints_test.go
  xds/internal/client/watchers_listener_test.go
  xds/internal/client/watchers_route_test.go
  xds/internal/client/xds.go
Labels: Type: Internal Cleanup, no release notes

#4191 xds testing: increase timeout from 90 minutes to 120 minutes
  test/kokoro/xds.cfg
  test/kokoro/xds_v3.cfg
Labels: no release notes

#4184 balancergroup: Propagate balancer.BuildOptions to child policies
  xds/internal/balancer/balancergroup/balancergroup.go
  xds/internal/balancer/balancergroup/balancergroup_test.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
  xds/internal/client/v3/client.go
  xds/internal/testutils/balancer.go
Labels: Type: Bug, no release notes

#4194 xds testing: increase timeout from 90 minutes to 120 minutes
  test/kokoro/xds.cfg
Labels: no release notes

#4195 xds testing: increase timeout from 90 minutes to 120 minutes
  test/kokoro/xds.cfg
Labels: no release notes

#4193 xds testing: increase timeout from 90 minutes to 120 minutes
  test/kokoro/xds.cfg
Labels: no release notes

#4196 status: document nil error handling of FromError
  status/status.go
Labels: Type: Documentation

#4200 Change version to 1.37.0-dev
  version.go
Labels: no release notes

#4070 priority: the implementation
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/priority/logging.go
  xds/internal/balancer/priority/utils.go
  xds/internal/balancer/priority/utils_test.go
  xds/internal/testutils/balancer.go
Labels: Type: Feature

#4202 priority: pass build options to balancergroup
  xds/internal/balancer/priority/balancer.go
Labels: Type: Bug, no release notes

#4154 xds: xds_cluster_impl_balancer part 1
  vet.sh
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/config.go
  xds/internal/balancer/clusterimpl/config_test.go
  xds/internal/balancer/clusterimpl/logging.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/loadstore/load_store_wrapper.go
  xds/internal/balancer/lrs/balancer.go
Labels: Type: Feature

#4201 test: add timeout to regular xds test runs
  test/kokoro/xds.sh
Labels: Type: Testing, no release notes

#4203 circuit breaking: keep max_count per picker, instead of globally, and add support in cluster_impl balancer
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/edsbalancer/config.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/client/requests_counter.go
  xds/internal/client/requests_counter_test.go
Labels: Type: Behavior Change

#4212 circuit breaking: update picker inline when there's a counter update
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
Labels: Type: Bug

#4220 vet: allow golint to run on generated protos
  vet.sh
Labels: Type: Testing, no release notes

#4218 encoding/proto: do not panic when types do not match
  encoding/proto/proto.go
Labels: Cherry Pick, Type: Bug

#4223 encoding/proto: do not panic when types do not match (#4218)
  encoding/proto/proto.go
Labels: no release notes

#4198 Change version to 1.36.0
  version.go
Labels: no release notes

#4199 Change version to 1.36.1-dev
  version.go
Labels: no release notes

#4217 csds: update client resource cache to keep and dump metadata
  xds/internal/client/callback.go
  xds/internal/client/cds_test.go
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/client/dump.go
  xds/internal/client/dump_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/v2/ack_test.go
  xds/internal/client/v2/cds_test.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/client_test.go
  xds/internal/client/v2/eds_test.go
  xds/internal/client/v2/lds_test.go
  xds/internal/client/v2/rds_test.go
  xds/internal/client/v3/client.go
  xds/internal/client/watchers.go
  xds/internal/client/watchers_cluster_test.go
  xds/internal/client/watchers_endpoints_test.go
  xds/internal/client/watchers_listener_test.go
  xds/internal/client/watchers_route_test.go
  xds/internal/client/xds.go
Labels: Type: Feature

#4206 xds: add support for HTTP filters (gRFC A39)
  internal/resolver/config_selector.go
  internal/transport/http2_client.go
  internal/transport/transport.go
  stream.go
  xds/internal/client/client.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/v2/rds_test.go
  xds/internal/client/watchers_route_test.go
  xds/internal/client/xds.go
  xds/internal/env/env.go
  xds/internal/httpfilter/httpfilter.go
  xds/internal/httpfilter/router/router.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#4215 balancer: Add UpdateAddresses() to balancer.ClientConn interface
  balancer/balancer.go
  balancer/base/balancer.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer_conn_wrappers.go
  pickfirst.go
  xds/internal/testutils/balancer.go
Labels: Type: API Change

#4227 xds/cdsbalancer: Override UpdateAddresses()
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/testutils/balancer.go
Labels: Type: Feature
