Repository grpc/grpc-go, pull requests merged in 2021-08, with the labels that each got.

#4634 advancedtls: fix a typo in crl.go
  security/advancedtls/crl.go
Labels: Type: Internal Cleanup, no release notes

#4633 server: fix leaked net.Conn
  server.go
Labels: Cherry Pick, Type: Bug

#4636 github: update stale bot to v4
  .github/workflows/stale.yml
Labels: Type: Meta

#4627 transport: fix race accessing s.recvCompress
  internal/transport/http2_client.go
Labels: Type: Bug

#4641 transport: fix race accessing s.recvCompress
  internal/transport/http2_client.go
Labels: Cherry Pick, Type: Bug

#4642 server: fix leaked net.Conn
  server.go
Labels: Type: Bug

#4644 server: fix leaked net.Conn
  server.go
Labels: Type: Bug

#4651 Change version to 1.39.1
  version.go
Labels: Type: Meta

#4653 Change version to 1.39.2-dev
  version.go
Labels: Type: Meta

#4610 xds: Add route to filterchain
  xds/internal/server/listener_wrapper_test.go
  xds/internal/testutils/e2e/clientresources.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/v2/rds_test.go
  xds/internal/xdsclient/xds.go
  xds/server_test.go
Labels: Type: Feature

#4621 xds/cluster_resolver: support RING_HASH as a child of cluster_resolver balancer
  internal/serviceconfig/serviceconfig.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/ringhash/config.go
  xds/internal/balancer/ringhash/config_test.go
Labels: Type: Feature

#4658 xds: fix flaky test (TestPickerUpdateAfterClose)
  xds/internal/balancer/clusterimpl/balancer_test.go
Labels: Type: Testing, no release notes

#4649 Added connection to transport context
  internal/transport/http2_server.go
  internal/xds/rbac/rbac_engine.go
  internal/xds/rbac/rbac_engine_test.go
  test/end2end_test.go
Labels: Type: Feature

#4613 clientconn: do not automatically reconnect addrConns; go idle instead
  balancer/balancer.go
  balancer_conn_wrappers.go
  clientconn.go
  clientconn_state_transition_test.go
  clientconn_test.go
  pickfirst.go
  test/channelz_test.go
  test/creds_test.go
  test/end2end_test.go
Labels: Type: Behavior Change

#4661 Update xDS client/server image per-branch tag after build
  test/kokoro/xds_k8s.sh
Labels: Type: Testing

#4609 all: preallocate slices where possible
  authz/rbac_translator.go
  balancer/rls/internal/keys/builder.go
  balancer/roundrobin/roundrobin.go
  channelz/service/service.go
  cmd/protoc-gen-go-grpc/grpc.go
  internal/channelz/funcs.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/xds/rbac/rbac_engine.go
  interop/xds/client/client.go
  xds/csds/csds.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/resolver/matcher.go
  xds/internal/testutils/protos.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/transport_helper.go
  xds/internal/xdsclient/v2/loadreport.go
  xds/internal/xdsclient/v3/loadreport.go
  xds/internal/xdsclient/xds.go
Labels: Type: Internal Cleanup, no release notes

#4667 Copy the tag_and_push_docker_image method to grpc-go
  test/kokoro/xds_k8s_install_test_driver.sh
Labels: Type: Testing

#4655 xds: Add support for Dynamic RDS in listener wrapper
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler.go
  xds/internal/server/rds_handler_test.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/xdsclient/client.go
  xds/server.go
  xds/server_test.go
Labels: Type: Feature

#4657 xds: support picking ringhash in xds client and cds policy
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4663 server: fix net.conn closed twice
  server.go
Labels: Type: Bug

#4673 balancer: add ExitIdle optional interface
  balancer/balancer.go
  balancer/base/balancer.go
  balancer/grpclb/grpclb.go
  balancer/rls/internal/balancer.go
  balancer_conn_wrappers.go
  balancer_switching_test.go
  clientconn.go
  internal/balancer/stub/stub.go
  pickfirst.go
  test/balancer_test.go
  xds/internal/balancer/balancergroup/balancergroup.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
Labels: Type: API Change

#4692 Move Server Credentials Handshake to transport
  internal/transport/http2_server.go
  internal/transport/transport.go
  server.go
Labels: Type: Internal Cleanup

#4687 test: use non blocking dials in end2end_test
  test/balancer_test.go
  test/creds_test.go
  test/end2end_test.go
  test/insecure_creds_test.go
Labels: Type: Testing

#4689 xds: deflake Test/ServerSideXDS_ServingModeChanges
  xds/internal/test/xds_server_serving_mode_test.go
Labels: Type: Testing, no release notes

#4684 xds: use the defaultTestTimeout instead of the short one in TestV2ClientBackoffAfterRecvError
  xds/internal/xdsclient/v2/client_test.go
Labels: Type: Testing

#4685 multiple: remove appengine specific build constraints and code
  Makefile
  channelz/service/func_nonlinux.go
  install_gae.sh
  internal/channelz/types_linux.go
  internal/channelz/types_nonlinux.go
  internal/channelz/util_linux.go
  internal/channelz/util_nonlinux.go
  internal/channelz/util_test.go
  internal/credentials/spiffe.go
  internal/credentials/spiffe_appengine.go
  internal/credentials/syscallconn.go
  internal/credentials/syscallconn_appengine.go
  internal/credentials/syscallconn_test.go
  internal/profiling/buffer/buffer.go
  internal/profiling/buffer/buffer_appengine.go
  internal/profiling/buffer/buffer_test.go
  internal/syscall/syscall_linux.go
  internal/syscall/syscall_nonlinux.go
  interop/grpclb_fallback/client_linux.go
  security/advancedtls/sni.go
  security/advancedtls/sni_appengine.go
  security/advancedtls/sni_beforego114.go
  test/go_vet/vet.go
  vet.sh
Labels: Type: Internal Cleanup

#4699 grpc: fix stayConnected function to connect upon entry
  clientconn_test.go
Labels: Type: Testing

#4700 Remove support for Go 1.13 and older
  .github/workflows/testing.yml
  examples/go.mod
  go.mod
  internal/resolver/dns/go113.go
  security/advancedtls/sni_beforego114.go
  security/authorization/go.mod
  test/channelz_linux_test.go
  test/tools/go.mod
Labels: Type: Internal Cleanup

#4676 xds: Required Router Filter for both Client and Server side
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/httpfilter.go
  xds/internal/httpfilter/router/router.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/testutils/e2e/clientresources.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/xds.go
  xds/server_test.go
Labels: Type: Behavior Change

#4669 xds: Instantiated HTTP Filters on Server Side
  internal/resolver/config_selector.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/matcher.go
  xds/internal/xdsclient/matcher_path.go
  xds/internal/xdsclient/matcher_path_test.go
  xds/internal/xdsclient/matcher_test.go
Labels: Type: Feature

#4723 Change to a non-workload-identity GKE cluster
  test/kokoro/xds_url_map.sh
Labels: Type: Testing
