Repository grpc/grpc-go, pull requests merged in 2021-03, with the labels that each got.

#4230 xds: add support for more resources to e2e server
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/e2e/clientresources.go
  xds/internal/testutils/e2e/server.go
Labels: Type: Testing, no release notes

#4221 xds: add HTTP filter is_optional support (gRFC A39)
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/xds.go
Labels: Type: Feature, no release notes

#4238 xds: Move tests requiring API client to `tests` directory
  xds/internal/client/client_test.go
  xds/internal/client/tests/README.md
  xds/internal/client/tests/dump_test.go
  xds/internal/client/tests/loadreport_test.go
Labels: Type: Internal Cleanup, no release notes

#4226 csds: update xds_client to populate update metadata
  xds/internal/client/cds_test.go
  xds/internal/client/client_test.go
  xds/internal/client/eds_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/v2/cds_test.go
  xds/internal/client/v2/client.go
  xds/internal/client/v2/client_test.go
  xds/internal/client/v2/eds_test.go
  xds/internal/client/v2/lds_test.go
  xds/internal/client/v2/rds_test.go
  xds/internal/client/v3/client.go
  xds/internal/client/xds.go
Labels: Type: Feature

#4235 client: implement proper config selector interceptors
  internal/resolver/config_selector.go
  stream.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature, no release notes

#4241 Added check for POST method in http2_server
  internal/transport/http2_server.go
  internal/transport/http_util.go
  internal/transport/transport_test.go
Labels: Type: Bug

#4247 xds: add env var protection for client-side security
  xds/internal/client/cds_test.go
  xds/internal/client/xds.go
  xds/internal/env/env.go
Labels: Type: Internal Cleanup

#4249 cleanup: fix typo in Interceptor README
  examples/features/interceptor/README.md
Labels: Type: Internal Cleanup, no release notes

#4254 vet: set PATH to HOME/go/bin, and print go version
  .github/workflows/testing.yml
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#4233 xds: Support server_listener_resource_name_template
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/client/client.go
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/e2e/bootstrap.go
  xds/server.go
  xds/server_test.go
Labels: Type: Feature

#4222 xds: Prepare to support filter chains on the server
  credentials/xds/xds.go
  credentials/xds/xds_client_test.go
  credentials/xds/xds_server_test.go
  internal/credentials/xds/handshake_info.go
  xds/internal/client/client.go
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/server.go
  xds/server_test.go
Labels: Type: Feature

#4257 rls: update pb.gos
  balancer/rls/internal/proto/grpc_lookup_v1/rls.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_config.pb.go
Labels: Type: Internal Cleanup, no release notes

#4229 cherry-pick commits to 1.34.x
  encoding/proto/proto.go
  vet.sh
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_xds.go
  xds/internal/env/env.go
Labels: no release notes

#4228 cherry-pick commits to 1.35.x
  encoding/proto/proto.go
  vet.sh
  xds/internal/client/client_cds_test.go
  xds/internal/client/client_xds.go
  xds/internal/env/env.go
Labels: no release notes

#4204 c2p: add google-c2p resolver
  credentials/alts/alts.go
  credentials/alts/utils.go
  credentials/alts/utils_test.go
  internal/googlecloud/googlecloud.go
  internal/googlecloud/googlecloud_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/googledirectpath/utils.go
  xds/internal/client/singleton.go
  xds/internal/env/env.go
Labels: Type: Feature, no release notes

#4236 xds: implement fault injection HTTP filter (A33)
  examples/go.sum
  stream.go
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/xds.go
Labels: Type: Feature

#4258 xds: validate 'listener_filters' and 'use_original_dst' fields
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
Labels: Type: Feature, no release notes

#4259 Change version to 1.34.2
  version.go
Labels: no release notes

#4260 Change version to 1.35.1
  version.go
Labels: no release notes

#4264 xds: disable fault injection test on 386
  xds/internal/httpfilter/fault/fault_test.go
Labels: Type: Testing, no release notes

#4263 Change version to 1.35.2-dev
  version.go
Labels: no release notes

#4262 Change version to 1.34.3-dev
  version.go
Labels: no release notes

#4246 xds: support all matchers for SANs
  credentials/xds/xds_client_test.go
  internal/credentials/xds/handshake_info.go
  internal/credentials/xds/handshake_info_test.go
  internal/xds/string_matcher.go
  internal/xds/string_matcher_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/client/cds_test.go
  xds/internal/client/client.go
  xds/internal/client/xds.go
Labels: Type: Feature

#4243 csds: implement CSDS service handler
  xds/csds/csds.go
  xds/csds/csds_test.go
  xds/internal/testutils/e2e/server.go
Labels: Type: Feature

#4273 xds/cdsbalancer: move xds client close to run()
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
Labels: Type: Bug, no release notes

#4279 internal: use strings.Replace instead strings.ReplaceAll
  xds/server.go
  xds/server_test.go
Labels: Type: Internal Cleanup, no release notes

#4283 test: enable fault_injection xds test
  test/kokoro/xds.sh
Labels: Type: Testing, no release notes

#4274 admin: implement admin services
  admin/admin.go
  admin/admin_test.go
  admin/test/admin_test.go
  admin/test/utils.go
  channelz/service/service.go
  internal/admin/admin.go
  internal/xds/bootstrap.go
  internal/xds/env/env.go
  xds/csds/csds_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/client/cds_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/rds_test.go
  xds/internal/client/xds.go
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/e2e/bootstrap.go
  xds/xds.go
Labels: Type: Feature

#4284 alts: re-add vmOnGCP and once globals for easier testing
  credentials/alts/alts.go
Labels: Type: Internal Cleanup, no release notes

#4285 xds: use different proto import for grpc services
  admin/test/utils.go
  xds/csds/csds.go
Labels: Type: Internal Cleanup, no release notes

#4287 xds: rename proto import to grpc
  xds/xds.go
Labels: Type: Internal Cleanup, no release notes

#4286 xds: enable timeout, circuit breaking, and fault injection by default
  internal/xds/env/env.go
  xds/csds/csds_test.go
Labels: Type: Feature

#4253 balancer/base: keep address attributes for pickers
  balancer/base/balancer.go
  balancer/base/balancer_test.go
Labels: Type: Behavior Change

#4296 cherry-pick commits to 1.36.x
  xds/internal/client/cds_test.go
  xds/internal/client/xds.go
  xds/internal/env/env.go
Labels: no release notes

#4297 Change version to 1.36.1
  version.go
Labels: no release notes

#4300 change version to 1.36.2-dev
  version.go
Labels: no release notes

#4291 Allow using interop client for making Traffic Director RPCs
  interop/client/client.go
Labels: Type: Testing, no release notes

#4290 interop: add a flag to clients to statically configure grpclb
  interop/client/client.go
Labels: Type: Testing, no release notes

#4306 Change version to 1.38.0-dev
  version.go
Labels: no release notes

#4299 xds/resolver: support inline RDS resource from LDS response
  xds/internal/client/client.go
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/watch_service_test.go
Labels: Type: Feature

#4281 xds: filter chain matching logic for server-side
  xds/internal/client/client.go
  xds/internal/client/filter_chain.go
  xds/internal/client/filter_chain_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/server_test.go
Labels: Type: Feature
