Repository grpc/grpc-go, pull requests merged in 2021-06, with the labels that each got.

#4477 client: Clarify that WaitForReady will block for CONNECTING channels
  rpc_util.go
Labels: Type: Documentation

#4476 xds: add test-only injection of xds config to client and server
  internal/xds/bootstrap.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/client/attributes.go
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/singleton.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/server.go
  xds/server_options.go
  xds/xds.go
Labels: Type: Feature

#4429 cluster_resolver: add functions to build child balancer config
  xds/internal/balancer/clusterresolver/balancerconfig/configbuilder.go
  xds/internal/balancer/clusterresolver/balancerconfig/configbuilder_test.go
  xds/internal/balancer/clusterresolver/balancerconfig/type.go
  xds/internal/balancer/edsbalancer/configbuilder.go
  xds/internal/balancer/edsbalancer/configbuilder_test.go
Labels: Type: Internal Cleanup, no release notes

#4458 internal/transport: skip log on EOF when reading client preface
  call_test.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  server.go
Labels: Type: Internal Cleanup, no release notes

#4504 client: handle RemoveSubConn in goroutine to avoid deadlock
  balancer_conn_wrappers.go
  balancer_switching_test.go
Labels: Type: Bug

#4505 csds: return empty response if xds client is not set
  xds/csds/csds.go
  xds/csds/csds_test.go
Labels: Type: Behavior Change

#4508 doc: fix typo in package networktype
  internal/transport/networktype/networktype.go
Labels: Type: Internal Cleanup

#4416 metadata: convert keys to lowercase in FromContext()
  metadata/metadata.go
Labels: Type: Behavior Change

#4512 cleanup: remove "Interface" as suffix of (almost all) interface names
  internal/xds/matcher/matcher_header.go
  internal/xds/matcher/matcher_header_test.go
  internal/xds/rbac/matchers.go
  xds/csds/csds.go
  xds/csds/csds_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/resolver/matcher.go
  xds/internal/resolver/matcher_path.go
  xds/internal/resolver/matcher_test.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/server.go
  xds/server_test.go
Labels: Type: Internal Cleanup, no release notes

#4517 xds: standardize builder type names (bb) and balancer receiver names (b)
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/xds_old.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
Labels: Type: Internal Cleanup, no release notes

#4518 xds: standardize xds client field name (xdsClient)
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/lrs/balancer.go
Labels: Type: Internal Cleanup, no release notes

#4509 xds/resolver: test xds client closed by resolver Close
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/fakeclient/client.go
Labels: Type: Testing, no release notes

#4519 c2p: add random number to xDS node ID in google-c2p resolver
  internal/grpcrand/grpcrand.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Feature, no release notes

#4510 xds: export XDSClient interface and use it in balancer tests
  xds/csds/csds.go
  xds/csds/csds_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/xdsclient/attributes.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/singleton.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/server.go
  xds/server_test.go
Labels: Type: Internal Cleanup

#4530 vet: remove support for non-module-aware Go versions
  vet.sh
Labels: Type: Internal Cleanup, no release notes

#4507 Add GetServiceInfo to xds.GRPCServer
  xds/server.go
  xds/server_test.go
Labels: Type: API Change

#4529 xds: remove env var protetion of advanced routing features
  internal/xds/env/env.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Internal Cleanup, no release notes

#4534 grpc: prevent deadlock in Test/ClientUpdatesParamsAfterGoAway on failure
  clientconn_test.go
Labels: Type: Testing, no release notes

#4536 internal: fix deadlock during switch_balancer and NewSubConn()
  clientconn.go
  resolver_conn_wrapper.go
Labels: Type: Bug, no release notes

#4543 Change version to 1.40.0-dev
  version.go
Labels: Type: Meta

#4539 xds/cds: update CDS balancer to partially handle aggregated cluster
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
Labels: Type: Feature

#4457 xds/eds: rewrite EDS policy using child policies
  xds/internal/balancer/balancer.go
  xds/internal/balancer/balancergroup/balancergroup.go
  xds/internal/balancer/edsbalancer/configbuilder_test.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_priority.go
  xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/eds_testutil_test.go
  xds/internal/balancer/edsbalancer/eds_watcher.go
  xds/internal/balancer/edsbalancer/util.go
  xds/internal/balancer/edsbalancer/util_test.go
  xds/internal/balancer/edsbalancer/xds_lrs_test.go
  xds/internal/balancer/edsbalancer/xds_old.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/xdsclient/requests_counter.go
Labels: Type: Internal Cleanup

#4545 xds: move eds package to cluster_resolver
  xds/internal/balancer/balancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/eds_watcher.go
  xds/internal/balancer/clusterresolver/logging.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/testutil_test.go
Labels: Type: Internal Cleanup

#4549 metadata: add Delete method to MD
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Feature

#4525 xds: generate per-request hash config selector
  examples/go.sum
  go.mod
  go.sum
  internal/grpcrand/grpcrand.go
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  xds/internal/balancer/ringhash/util.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4553 xds: require router filter when filters are empty
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Cherry Pick, Type: Bug

#4551 xds/clusterimpl: fix race between picker update and ClientConn state update
  xds/internal/balancer/clusterimpl/clusterimpl.go
Labels: Type: Bug

#4555 xds: fix test race in cluster_resolver
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
Labels: Type: Internal Cleanup

#4556 Revert "xds: require router filter when filters are empty"
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Bug, no release notes

#4533 stats: add stream info inside stats.Begin
  server.go
  stats/stats.go
  stats/stats_test.go
  stream.go
Labels: Type: Feature

#4548 buildscripts: add option to use xds-k8s test driver from a fork
  test/kokoro/xds_k8s_install_test_driver.sh
Labels: Type: Testing, no release notes

#4560 xds/circuit_breaking: counters should be keyed by {cluster, EDS service name} pair
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/xdsclient/requests_counter.go
  xds/internal/xdsclient/requests_counter_test.go
Labels: Type: Bug

#4532 cluster_resolver: fix DiscoveryMechanismType marshal JSON
  xds/internal/balancer/clusterresolver/balancerconfig/type.go
  xds/internal/balancer/clusterresolver/balancerconfig/type_test.go
Labels: Type: Internal Cleanup

#4559 client: add deadline for TransportCredentials handshaker
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Bug, fixit

#4535 xdsclient: move tests out of tests directory
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/README.md
  xds/internal/xdsclient/xdsclient_test.go
Labels: Type: Internal Cleanup, no release notes

#4528 xds: delete LRS policy and move the functionality to xds_cluster_impl
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/clusterresolver/balancerconfig/configbuilder.go
  xds/internal/balancer/clusterresolver/balancerconfig/configbuilder_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/balancer/lrs/config.go
  xds/internal/balancer/lrs/config_test.go
  xds/internal/balancer/lrs/logging.go
  xds/internal/balancer/lrs/picker.go
  xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
  xds/internal/internal.go
Labels: Type: Internal Cleanup

#4524 server: improve chained interceptors performance
  server.go
  server_test.go
Labels: Type: Performance

#4561 internal/transport: do not mask ConnectionError
  internal/transport/http2_client.go
Labels: Cherry Pick, Type: Bug

#4569 internal/transport: do not mask ConnectionError (#4561)
  internal/transport/http2_client.go
Labels: Type: Bug

#4541 Change version to 1.39.0
  version.go
Labels: Type: Behavior Change

#4566 xds/cluster_impl: fix cluster_impl not correctly starting LoadReport stream
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/testutils/fakeclient/client.go
Labels: Type: Bug

#4572 Cherry pick #4561 to v1.38.x branch
  internal/transport/http2_client.go
Labels: Cherry Pick

#4523 authorization: translate SDK policy to Envoy RBAC proto
  authz/rbac_translator.go
  authz/rbac_translator_test.go
Labels: Type: Feature, no release notes
