Repository grpc/grpc-go, pull requests merged in 2021-12, with the labels that each got.

#5017 fix possible nil before casting
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: Testing

#5031 xds/bootstrap_config: add a string function to server config
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
Labels: Type: Feature

#4995 rls: support extra_keys and constant_keys
  balancer/rls/internal/keys/builder.go
  balancer/rls/internal/keys/builder_test.go
  balancer/rls/internal/picker.go
Labels: Type: Feature

#4987 xds/resolver: Add support for cluster specifier plugins
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#5041 Change version to 1.44.0-dev
  version.go
Labels: Type: Meta

#5012 internal/balancergroup: eliminate race in exitIdle
  internal/balancergroup/balancergroup.go
Labels: Type: Bug

#5038 grpclog.DepthLoggerV2: Correct comment: formats like fmt.Println
  grpclog/loggerv2.go
  internal/grpclog/grpclog.go
Labels: Type: Documentation

#5047 Backport "xds/c2p: replace C2P resolver env var with experimental scheme suffix #5044" to 1.43.x
  internal/envconfig/xds.go
  xds/googledirectpath/googlec2p.go
Labels: Type: Feature, Cherry Pick

#5032 xds/client: send NewStream errors to the watchers
  xds/internal/xdsclient/controller/transport.go
Labels: Type: Bug

#5033 transport: better error message when per-RPC creds fail
  internal/transport/http2_client.go
Labels: Type: Bug

#5037 xds/client: move xdsclient.New tests to controller.New
  xds/internal/xdsclient/controller/controller_test.go
  xds/internal/xdsclient/xdsclient_test.go
Labels: Type: Internal Cleanup

#4991 xds/federation: resource name parsing
  xds/internal/xdsclient/xdsresource/name.go
  xds/internal/xdsclient/xdsresource/name_test.go
Labels: Type: Feature

#5005 test: cleanup roundrobin_test
  balancer/roundrobin/roundrobin_test.go
Labels: Type: Internal Cleanup

#5050 xds: Added env var for RLS in xDS
  internal/envconfig/xds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Feature

#5035 authz: fix regex expression match
  authz/rbac_translator.go
  authz/rbac_translator_test.go
  authz/sdk_end2end_test.go
  internal/grpcutil/regex.go
  internal/grpcutil/regex_test.go
Labels: Type: Bug

#5053 cmd/protoc-gen-go-grpc: update google.golang.org/protobuf to v1.27.1
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  regenerate.sh
Labels: Type: Dependencies

#5054 xds/client: send connection errors to all watchers
  xds/internal/xdsclient/pubsub/update.go
Labels: Type: Bug, Cherry Pick

#5039 Change version to 1.43.0
  version.go
Labels: Type: Meta

#5024 testing: fix goroutine leak in TestClientUpdatesParamsAfterGoAway
  clientconn_test.go
Labels: Status: Requires Reporter Clarification, Type: Testing

#5040 Change version to 1.43.1-dev
  version.go
Labels: Type: Meta

#5046 rls: control channel implementation
  balancer/rls/internal/balancer.go
  balancer/rls/internal/balancer_test.go
  balancer/rls/internal/builder.go
  balancer/rls/internal/client.go
  balancer/rls/internal/client_test.go
  balancer/rls/internal/config_test.go
  balancer/rls/internal/control_channel.go
  balancer/rls/internal/control_channel_test.go
  balancer/rls/internal/helpers_test.go
  balancer/rls/internal/picker.go
  balancer/rls/internal/picker_test.go
  balancer/rls/internal/test/e2e/e2e.go
  balancer/rls/internal/test/e2e/rls_child_policy.go
  balancer/rls/internal/test/e2e/rls_fakeserver.go
  balancer/rls/internal/test/e2e/rls_lb_config.go
  internal/stubserver/stubserver.go
  internal/testutils/restartable_listener.go
Labels: Type: Feature

#5004 xds: Add RLS Cluster Specifier Plugin
  balancer/rls/rls.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/clusterspecifier/rls/rls_test.go
Labels: Type: Feature

#5062 xds: Add xds dependency to the fallback test client
  interop/grpclb_fallback/client_linux.go
Labels: Type: Testing

#5066 xds: Remove WithBlock option from the fallback test client
  interop/grpclb_fallback/client_linux.go
Labels: Type: Testing

#5061 rls: minor config processing changes
  balancer/rls/internal/builder.go
  balancer/rls/internal/config.go
  balancer/rls/internal/config_test.go
Labels: Type: Feature

#5058 internal/resolver: fix possible goroutine leak in TestSafeConfigSelector
  internal/resolver/config_selector_test.go
Labels: Type: Testing

#5068 grpc: minor improvement on WithInsecure() document
  dialoptions.go
Labels: Type: Documentation

#5022 grpclb: fix possible nil before conversion in TestDropRequest
  balancer/grpclb/grpclb_test.go
Labels: Type: Testing

#5060 rls: move the data cache implementation into the rls package
  balancer/rls/internal/cache.go
  balancer/rls/internal/cache/cache.go
  balancer/rls/internal/cache/cache_test.go
  balancer/rls/internal/cache_test.go
  balancer/rls/internal/child_policy.go
Labels: Type: Feature

#5069 insecure: remove experimental notice
  credentials/insecure/insecure.go
Labels: Type: Feature

#5071 test/kokoro: Use xds-test-server-5 as the GCE interop server
  test/kokoro/xds.sh
Labels: Type: Testing

#5073 dialoptions.go: Fix WithBlock godoc
  dialoptions.go
Labels: Type: Documentation

#5074 testdata: use SHA256 as signing algorithm in testdata certs
  testdata/x509/client1_cert.pem
  testdata/x509/client1_key.pem
  testdata/x509/client2_cert.pem
  testdata/x509/client2_key.pem
  testdata/x509/client_ca_cert.pem
  testdata/x509/client_ca_key.pem
  testdata/x509/multiple_uri_cert.pem
  testdata/x509/multiple_uri_key.pem
  testdata/x509/server1_cert.pem
  testdata/x509/server1_key.pem
  testdata/x509/server2_cert.pem
  testdata/x509/server2_key.pem
  testdata/x509/server_ca_cert.pem
  testdata/x509/server_ca_key.pem
  testdata/x509/spiffe_cert.pem
  testdata/x509/spiffe_key.pem
Labels: Type: Testing

#5052 authz: update representation of allow authenticated in SDK
  authz/rbac_translator.go
  authz/rbac_translator_test.go
  authz/sdk_end2end_test.go
Labels: Type: Internal Cleanup

#5097 test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.43.x)
  test/kokoro/xds.sh
Labels: Type: Testing
