Repository grpc/grpc-go, pull requests merged in 2021-01, with the labels that each got.

#4120 xds: NACK more invalid RDS responses
  xds/internal/client/client_rds_test.go
  xds/internal/client/client_xds.go
Labels: Type: Bug

#4137 xds client: Updated v3 type for http connection manager
  xds/internal/client/client_lds_test.go
  xds/internal/version/version.go
Labels: Cherry Pick, Type: Bug

#4134 github: enable CodeQL checker
  .github/workflows/codeql-analysis.yml
Labels: Type: Testing, no release notes

#4129 interop: remove test.proto clones/variants and use grpc-proto repo instead
  benchmark/benchmain/main.go
  benchmark/benchmark.go
  benchmark/client/main.go
  benchmark/grpc_testing/control.pb.go
  benchmark/grpc_testing/control.proto
  benchmark/grpc_testing/messages.pb.go
  benchmark/grpc_testing/messages.proto
  benchmark/grpc_testing/payloads.proto
  benchmark/grpc_testing/services.pb.go
  benchmark/grpc_testing/services.proto
  benchmark/grpc_testing/stats.pb.go
  benchmark/grpc_testing/stats.proto
  benchmark/worker/benchmark_client.go
  benchmark/worker/benchmark_server.go
  benchmark/worker/main.go
  binarylog/binarylog_end2end_test.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test.proto
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/test_utils.go
  regenerate.sh
  stats/grpc_testing/test.pb.go
  stats/grpc_testing/test.proto
  stats/grpc_testing/test_grpc.pb.go
  stats/stats_test.go
Labels: Type: Internal Cleanup, no release notes

#4135 lrs: use JSON for locality's String representation
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/balancer/lrs/picker.go
  xds/internal/internal.go
  xds/internal/internal_test.go
Labels: Cherry Pick, Type: Bug

#4122 xds: add HTTP connection manager max_stream_duration support
  xds/internal/client/client.go
  xds/internal/client/client_lds_test.go
  xds/internal/client/client_rds_test.go
  xds/internal/client/client_xds.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Feature

#4143 xds/resolver: fix resource deletion
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Cherry Pick, Type: Bug

#4144 xds interop: turn on circuit breaking test
  test/kokoro/xds.sh
Labels: Type: Testing, no release notes

#4142 Change version to 1.36.0-dev
  version.go
Labels: no release notes

#4148 cleanup: use different import alias for services than messages
  benchmark/benchmain/main.go
  benchmark/benchmark.go
  benchmark/client/main.go
  benchmark/worker/benchmark_client.go
  benchmark/worker/main.go
  binarylog/binarylog_end2end_test.go
  interop/alts/client/client.go
  interop/alts/server/server.go
  interop/client/client.go
  interop/grpclb_fallback/client.go
  interop/http2/negative_http2_client.go
  interop/server/server.go
  interop/test_utils.go
  interop/xds/client/client.go
  interop/xds/server/server.go
  stats/stats_test.go
  stress/client/main.go
Labels: Type: Internal Cleanup, no release notes

#4149 interop/grpc_testing: update generated code after recent grpc-proto changes
  interop/grpc_testing/messages.pb.go
Labels: Type: Testing, no release notes

#4153 xds bootstrap: support config content in env variable
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/env/env.go
Labels: Type: Feature

#4156 interop/xds: implement new stats response field
  interop/xds/client/client.go
Labels: Type: Testing, no release notes

#4157 interop/xds: support ClientConfigureRequest.timeout_sec field
  interop/xds/client/client.go
Labels: Type: Testing, no release notes

#4160 test: Run e2e authority tests only on linux.
  test/authority_test.go
Labels: Type: Bug, no release notes

#4165 xds interop: add xds v3 kokoro tests
  test/kokoro/xds.sh
  test/kokoro/xds_v3.cfg
  test/kokoro/xds_v3.sh
Labels: Type: Testing, no release notes

#4164 pemfile: Make test happy with Go1.16
  credentials/tls/certprovider/pemfile/watcher_test.go
Labels: Type: Bug, no release notes

#4177 regenerate.sh: include standard protos; update generated files
  interop/grpc_testing/messages.pb.go
  regenerate.sh
Labels: Type: Internal Cleanup, no release notes

#4174 xds: Remove v3Support environment variable
  xds/internal/client/bootstrap/bootstrap.go
  xds/internal/client/bootstrap/bootstrap_test.go
  xds/internal/env/env.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Internal Cleanup, no release notes

#4171 xds: report drops by circuit breaking
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/client/client_requests_counter.go
  xds/internal/client/load/store.go
  xds/internal/client/load/store_test.go
  xds/internal/testutils/protos.go
Labels: no release notes
