Repository grpc/grpc-go, pull requests merged in 2021-11, with the labels that each got.

#4919 grpclb: move restartableListener to testutils
  balancer/grpclb/grpclb_test.go
  balancer/grpclb/grpclb_test_util_test.go
  internal/testutils/restartable_listener.go
Labels: Type: Testing

#4858 examples: remove usage of WithBlock in examples
  examples/examples_test.sh
  examples/features/authentication/client/main.go
  examples/features/compression/client/main.go
  examples/features/deadline/client/main.go
  examples/features/debugging/client/main.go
  examples/features/encryption/ALTS/client/main.go
  examples/features/encryption/TLS/client/main.go
  examples/features/errors/client/main.go
  examples/features/interceptor/client/main.go
  examples/features/load_balancing/client/main.go
  examples/features/metadata/client/main.go
  examples/features/multiplex/client/main.go
  examples/features/name_resolving/client/main.go
  examples/features/unix_abstract/client/main.go
  examples/features/unix_abstract/server/main.go
  examples/helloworld/greeter_client/main.go
  examples/helloworld/greeter_server/main.go
  examples/route_guide/client/client.go
Labels: Type: Documentation

#4920 xds: move LocalTCPListener to internal/testutils
  internal/testutils/local_listener.go
  xds/csds/csds_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/server_test.go
Labels: Type: Testing

#4892 xds/bootstrap: refactor to support top level and per-authority server config
  xds/csds/csds.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/loadreport.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/xdsclient_test.go
  xds/server_test.go
Labels: Type: Feature

#4873 transport/http2_server : Move up streamID validation in operate headers
  internal/transport/http2_server.go
Labels: Type: Bug

#4925 xds: NACK missing route specifier server side
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
Labels: Type: Bug

#4915 grpc: stabilize WithConnectParams DialOption
  dialoptions.go
Labels: Type: Documentation

#4955 xds/balancergroup: remove xds dependency from balancergroup
  xds/internal/balancer/balancergroup/balancergroup.go
  xds/internal/balancer/balancergroup/balancergroup_test.go
  xds/internal/balancer/balancergroup/testutils_test.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
Labels: Type: Internal Cleanup

#4954 kokoro: Enable xds authz_test
  test/kokoro/xds_k8s.cfg
  test/kokoro/xds_k8s.sh
Labels: Type: Testing

#4959 kokoro: Enable xds authz_test (#4954) (v1.42.x backport)
  test/kokoro/xds_k8s.cfg
  test/kokoro/xds_k8s.sh
Labels: Type: Testing

#4962 internal: update pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
Labels: Type: Internal Cleanup

#4900 xds/federation: support populating resource template in xds-resolver
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/xdsclient/bootstrap/template.go
  xds/internal/xdsclient/bootstrap/template_test.go
  xds/server.go
Labels: Type: Feature

#4936 xds/federation: support new bootstrap fields and protect them by an env var
  internal/xds/env/env.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
Labels: Type: Feature

#4938 transport: pass handshake info with attributes to custom dialers
  internal/transport/http2_client.go
  internal/transport/transport_test.go
Labels: Type: Feature

#4963 xds/client: move watchers from xdsclient to a separate struct
  xds/csds/csds.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/xdsclient/attributes.go
  xds/internal/xdsclient/callback.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/dump.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/pubsub/dump.go
  xds/internal/xdsclient/pubsub/pubsub.go
  xds/internal/xdsclient/pubsub/update.go
  xds/internal/xdsclient/pubsub/watch.go
  xds/internal/xdsclient/transport_helper.go
  xds/internal/xdsclient/v2/ack_test.go
  xds/internal/xdsclient/v2/cds_test.go
  xds/internal/xdsclient/v2/client.go
  xds/internal/xdsclient/v2/client_test.go
  xds/internal/xdsclient/v2/eds_test.go
  xds/internal/xdsclient/v2/lds_test.go
  xds/internal/xdsclient/v2/rds_test.go
  xds/internal/xdsclient/v3/client.go
  xds/internal/xdsclient/watchers.go
  xds/internal/xdsclient/watchers_cluster_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_listener_test.go
  xds/internal/xdsclient/watchers_route_test.go
  xds/internal/xdsclient/xdsresource/errors.go
  xds/internal/xdsclient/xdsresource/type.go
  xds/server_test.go
Labels: Type: Internal Cleanup

#4956 lint: fix some unused parameter issues
  authz/rbac_translator.go
  balancer/rls/internal/adaptive/adaptive_test.go
  balancer/rls/internal/client.go
  balancer/rls/internal/client_test.go
  benchmark/benchmain/main.go
  benchmark/latency/latency_test.go
  binarylog/binarylog_end2end_test.go
  internal/channelz/funcs.go
  internal/profiling/buffer/buffer.go
  internal/serviceconfig/serviceconfig_test.go
  internal/transport/flowcontrol.go
  internal/transport/http2_client.go
  internal/transport/proxy.go
  internal/transport/proxy_test.go
  internal/transport/transport_test.go
  stats/stats_test.go
  test/balancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
  xds/internal/test/e2e/controlplane.go
  xds/internal/test/e2e/e2e.go
  xds/internal/test/e2e/e2e_test.go
Labels: Type: Internal Cleanup

#4966 xds: move balancergroup and weightedtarget our of xds directory
  balancer/weightedtarget/logging.go
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget.go
  balancer/weightedtarget/weightedtarget_config.go
  balancer/weightedtarget/weightedtarget_config_test.go
  balancer/weightedtarget/weightedtarget_test.go
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
  internal/balancergroup/balancerstateaggregator.go
  internal/testutils/balancer.go
  internal/testutils/wrr.go
  xds/internal/balancer/balancer.go
  xds/internal/balancer/balancergroup/balancergroup_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/config_test.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/clustermanager/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/testutil_test.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/priority/ignore_resolve_now_test.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ringhash_test.go
  xds/internal/balancer/weightedtarget/weightedtarget_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/balancer_test.go
  xds/internal/testutils/testutils.go
Labels: Type: Internal Cleanup

#4922 config: remove retry disable via environment variable
  dialoptions.go
  internal/envconfig/envconfig.go
  internal/xds/env/env.go
  test/retry_test.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Behavior Change

#4718 grpc: implement WithInsecure() using the insecure package
  clientconn.go
  clientconn_test.go
  credentials/credentials.go
  credentials/insecure/insecure.go
  dialoptions.go
  test/creds_test.go
  test/insecure_creds_test.go
Labels: Type: Internal Cleanup

#4967 xds: Add Cluster Specifier Plugin to xdsclient
  xds/internal/clusterspecifier/cluster_specifier.go
  xds/internal/xdsclient/xdsresource/type_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Feature

#4964 xds: Added validation and construction of RBAC matcher engine to ParseConfig
  internal/xds/rbac/rbac_engine.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Bug

#4968 xds/client: move transport_helper from xdsclient to a separate struct
  xds/csds/csds.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/testutils/fakeserver/server.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/controller.go
  xds/internal/xdsclient/controller/controller.go
  xds/internal/xdsclient/controller/loadreport.go
  xds/internal/xdsclient/controller/transport.go
  xds/internal/xdsclient/controller/v2_ack_test.go
  xds/internal/xdsclient/controller/v2_cds_test.go
  xds/internal/xdsclient/controller/v2_client_test.go
  xds/internal/xdsclient/controller/v2_eds_test.go
  xds/internal/xdsclient/controller/v2_lds_test.go
  xds/internal/xdsclient/controller/v2_rds_test.go
  xds/internal/xdsclient/controller/v2_testutils_test.go
  xds/internal/xdsclient/controller/version/v2/client.go
  xds/internal/xdsclient/controller/version/v2/loadreport.go
  xds/internal/xdsclient/controller/version/v3/client.go
  xds/internal/xdsclient/controller/version/v3/loadreport.go
  xds/internal/xdsclient/controller/version/version.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/loadreport.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/pubsub/interface.go
  xds/internal/xdsclient/watchers.go
  xds/internal/xdsclient/watchers_cluster_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_listener_test.go
  xds/internal/xdsclient/watchers_route_test.go
  xds/internal/xdsclient/xdsclient_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/type.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/internal/xdsclient/xdsresource/version/version.go
  xds/xds.go
Labels: Type: Internal Cleanup

#4971 pickfirst: check b.sc before calling Connect
  pickfirst.go
Labels: Type: Bug, Cherry Pick

#4923 internal: merge xds/envconfig into env package
  internal/envconfig/xds.go
  internal/xds/bootstrap.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/test/xds_client_affinity_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/server.go
Labels: Type: Internal Cleanup

#4918 rpc_util: Change error message to indicate size after decompression
  rpc_util.go
Labels: Type: Documentation, Status: Requires Reporter Clarification

#4969 balancer: add Authority field to balancer.BuildOptions
  balancer/balancer.go
  clientconn.go
  test/balancer_test.go
Labels: Type: Feature

#4972 xdsclient: add Cluster Specifier Name to Route
  xds/internal/xdsclient/controller/v2_rds_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/type_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/server.go
Labels: Type: Feature

#4973 internal: add log when service config is disabled
  clientconn.go
Labels: Type: Documentation

#4979 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4982 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.40.x) (#4979)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4978 xds/client: cleanup Dump to remove unnecessary version field
  xds/csds/csds.go
  xds/internal/xdsclient/attributes.go
  xds/internal/xdsclient/dump.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/pubsub/dump.go
  xds/internal/xdsclient/pubsub/pubsub.go
  xds/internal/xdsclient/pubsub/update.go
Labels: Type: Internal Cleanup

#4975 examples: Fix server port in route_guide example to work with client
  examples/route_guide/server/server.go
Labels: Type: Bug

#4983 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.41.x) (#4979)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4985 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.39.x) (#4979)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4986 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.38.x) (#4979)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4984 test/kokoro: rename xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.42.x) (#4979)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
Labels: Type: Testing

#4989 internal: move leakcheck to t.Cleanup
  internal/grpctest/grpctest.go
Labels: Type: Internal Cleanup

#4993 rls: move pb.gos to grpc/internal/proto/grpc_lookup_v1
  balancer/rls/internal/client.go
  balancer/rls/internal/client_test.go
  balancer/rls/internal/config.go
  balancer/rls/internal/keys/builder.go
  balancer/rls/internal/keys/builder_test.go
  balancer/rls/internal/picker_test.go
  balancer/rls/internal/testutils/fakeserver/fakeserver.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  regenerate.sh
Labels: Type: Internal Cleanup

#4977 status: support wrapped errors in FromContextError
  status/status.go
  status/status_test.go
Labels: Type: Behavior Change

#5003 rls: double import rls protos
  balancer/rls/internal/client.go
Labels: Type: Internal Cleanup

#4994 balancergroup: add method to exitIdle a sub-balancer
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
Labels: Type: Internal Cleanup

#5010 xds/c2p: fix default client resource template, and xds-client target scheme
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Bug

#5015 xds/kokoro: install go 1.17, and retry go build
  test/kokoro/xds.sh
Labels: Type: Testing
