Repository grpc/grpc-go, pull requests merged in 2021-07, with the labels that each got.

#4579 clientconn: stop automatically connecting to idle subchannels returned by picker
  clientconn.go
  picker_wrapper.go
Labels: Type: Behavior Change

#4583 binarylog: Don't leak the flusher goroutine when closing a Sink
  internal/binarylog/sink.go
Labels: Type: Bug

#4586 Fix bootstrap format in comment
  xds/internal/xdsclient/bootstrap/bootstrap.go
Labels: Type: Documentation

#4590 internal/binarylog: Use defer to unlock mutexes
  internal/binarylog/sink.go
Labels: Type: Internal Cleanup

#4582 binarylog: Don't continue after failing to marshal the proto
  internal/binarylog/sink.go
Labels: Type: Bug

#4531 cluster_resolver: implement resource resolver to resolve EDS and DNS
  resolver/manual/manual.go
  xds/internal/balancer/clusterresolver/balancerconfig/type.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/clusterresolver/resource_resolver_test.go
  xds/internal/testutils/fakeclient/client.go
Labels: Type: Feature

#4474 transport: validate http 200 status for responses
  internal/status/status.go
  internal/transport/http2_client.go
  internal/transport/http_util.go
  internal/transport/transport_test.go
  test/end2end_test.go
Labels: Status: Requires Reporter Clarification, Type: Bug

#4581 binarylog: Use a simple boolean rather than a sync.Once
  internal/binarylog/sink.go
Labels: Type: Performance

#4564 xds/client: notify the resource watchers of xDS errors
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/xdsclient/callback.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/v2/client.go
  xds/internal/xdsclient/v2/client_test.go
  xds/internal/xdsclient/v3/client.go
  xds/internal/xdsclient/watchers.go
  xds/internal/xdsclient/watchers_cluster_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_listener_test.go
  xds/internal/xdsclient/watchers_route_test.go
Labels: Type: Feature

#4587 client: improve GOAWAY debug messages
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#4489 advancedtls: CRL checking for golang gRPC
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/advancedtls/testdata/crl/0b35a562.r0
  security/advancedtls/testdata/crl/0b35a562.r1
  security/advancedtls/testdata/crl/1.crl
  security/advancedtls/testdata/crl/1ab871c8.r0
  security/advancedtls/testdata/crl/2.crl
  security/advancedtls/testdata/crl/3.crl
  security/advancedtls/testdata/crl/4.crl
  security/advancedtls/testdata/crl/5.crl
  security/advancedtls/testdata/crl/6.crl
  security/advancedtls/testdata/crl/71eac5a2.r0
  security/advancedtls/testdata/crl/7a1799af.r0
  security/advancedtls/testdata/crl/8828a7e6.r0
  security/advancedtls/testdata/crl/README.md
  security/advancedtls/testdata/crl/deee447d.r0
  security/advancedtls/testdata/crl/revokedInt.pem
  security/advancedtls/testdata/crl/revokedLeaf.pem
  security/advancedtls/testdata/crl/unrevoked.pem
Labels: Type: Security, no release notes

#4604 internal/binarylog: Fix data race when calling Write() and Close() in parallel
  internal/binarylog/sink.go
Labels: Type: Bug

#4594 xds: support cluster fallback in cluster_resolver
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/eds_watcher.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_test.go
  xds/internal/balancer/priority/config.go
Labels: Type: Feature

#4570 test: fix possible goroutine leaks in unit tests
  internal/resolver/config_selector_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/server/listener_wrapper_test.go
Labels: Type: Testing

#4605 grpclb: propagate the most recent connection error when grpclb enters transient failure
  balancer/grpclb/grpclb.go
  balancer/grpclb/grpclb_test.go
Labels: Type: Internal Cleanup

#4595 xds: add http filters to FilterChain matching
  xds/internal/server/listener_wrapper_test.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/xds.go
  xds/server_test.go
Labels: Type: Feature

#4576 Add extra layer on top of RBAC Engine
  internal/xds/rbac/matchers.go
  internal/xds/rbac/rbac_engine.go
  internal/xds/rbac/rbac_engine_test.go
Labels: Type: Feature

#4607 cluster_resolver: move balancer config types into cluster_resolver package and unexport
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/balancerconfig/type.go
  xds/internal/balancer/clusterresolver/balancerconfig/type_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_test.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
Labels: Type: Internal Cleanup

#4611 client: fix detection of whether IO was performed in NewStream
  internal/transport/http2_client.go
  internal/transport/transport_test.go
  rpc_util.go
  stream.go
Labels: Type: Bug

#4625 Change version to 1.41.0-dev
  version.go
Labels: Type: Meta

#4616 fix typo
  xds/internal/balancer/balancergroup/balancergroup_test.go
Labels: Type: Internal Cleanup

#4628 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Type: Meta, no release notes

#4631 xds: fix a typo
  internal/xds/env/env.go
Labels: Type: Internal Cleanup, no release notes
