Repository grpc/grpc-go, pull requests merged in 2021-09, with the labels that each got.

#4671 xds/internal/resolver: update github.com/cespare/xxhash to v2
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Dependencies, no release notes

#4720 xds: start a management server per test
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
Labels: Type: Testing

#4701 ringhash: the ring
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
Labels: Type: Feature

#4664 authz: create interceptors for gRPC security policy API
  authz/rbac_translator.go
  authz/rbac_translator_test.go
  authz/sdk_end2end_test.go
  authz/sdk_server_interceptors.go
  authz/sdk_server_interceptors_test.go
  internal/xds/rbac/rbac_engine.go
Labels: Type: Feature

#4728 xds: Fix race in Filter Chain
  xds/internal/server/listener_wrapper.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
Labels: Type: Bug

#4712 xds: use separate update channels for listeners in test
  xds/internal/test/xds_server_serving_mode_test.go
Labels: Type: Testing

#4713 oauth: Allow access to Google API regional endpoints via Google Default Credentials
  credentials/oauth/oauth.go
  credentials/oauth/oauth_test.go
  internal/credentials/util.go
Labels: Type: Bug

#4731 priority: forward the first IDLE state and picker
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Feature

#4735 xds: remove env var protection for security on client
  internal/xds/env/env.go
  xds/internal/test/xds_integration_test.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Internal Cleanup

#4737 xds: update go-control-plane to latest
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  xds/csds/csds_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/internal/testutils/e2e/server.go
Labels: Type: Internal Cleanup

#4738 xds: add retry support
  .github/workflows/testing.yml
  internal/envconfig/envconfig.go
  internal/xds/env/env.go
  test/retry_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4677 interop-testing: add soak test cases to interop client
  interop/client/client.go
  interop/test_utils.go
Labels: Status: Requires Reporter Clarification, Type: Testing

#4726 xds: Added server side routing
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/server/conn_wrapper.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/testutils/e2e/clientresources.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/matcher.go
  xds/internal/xdsclient/matcher_test.go
  xds/internal/xdsclient/v2/rds_test.go
  xds/internal/xdsclient/xds.go
  xds/server.go
Labels: Type: Feature

#4747 xds: support new fields to fetch security configuration
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4752 xds: don't remove env var protection for security on the client yet
  internal/xds/env/env.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Internal Cleanup

#4743 xds: update xdsclient NACK to keep valid resources
  xds/csds/csds_test.go
  xds/internal/xdsclient/callback.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/eds_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/v2/cds_test.go
  xds/internal/xdsclient/v2/client_test.go
  xds/internal/xdsclient/v2/eds_test.go
  xds/internal/xdsclient/v2/lds_test.go
  xds/internal/xdsclient/v2/rds_test.go
  xds/internal/xdsclient/watchers_cluster_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_listener_test.go
  xds/internal/xdsclient/watchers_route_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Behavior Change

#4754 credentials/ALTS: Ensure ALTS record protocol names are consistent
  credentials/alts/internal/conn/record_test.go
Labels: Type: Testing

#4751 grpc: close underlying transport when subConn is closed when in connecting state
  clientconn.go
Labels: Type: Bug

#4755 client: fix case where GOAWAY would leak connections and memory
  clientconn.go
  test/end2end_test.go
Labels: Type: Bug

#4756 balancer: fix aggregated state to not report idle with zero subconns
  balancer/balancer.go
  balancer/base/balancer.go
  balancer/roundrobin/roundrobin.go
Labels: Type: Bug

#4748 xds: RBAC HTTP Filter
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/test/xds_integration_test.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Feature

#4757 grpc: clarify the use of transport.ErrConnClosing from createTransport()
  clientconn.go
Labels: Type: Internal Cleanup

#4739 license: add NOTICE.txt file
  NOTICE.txt
Labels: Type: Meta

#4749 stats: support stats for all retry attempts; support transparent retry
  stats/stats.go
  stream.go
  test/end2end_test.go
  test/retry_test.go
Labels: Type: Feature

#4744 xds/affinity: fix bugs in clusterresolver and xds-resolver
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Bug

#4769 priority: handle Idle children the same way as Ready
  xds/internal/balancer/priority/balancer_priority.go
Labels: Type: Bug

#4770 transport/server: add :method POST to incoming metadata
  binarylog/binarylog_end2end_test.go
  internal/transport/http2_server.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#4753 xds: de-experimentalize xDS apis required for psm security
  connectivity/connectivity.go
  credentials/xds/xds.go
  xds/internal/server/listener_wrapper.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/server.go
  xds/server_options.go
  xds/server_test.go
  xds/xds.go
Labels: Type: Documentation, Type: API Change

#4741 ringhash: the balancer
  xds/internal/balancer/ringhash/logging.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
  xds/internal/test/xds_client_affinity_test.go
Labels: Type: Feature

#4762 xds: validations for security config, as specified in A29
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Internal Cleanup

#4763 test/bufconn: add Listener.DialContext(context.Context)
  test/bufconn/bufconn.go
Labels: Type: Feature

#4776 xds: enable ringhash and retry by default
  .github/workflows/testing.yml
  internal/xds/env/env.go
  test/retry_test.go
Labels: Type: Feature

#4774 tlogger: print log type
  internal/grpctest/tlogger.go
Labels: Type: Testing

#4765 xds: Add env var protection for RBAC HTTP Filter
  internal/xds/env/env.go
  xds/internal/httpfilter/httpfilter.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/filter_chain_test.go
  xds/internal/xdsclient/lds_test.go
  xds/server.go
Labels: Type: Internal Cleanup

#4783 [Backport grpc#27373] add testing_version flag
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#4784 xds/test: delete use of removed types
  internal/xds/matcher/string_matcher_test.go
  xds/internal/xdsclient/rds_test.go
Labels: Type: Internal Cleanup

#4785 transport: fix transparent retries when per-RPC credentials are in use
  internal/transport/http2_client.go
  stream.go
Labels: Type: Bug

#4790 Revert "transport/server: add :method POST to incoming metadata (#4770)"
  binarylog/binarylog_end2end_test.go
  internal/transport/http2_server.go
  test/end2end_test.go
Labels: Type: Feature

#4791 Change version to 1.41.0
  version.go
Labels: Type: Documentation

#4793 Change version to 1.42.0-dev
  version.go
Labels: Type: Documentation

#4798 transport: fix log spam from Server Authentication Handshake errors
  internal/transport/http2_server.go
  server.go
Labels: Type: Bug

#4745 transport: fix a typo in http2_server.go
  internal/transport/http2_server.go
Labels: Status: Requires Reporter Clarification, Type: Internal Cleanup

#4786 xds: Added validations for HCM to support xDS RBAC Filter
  internal/xds/rbac/matchers.go
  xds/internal/xdsclient/filter_chain.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4746 server: optimize chain interceptors (-1 allocation, -10% time/call)
  server.go
Labels: Type: Performance

#4801 xds: fix parent balancers to handle Idle children
  xds/internal/balancer/clustermanager/balancerstateaggregator.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
  xds/internal/balancer/weightedtarget/weightedtarget_test.go
Labels: Type: Bug

#4805 interop: don't use WithBlock dial option in the client
  interop/client/client.go
Labels: Type: Testing

#4806 github: set a shorter timeout on testing jobs
  .github/workflows/codeql-analysis.yml
  .github/workflows/testing.yml
Labels: Type: Meta

#4807 xds: have separate tests for RBAC on and off
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Testing

#4787 grpc: cleanup parse target and authority tests
  clientconn_authority_test.go
  clientconn_parsed_target_test.go
  clientconn_test.go
  internal/grpcutil/target_test.go
Labels: Type: Testing

#4797 channelz: recommend using admin.Register instead
  admin/admin.go
  channelz/service/service.go
Labels: Type: Documentation

#4792 Change version to 1.41.1-dev
  version.go
Labels: Type: Documentation

#4811 test: add option to make httpServer wait for END_STREAM; fix RetryStats race
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  test/end2end_test.go
  test/retry_test.go
Labels: Type: Testing

#4803 transport: logic specified in A41 to support RBAC xDS HTTP Filter
  internal/transport/controlbuf.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  test/end2end_test.go
Labels: Type: Feature

#4815 xds: Small changes at xDS RBAC Layer
  internal/xds/rbac/rbac_engine.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Feature

#4781 advancedtls: add revocation support to client/server options
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Feature

#4788 xds/rds: NACK unknown route action cluster specifier
  xds/internal/test/xds_server_integration_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/xds.go
Labels: Type: Bug

#4816 transport: call stats handler for trailers before closeStream
  internal/transport/http2_client.go
Labels: Type: Bug

#4818 xds: Small RBAC Changes defined in A41
  internal/xds/rbac/matchers.go
  internal/xds/rbac/rbac_engine.go
  internal/xds/rbac/rbac_engine_test.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Feature

#4813 internal: log SubConn type if it's not the expected type
  picker_wrapper.go
Labels: Type: Internal Cleanup

#4819 rls: improve config parsing
  balancer/rls/internal/config.go
  balancer/rls/internal/config_test.go
Labels: Type: Internal Cleanup

#4799 xds: nack if certprovider instance name is missing in bootstrap config
  xds/internal/test/xds_security_config_nack_test.go
  xds/internal/xdsclient/cds_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/eds_test.go
  xds/internal/xdsclient/lds_test.go
  xds/internal/xdsclient/rds_test.go
  xds/internal/xdsclient/v2/client.go
  xds/internal/xdsclient/v3/client.go
  xds/internal/xdsclient/xds.go
Labels: Type: Feature

#4767 credentials/google: introduce a new API `NewComputeEngineCredsWithOptions`
  credentials/google/google.go
  credentials/google/google_test.go
Labels: Type: Feature
