Repository grpc/grpc-go, pull requests merged in 2021-04, with the labels that each got.

#4277 xds: Add fields to cluster update
  xds/internal/client/cds_test.go
  xds/internal/client/client.go
  xds/internal/client/xds.go
Labels: Type: Behavior Change

#4307 xds/interop: register admin services and reflection to interop client
  interop/xds/client/client.go
Labels: Cherry Pick, no release notes

#4324 xds: fix service request counter flaky test
  xds/internal/client/requests_counter.go
  xds/internal/client/requests_counter_test.go
Labels: no release notes

#4320 xds/interop: register admin services and reflection (#4307)
  interop/xds/client/client.go
Labels: Type: Testing, no release notes

#4308 balancergroup: fix leak child balancer not closed
  xds/internal/balancer/balancergroup/balancergroup.go
  xds/internal/balancer/balancergroup/balancergroup_test.go
Labels: Type: Bug

#4318 xds/clusterimpl: fix picker update race after balancer is closed
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
Labels: no release notes

#4326 xds/csds: update proto imports to separate grpc from non-grpc symbols
  xds/csds/csds_test.go
Labels: Type: Internal Cleanup, no release notes

#4305 Change version to 1.37.1-dev
  version.go
Labels: no release notes

#4327 xds/resolver: fix panic when two LDS updates are receives without RDS in between
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Bug

#4325 xds/interop: move header/path matching to all
  test/kokoro/xds.sh
Labels: no release notes

#4315 xds: add support for unsupported filter matchers
  xds/internal/client/filter_chain.go
  xds/internal/client/filter_chain_test.go
  xds/internal/client/lds_test.go
Labels: Type: Feature

#4256 examples: update xds examples for PSM security
  examples/features/xds/client/main.go
  examples/features/xds/server/main.go
Labels: Type: Feature

#4309 weightedtarget: handle updating child policy name
  xds/internal/balancer/weightedtarget/weightedtarget.go
  xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
  xds/internal/balancer/weightedtarget/weightedtarget_test.go
Labels: Type: Bug

#4313 cmd/protoc-gen-go-grpc: add protoc and protoc-gen-go-grpc versions to top comment
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/grpc_testing/test_grpc.pb.go
Labels: Type: Documentation, no release notes

#4312 xds: server-side listener network filter validation
  internal/testutils/marshal_any.go
  xds/internal/client/filter_chain_test.go
  xds/internal/client/lds_test.go
  xds/internal/client/xds.go
  xds/internal/httpfilter/httpfilter.go
  xds/internal/httpfilter/router/router.go
  xds/internal/test/xds_server_integration_test.go
Labels: Type: Feature

#4310 xds/google_default_creds: handshake based on cluster name in address attributes
  credentials/google/google.go
  credentials/google/google_test.go
  credentials/google/xds.go
  internal/credentials/xds/handshake_cluster.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
Labels: Type: Feature

#4337 multiple: go mod tidy to make vet happy
  examples/go.sum
  go.sum
  security/authorization/go.sum
Labels: Type: Internal Cleanup, no release notes

#4311 client: propagate connection error causes to RPC statuses
  clientconn.go
  internal/transport/http2_client.go
  internal/transport/keepalive_test.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  test/end2end_test.go
Labels: Type: Feature

#4339 credentials/google: remove unnecessary dependency on xds protos
  credentials/credentials.go
  credentials/google/google_test.go
  credentials/google/xds.go
  credentials/sts/sts_test.go
  credentials/xds/xds_client_test.go
  internal/credentials/credentials.go
  internal/internal.go
  internal/transport/http2_client.go
  internal/xds_handshake_cluster.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/edsbalancer/eds_impl.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
Labels: Type: Internal Cleanup, no release notes

#4314 xds/clusterimpl: trigger re-resolution on subconn transient_failure
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/testutils/balancer.go
Labels: Type: Feature, no release notes

#4214 test: Fix goroutine leaks
  clientconn_state_transition_test.go
  credentials/alts/internal/handshaker/handshaker_test.go
  credentials/local/local_test.go
  internal/transport/keepalive_test.go
  internal/transport/proxy_test.go
  test/end2end_test.go
Labels: Type: Testing, no release notes

#4270 Move exponential backoff to DNS resolver from resolver.ClientConn
  balancer_conn_wrappers_test.go
  dialoptions.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  resolver/resolver.go
  resolver_conn_wrapper.go
  resolver_conn_wrapper_test.go
  test/balancer_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: API Change, Type: Behavior Change

#4334 xds/balancers: export balancer names and config structs
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/config.go
  xds/internal/balancer/clusterimpl/config_test.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/balancer_test.go
  xds/internal/balancer/lrs/config.go
  xds/internal/balancer/lrs/config_test.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/priority/config.go
  xds/internal/balancer/priority/config_test.go
  xds/internal/balancer/weightedtarget/weightedtarget.go
  xds/internal/balancer/weightedtarget/weightedtarget_config.go
  xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
  xds/internal/balancer/weightedtarget/weightedtarget_test.go
Labels: no release notes

#4353 internal: fix symbol undefined build failure
  xds/internal/balancer/clusterimpl/balancer_test.go
Labels: Type: Internal Cleanup, no release notes

#4354 test: enable xDS CSDS test
  test/kokoro/xds.sh
Labels: Type: Testing, no release notes

#4344 Run emulated linux arm64 tests
  .github/workflows/testing.yml
Labels: no release notes

#4347 client: fix leaked addrConn struct when addresses are updated
  balancer_conn_wrappers.go
  clientconn.go
Labels: Cherry Pick, Type: Bug

#4359 test: enable xDS CSDS test
  test/kokoro/xds.sh
Labels: no release notes

#4361 xds: specify "h2" as the alpn in xds creds
  internal/credentials/xds/handshake_info.go
Labels: Type: Bug, no release notes

#4356 xds/lrs: server name is not required to be non-empty
  xds/internal/balancer/lrs/balancer.go
  xds/internal/balancer/lrs/config.go
  xds/internal/balancer/lrs/config_test.go
Labels: Type: Bug, no release notes

#4316 client: include details about GOAWAYs in status messages
  internal/transport/http2_client.go
  internal/transport/keepalive_test.go
  internal/transport/transport.go
  test/end2end_test.go
Labels: Type: Feature

#4328 xds: serving mode changes outlined in gRFC A36
  internal/internal.go
  server.go
  xds/internal/server/listener_wrapper.go
  xds/internal/test/xds_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/server.go
  xds/server_options.go
  xds/server_test.go
  xds/xds.go
Labels: Type: Feature, no release notes

#4340 reflection: accept interface instead of grpc.Server struct in Register()
  reflection/serverreflection.go
Labels: Type: API Change

#4352 xds/cds: add separate fields for cluster name and eds service name
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/edsbalancer/config.go
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_impl_test.go
  xds/internal/balancer/edsbalancer/eds_test.go
  xds/internal/balancer/edsbalancer/load_store_wrapper.go
  xds/internal/client/cds_test.go
  xds/internal/client/client.go
  xds/internal/client/client_test.go
  xds/internal/client/v2/cds_test.go
  xds/internal/client/watchers_cluster_test.go
  xds/internal/client/xds.go
Labels: no release notes

#4275 xds/priority: add ignore reresolution boolean to config
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/priority/config.go
  xds/internal/balancer/priority/config_test.go
  xds/internal/balancer/priority/ignore_resolve_now.go
  xds/internal/balancer/priority/ignore_resolve_now_test.go
Labels: Type: Feature

#4360 metadata: reduce memory footprint in FromOutgoingContext
  metadata/metadata.go
Labels: Type: Performance

#4368 serviceconfig: support marshalling BalancerConfig to JSON
  internal/serviceconfig/serviceconfig.go
  internal/serviceconfig/serviceconfig_test.go
Labels: Type: Feature, no release notes

#4372 xds/circuit_breaking: use cluster name as key, not EDS service name
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_test.go
Labels: no release notes

#4373 internal: regenerate proto
  balancer/rls/internal/proto/grpc_lookup_v1/rls.pb.go
Labels: Type: Internal Cleanup, no release notes

#4364 grpc: call balancer.Close() before returning from ccBalancerWrapper.close()
  balancer_conn_wrappers.go
Labels: Type: Bug

#4378 xds/eds: restart EDS watch after previous was canceled
  xds/internal/balancer/edsbalancer/eds.go
  xds/internal/balancer/edsbalancer/eds_test.go
Labels: Type: Bug, no release notes
