Repository grpc/grpc-go, pull requests merged in 2021-10, with the labels that each got.

#4821 test: fix stayConnected to call Connect after state reports IDLE
  clientconn_test.go
Labels: Type: Testing

#4832 rls: pull proto changes made in grpc-proto/pull/98
  balancer/rls/internal/proto/grpc_lookup_v1/rls.pb.go
Labels: Type: Dependencies

#4836 xds: remove race in TestUnmarshalCluster_WithUpdateValidatorFunc
  xds/internal/test/xds_security_config_nack_test.go
Labels: Type: Testing

#4837 server: add missing conn.Close if the connection dies before reading the HTTP/2 preface
  internal/transport/http2_server.go
  server.go
  test/end2end_test.go
Labels: Type: Bug, Cherry Pick

#4840 kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4841 github: increase timeout for codeql and disable for PRs
  .github/workflows/codeql-analysis.yml
Labels: Type: Testing

#4842 [Backport v1.41.x] kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4843 [Backport v1.40.x] kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4844 [Backport v1.39.x] kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4845 [Backport v1.38.x] kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4846 [Backport v1.37.x] kokoro: remove expired letsencrypt.org cert and update
  test/kokoro/xds.sh
Labels: Type: Testing

#4830 creds/google: replace NewComputeEngineCredsWithOptions with NewDefaultCredentialsWithOptions
  credentials/google/google.go
  credentials/google/google_test.go
Labels: Type: Feature

#4831 xds: suppress redundant resource updates using proto.Equal
  xds/internal/test/xds_server_serving_mode_test.go
  xds/internal/xdsclient/callback.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/watchers_cluster_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_listener_test.go
  xds/internal/xdsclient/watchers_route_test.go
Labels: Type: Feature

#4913 internal: update rls.pb.go
  balancer/rls/internal/proto/grpc_lookup_v1/rls_config.pb.go
Labels: Type: Internal Cleanup

#4912 Change version to 1.43.0-dev
  version.go
Labels: Type: Meta
