Repository grpc/grpc-go, pull requests merged in 2022-05, with the labels that each got.

#5331 xds/client: hold authority mutex before making a new authority
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/loadreport.go
Labels: Type: Bug

#5323 client: fix potential panic during RPC retries
  clientconn.go
  internal/transport/http2_client.go
  picker_wrapper.go
  stream.go
  test/end2end_test.go
  test/retry_test.go
Labels: Type: Bug, Cherry Pick

#5317 xds: Handle loops and ignore duplicates in aggregated cluster handling
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
Labels: Type: Bug

#5339 xdsclient/csds: fix leaked metadata
  xds/internal/xdsclient/pubsub/update.go
Labels: Type: Bug, Cherry Pick

#5299 xds: Add Outlier Detection configuration and CDS handling
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/outlierdetection/config.go
  xds/internal/xdsclient/xdsresource/type_cds.go
Labels: Type: Feature

#5334 xds/priority: start the init timer when a child switch to Connecting from non-transient-failure state
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Behavior Change

#5357 xds/resolver: use correct resource name in log message
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
Labels: Type: Internal Cleanup

#5345 xds: Added support for metadataMatcher.invert
  internal/xds/rbac/matchers.go
  internal/xds/rbac/rbac_engine_test.go
Labels: Type: Feature

#5338 xds/ringhash: update connectivity state aggregation, and make sure at least one SubConn is connecting in TF
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Behavior Change

#5364 Added HTTP status and grpc status to POST check
  internal/transport/controlbuf.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
Labels: Type: Behavior Change, fixit

#5374 xds/priority: avoid sending duplicate updates to children
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Bug

#5373 client/SubConn: do not recreate addrConn if UpdateAddresses is called with the same addresses
  clientconn.go
  clientconn_test.go
Labels: Type: Bug

#5370 Don't call cmp in non testing file
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/outlierdetection/config.go
  xds/internal/balancer/outlierdetection/config_test.go
Labels: Type: Bug

#5379 Change version to 1.48.0-dev
  version.go
Labels: Type: Meta

#5363 xds: move e2e tests into grpc/test/xds directory
  internal/internal.go
  internal/testutils/xds/e2e/bootstrap.go
  internal/testutils/xds/e2e/clientresources.go
  internal/testutils/xds/e2e/server.go
  internal/testutils/xds/e2e/setup_certs.go
  internal/testutils/xds/e2e/setup_management_server.go
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_integration_test.go
  test/xds/xds_client_retry_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
  xds/csds/csds_test.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/test/e2e/controlplane.go
  xds/internal/test/e2e/e2e_test.go
  xds/internal/test/xds_client_integration_test.go
  xds/internal/test/xds_integration_test.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/server_test.go
  xds/xds.go
Labels: Type: Testing

#5381 interop: update proto by running regenerate.sh
  interop/grpc_testing/messages.pb.go
Labels: Type: Testing

#5367 xds/clusterresolver: reuse child policy names for the same locality
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_childname.go
  xds/internal/balancer/clusterresolver/configbuilder_childname_test.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_test.go
Labels: Type: Bug

#5382 test/xds: move tests to a package with _test suffix
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_integration_test.go
  test/xds/xds_client_retry_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
Labels: Type: Testing

#5387 xds/priority: clean up tests
  internal/testutils/balancer.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Testing
