Repository grpc/grpc-go, pull requests merged in 2022-04, with the labels that each got.

#5280 xdsclient: always backoff between new streams even after successful stream
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/controller.go
  xds/internal/xdsclient/controller/controller.go
  xds/internal/xdsclient/controller/controller_test.go
  xds/internal/xdsclient/controller/transport.go
  xds/internal/xdsclient/controller/v2_testutils_test.go
Labels: Type: Bug

#5285 grpc: perform graceful switching of LB policies in the `ClientConn` by default
  balancer_conn_wrappers.go
  clientconn.go
  clientconn_test.go
  internal/balancer/gracefulswitch/gracefulswitch.go
  internal/balancer/stub/stub.go
  test/balancer_switching_test.go
  test/resolver_update_test.go
  test/roundrobin_test.go
Labels: Type: Feature

#5287 [v1.37.x] xds/kokoro: install go 1.17, and retry go build (#5015)
  test/kokoro/xds.sh
Labels: Type: Testing

#5286 [v1.38.x] xds/kokoro: install go 1.17, and retry go build (#5015)
  test/kokoro/xds.sh
Labels: Type: Testing

#5281 xds: Add RLS in xDS e2e test
  balancer/rls/balancer_test.go
  balancer/rls/control_channel_test.go
  balancer/rls/helpers_test.go
  balancer/rls/picker_test.go
  internal/testutils/rls/fake_rls_server.go
  internal/testutils/wrappers.go
  xds/internal/clusterspecifier/cluster_specifier.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/test/xds_client_integration_test.go
Labels: Type: Feature

#5294 interop: build client without timeout; add logs to help debug failures
  .github/workflows/testing.yml
  interop/client/client.go
  interop/interop_test.sh
  interop/server/server.go
Labels: Type: Testing

#5240 cmd/protoc-gen-go-grpc: allow hooks to modify client structs and service handlers
  cmd/protoc-gen-go-grpc/grpc.go
Labels: Type: Internal Cleanup

#5196 gcp/observability: implement logging via binarylog
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  gcp/observability/internal/config/config.pb.go
  gcp/observability/internal/config/config.proto
  gcp/observability/internal/logging/logging.pb.go
  gcp/observability/internal/logging/logging.proto
  gcp/observability/logging.go
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/tags.go
  gcp/observability/tags_test.go
  internal/binarylog/binarylog.go
  internal/binarylog/env_config.go
  internal/binarylog/env_config_test.go
Labels: Type: Feature

#5298 Change version to 1.47.0-dev
  version.go
Labels: Type: Meta

#5292 server: return better status for context err when writing header
  internal/transport/http2_server.go
  test/end2end_test.go
Labels: Type: Bug

#5302 server: clarify documentation around setting and sending headers and ServerStream errors
  server.go
  stream.go
Labels: Type: Documentation

#5303 xds/eds: reject EDS resources with multiple instances of the same locality in the same priority
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Bug

#5300 gcp/observability: correctly test this module in presubmit tests
  .github/workflows/testing.yml
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/logging.go
  gcp/observability/observability_test.go
Labels: Type: Internal Cleanup

#5272 test/interop: register RLS to the interop test client
  interop/client/client.go
Labels: Type: Testing

#5307 backport: gcp/observability: correctly test this module in presubmit tests
  .github/workflows/testing.yml
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/logging.go
  gcp/observability/observability_test.go
Labels: Type: Internal Cleanup

#5306 documentation: fix typo in RegisterCodec godoc
  encoding/encoding.go
Labels: Type: Documentation

#5332 internal/proto: update generated code
  internal/proto/grpc_service_config/service_config.pb.go
Labels: Type: Internal Cleanup
