Repository grpc/grpc-go, pull requests merged in 2022-09, with the labels that each got.

#5531 orca: server side custom metrics implementation
  internal/internal.go
  orca/call_metric_recorder.go
  orca/call_metric_recorder_test.go
  orca/internal/internal.go
  orca/orca.go
  orca/orca_test.go
  orca/service.go
  orca/service_test.go
  server.go
Labels: Type: Feature

#5607 optimization of the roundrobin implementation.
  balancer/roundrobin/roundrobin.go
Labels: Type: Performance

#5617 cleanup: fixes for issues surfaced by vet
  balancer/rls/balancer_test.go
  credentials/alts/internal/conn/record_test.go
  internal/testutils/balancer.go
  internal/testutils/roundrobin/roundrobin.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Internal Cleanup

#5540 Grab comment from proto file, similar to protoc-gen-go
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/grpc_testing/test_grpc.pb.go
Labels: Status: Requires Reporter Clarification, Type: Feature

#5435 xds: add Outlier Detection Balancer
  internal/grpcrand/grpcrand.go
  test/xds/xds_client_outlier_detection_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/balancer/outlierdetection/callcounter.go
  xds/internal/balancer/outlierdetection/callcounter_test.go
  xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
  xds/internal/balancer/outlierdetection/logging.go
  xds/internal/balancer/outlierdetection/subconn_wrapper.go
Labels: Type: Feature

#5623 gcp/observability: fix End() to cleanup global state correctly
  .github/workflows/testing.yml
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
Labels: Type: Bug

#5630 Documentation/proxy: update due to Go 1.16 behavior change
  Documentation/proxy.md
Labels: Type: Documentation

#5596 metadata: add ValueFromIncomingContext to more efficiently retrieve a single value
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Feature

#5645 orca: fix package used to reference service to use grpc suffix instead of pb
  orca/service.go
Labels: Type: Bug

#5647 orca: fix package used to reference service to use pb suffix instead of grpc
  orca/service.go
Labels: Type: Bug

#5633 test/kokoro: enable pod log collection in the buildscripts (v1.49.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5637 test/kokoro: enable pod log collection in the buildscripts (v1.46.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5638 test/kokoro: enable pod log collection in the buildscripts (v1.45.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5642 test/kokoro: enable pod log collection in the buildscripts (v1.40.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5641 test/kokoro: enable pod log collection in the buildscripts (v1.41.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5640 test/kokoro: enable pod log collection in the buildscripts (v1.43.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5639 test/kokoro: enable pod log collection in the buildscripts (v1.44.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5636 test/kokoro: enable pod log collection in the buildscripts (v1.47.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5635 test/kokoro: enable pod log collection in the buildscripts (v1.48.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5634 test/kokoro: enable pod log collection in the buildscripts (v1.42.x backport)
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5650 test: loosen metadata error check to reduce dependence on exact library errors
  test/metadata_test.go
Labels: Type: Testing

#5632 xds: Enable Outlier Detection interop tests
  test/kokoro/xds_k8s_lb.sh
Labels: Type: Testing

#5656 rls: delegate pick to child policy as long as it is not in TransientFailure
  balancer/rls/picker.go
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
Labels: Type: Bug

#5652 transport: Fix deadlock in transport caused by GOAWAY race with new stream creation
  internal/transport/http2_client.go
  test/clienttester.go
  test/end2end_test.go
Labels: Type: Bug

#5664 xDS: Outlier Detection Env Var not hardcoded to false
  internal/envconfig/xds.go
Labels: Type: Bug

#5670 xdsclient: ignore routes with cluster_specifier_plugin when GRPC_EXPERIMENTAL_XDS_RLS_LB is off
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Bug

#5660 GitHub: restrict permissions in release workflow
  .github/workflows/release.yml
Labels: Type: Meta

#5627 orca: cleanup old code, and get grpc package to use new code
  balancer/balancer.go
  orca/orca.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/orca/orca.go
  xds/internal/balancer/orca/orca_test.go
Labels: Type: Internal Cleanup

#5678 client: remove trailing null from unix abstract socket address
  examples/features/unix_abstract/server/main.go
  internal/resolver/unix/unix.go
  test/authority_test.go
Labels: Type: Behavior Change

#5673 xds: enable Outlier Detection by default
  internal/envconfig/xds.go
  internal/internal.go
  test/xds/xds_client_outlier_detection_test.go
  xds/internal/balancer/balancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature
