Repository grpc/grpc-go, pull requests merged in 2022-07, with the labels that each got.

#5484 Change version to 1.49.0-dev
  version.go
Labels: Type: Meta

#5422 xdsclient: don't reset version info after stream restart
  internal/testutils/xds/e2e/logging.go
  internal/testutils/xds/e2e/server.go
  internal/testutils/xds/e2e/setup_management_server.go
  test/xds/xds_client_ack_nack_test.go
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_integration_test.go
  test/xds/xds_client_retry_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
  xds/csds/csds_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/test/e2e/controlplane.go
  xds/internal/xdsclient/controller/controller.go
  xds/internal/xdsclient/controller/transport.go
Labels: Type: Bug

#5473 balancer: fix connectivity state aggregation algorithm to follow the spec
  balancer/balancer.go
  balancer/conn_state_evaluator.go
  balancer/conn_state_evaluator_test.go
Labels: Type: Bug

#5479 xdsclient: move XDSClient interface definition to client.go
  xds/internal/xdsclient/attributes.go
  xds/internal/xdsclient/client.go
Labels: Type: Internal Cleanup

#5477 all: update to 'go 1.17' to enable module graph pruning
  go.mod
  go.sum
Labels: Type: Internal Cleanup

#5493 internal/xds: generate an entry in the authorities map with empty string key
  internal/xds/bootstrap.go
Labels: Type: Testing

#5491 xdsclient: use top-level server list if authority specific list is empty
  xds/internal/xdsclient/authority.go
Labels: Type: Bug

#5495 doc: remove comment about obsolete GRPC_GO_RETRY env var
  dialoptions.go
  examples/features/retry/README.md
Labels: Type: Documentation

#5488 xdsclient: handle empty authority in new style resource names
  xds/internal/xdsclient/xdsresource/name.go
  xds/internal/xdsclient/xdsresource/name_test.go
Labels: Type: Bug

#5483 Change version to 1.48.1-dev
  version.go
Labels: Type: Meta

#5494 Fix race between activeStreams and bdp window size
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Bug

#5504 xds: re-add testing only NewXDSResolverWithConfigForTesting()
  xds/xds.go
Labels: Cherry Pick, Type: Dependencies

#5503 client: fix stream creation issue with transparent retry
  stream.go
Labels: Type: Bug, Cherry Pick

#5505 xdsclient: fix LRS stream leaks when errors are encountered
  xds/internal/xdsclient/controller/transport.go
  xds/internal/xdsclient/controller/version/v2/loadreport.go
  xds/internal/xdsclient/controller/version/v3/loadreport.go
Labels: Type: Bug, Cherry Pick

#5508 test/kokoro: Add missing secondary_kube_context to xds LB tests
  test/kokoro/xds_k8s_lb.sh
Labels: Type: Testing

#5524 grpc: change the log-level when a new ServerTransport cannot be created
  server.go
Labels: Type: Behavior Change

#5502 interop client: fixes for interop soak test
  interop/test_utils.go
Labels: Type: Testing

#5525 gcp/observability: Add support for Environment Variable GRPC_CONFIG_OBSERVABILITY_JSON
  gcp/observability/config.go
  gcp/observability/observability_test.go
Labels: Type: Feature

#5527 balancer/weightedtarget: pause picker updates during UpdateClientConnState
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget.go
  balancer/weightedtarget/weightedtarget_test.go
Labels: Type: Feature

#5528 xds/clustermanager: pause picker updates during UpdateClientConnState
  xds/internal/balancer/clustermanager/balancerstateaggregator.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: Feature

#5537 xds: Fixed GoLang regression for Outlier Detection
  internal/envconfig/xds.go
Labels: Type: Bug

#5532 xdsclient: change receiver on BootstrapConfig() to be consistent
  xds/internal/xdsclient/client.go
Labels: Type: Internal Cleanup

#5529 test/interop: increase pick_first timeout
  interop/test_utils.go
Labels: Type: Testing

#5538 Backport Outlier Detection Fix to 1.48
  internal/envconfig/xds.go
Labels: Type: Bug, Cherry Pick

#5533 xdsclient: organize existing contents better with new files
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/clientimpl_dump.go
  xds/internal/xdsclient/clientimpl_loadreport.go
  xds/internal/xdsclient/clientimpl_validator.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/controller.go
  xds/internal/xdsclient/singleton.go
Labels: Type: Internal Cleanup

#5506 xdsclient: cleanup listener watchers test
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
  xds/internal/xdsclient/watchers_listener_test.go
Labels: Type: Testing

#5534 test: improve the logic for checking round_robin
  test/roundrobin_test.go
Labels: Type: Testing

#5513 transport/server: fix race that could cause a stray header to be sent
  internal/transport/http2_server.go
  test/end2end_test.go
Labels: Type: Bug, Cherry Pick

#5543 grpc: prevent a nil stats handler from causing a panic
  default_dial_option_server_option_test.go
  dialoptions.go
  server.go
  test/end2end_test.go
Labels: Type: Bug
