Repository grpc/grpc-go, pull requests merged in 2022-08, with the labels that each got.

#5539 rls: suppress picker updates from children when handling config updates
  balancer/rls/balancer.go
  balancer/rls/balancer_test.go
  balancer/rls/control_channel.go
Labels: Type: Feature

#5549 priority: sync priority with child in use
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Bug

#5551 test: move clientconn state transition test to test/ directory
  clientconn_test.go
  test/clientconn_state_transition_test.go
Labels: Type: Testing

#5556 Switched mutex unlock to defer in newAddrConn
  clientconn.go
Labels: Type: Bug

#5555 grpc: remove mentions of deleted API, WithBalancerName, from comments
  service_config.go
  test/channelz_test.go
  vet.sh
Labels: Type: Internal Cleanup

#5552 xdsclient: deflake Test/LDSWatch_PartialValid
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
Labels: Type: Testing

#5560 xdsclient: NACK endpoint resources with zero weight
  internal/testutils/xds/e2e/clientresources.go
  xds/internal/testutils/protos.go
  xds/internal/xdsclient/controller/v2_eds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Bug

#5557 ringhash: handle config updates properly
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Bug

#5568 xdsclient: NACK endpoint resource if load_balancing_weight is specified and is zero
  internal/testutils/xds/e2e/clientresources.go
  xds/internal/testutils/protos.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
Labels: Type: Bug

#5569 test/kokoro: add missing image tagging to the xDS interop url map buildscript
  test/kokoro/xds_url_map.sh
Labels: Type: Bug

#5565 O11Y: Added support for custom tags
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/internal/config/config.pb.go
  gcp/observability/internal/config/config.proto
  gcp/observability/logging.go
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
  gcp/observability/tags.go
  gcp/observability/tags_test.go
Labels: Type: Feature

#5582 gcp/observability: Add logging filters for logging, tracing, and metrics API calls
  gcp/observability/logging.go
Labels: Type: Bug

#5585 Change version to 1.50.0-dev
  version.go
Labels: Type: Meta

#5561 Publish arm64 binaries to GitHub releases
  .github/workflows/release.yml
Labels: Type: Meta

#5566 internal/transport: fix typo
  internal/transport/controlbuf.go
Labels: Type: Internal Cleanup

#5592 internal/fakegrpclb: don't listen on all adapters
  internal/testutils/fakegrpclb/server.go
Labels: Type: Testing

#5588 xds/clusterresolver: prevent deadlock of concurrent Close and UpdateState calls
  xds/internal/balancer/clusterresolver/resource_resolver.go
Labels: Type: Bug

#5591 xds/resolver: generate channel ID randomly
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/xdsclient/xdsresource/type_rds.go
Labels: Type: Feature, Cherry Pick

#5583 Change version to 1.49.0
  version.go
Labels: Type: Meta

#5584 Change version to 1.49.1-dev
  version.go
Labels: Type: Meta

#5589 transport: add peer information to http2Server and http2Client context
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
Labels: Type: Feature

#5597 Fix http2 spec document link
  internal/transport/http_util.go
Labels: Type: Documentation

#5601 xds/ringhash: make reconnection logic work for a single subConn
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/logging.go
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#5562 clusterresolver: deflake eds_impl tests
  internal/testutils/roundrobin/roundrobin.go
  internal/testutils/xds/e2e/setup_management_server.go
  test/balancer_switching_test.go
  test/roundrobin_test.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
Labels: Type: Testing

#5614 ringhash: implement a no-op ExitIdle() method
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#5608 test/kokoro: enable pod log collection in the buildscripts
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5616 cleanup: remove duplicate words in comments
  balancer/rls/config.go
  credentials/sts/sts.go
  credentials/sts/sts_test.go
  credentials/tls/certprovider/store_test.go
  internal/balancergroup/balancerstateaggregator.go
  internal/testutils/roundrobin/roundrobin.go
  security/advancedtls/advancedtls_integration_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/resolver/watch_service.go
Labels: Type: Internal Cleanup

#5613 xdsclient: NACK cluster resource if config_source_specifier in lrs_server is not self
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#5620 alts: do not set WaitForReady on handshaker service RPCs
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Bug
