Repository grpc/grpc-go, pull requests merged in 2022-10, with the labels that each got.

#5654 internal/transport: optimize grpc-message encoding/decoding
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Performance

#5687 Change version to 1.51.0-dev
  version.go
Labels: Type: Meta

#5653 grpc: restrict status codes from control plane (gRFC A54)
  credentials/credentials.go
  internal/status/status.go
  internal/transport/http2_client.go
  picker_wrapper.go
  stream.go
  test/control_plane_status_test.go
  test/creds_test.go
Labels: Type: Behavior Change

#5675 Add binary logger option for client and server
  default_dial_option_server_option_test.go
  dialoptions.go
  gcp/observability/opencensus.go
  internal/internal.go
  server.go
  stream.go
  test/end2end_test.go
Labels: Type: Feature

#5682 priority: release references to child policies which are removed
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/priority/ignore_resolve_now.go
  xds/internal/balancer/priority/ignore_resolve_now_test.go
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#5541 client: set grpc-accept-encoding to full list of registered compressors
  encoding/encoding.go
  internal/envconfig/envconfig.go
  internal/grpcutil/compressor.go
  internal/grpcutil/compressor_test.go
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Feature

#5691 xdsclient: improve LDS watchers test
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/dump_test.go
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
  xds/internal/xdsclient/loadreport_test.go
Labels: Type: Testing

#5704 gcp/observability: implement public preview config syntax, logging schema, and exposed metrics
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/internal/logging/logging.pb.go
  gcp/observability/internal/logging/logging.proto
  gcp/observability/logging.go
  gcp/observability/logging_test.go
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
  internal/binarylog/binarylog.go
  internal/binarylog/binarylog_test.go
  internal/binarylog/env_config.go
  internal/binarylog/method_logger.go
  internal/binarylog/method_logger_test.go
  internal/envconfig/observability.go
Labels: Type: Feature

#5707 xds: de-experimentalize google c2p resolver
  xds/googledirectpath/googlec2p.go
Labels: Type: Feature

#5715 xds/xdsclient: add EDS resource endpoint address duplication check
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Behavior Change

#5719 Fix o11y typo
  gcp/observability/config.go
Labels: Type: Bug

#5720 o11y: Fixed o11y bug
  server.go
Labels: Type: Bug

#5722 Cherry-pick observability changes from master to v1.50.x and update version to 1.50.1
  default_dial_option_server_option_test.go
  dialoptions.go
  gcp/observability/config.go
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/internal/logging/logging.pb.go
  gcp/observability/internal/logging/logging.proto
  gcp/observability/logging.go
  gcp/observability/logging_test.go
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
  internal/binarylog/binarylog.go
  internal/binarylog/binarylog_test.go
  internal/binarylog/env_config.go
  internal/binarylog/method_logger.go
  internal/binarylog/method_logger_test.go
  internal/envconfig/observability.go
  internal/internal.go
  server.go
  stream.go
  test/end2end_test.go
  version.go
Labels: Cherry Pick, Type: Meta

#5713 xds: move bootstrap config generating utility package to testutils
  admin/test/utils.go
  internal/testutils/xds/bootstrap/bootstrap.go
  internal/testutils/xds/e2e/setup_management_server.go
  test/xds/xds_client_federation_test.go
  xds/csds/csds_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/test/e2e/controlplane.go
Labels: Type: Testing

#5698 fakeserver: add v3 support to the xDS fakeserver implementation
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Testing

#5711 weightedtarget: return a more meaningful error when no child policy is reporting READY (#5391)
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
Labels: Type: Feature

#5693 xdsclient: improve CDS watchers test
  xds/internal/xdsclient/e2e_test/cds_watchers_test.go
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
  xds/internal/xdsclient/watchers_cluster_test.go
Labels: Type: Testing

#5702 xdsclient: add a convenience type to synchronize execution of callbacks
  xds/internal/xdsclient/callback_serializer.go
  xds/internal/xdsclient/callback_serializer_test.go
Labels: Type: Feature

#5694 xdsclient: improve EDS watchers test
  xds/internal/xdsclient/e2e_test/eds_watchers_test.go
  xds/internal/xdsclient/watchers_endpoints_test.go
  xds/internal/xdsclient/watchers_federation_test.go
Labels: Type: Testing

#5696 xdsclient: improve federation watchers test
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/e2e_test/federation_watchers_test.go
  xds/internal/xdsclient/watchers_federation_test.go
Labels: Type: Testing

#5728 tests: refactor tests to use testutils helper functions
  balancer/weightedtarget/weightedtarget_test.go
  internal/balancergroup/balancergroup_test.go
  internal/testutils/balancer.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/testutil_test.go
Labels: Type: Internal Cleanup

#5692 xdsclient: improve RDS watchers test
  xds/internal/xdsclient/e2e_test/federation_watchers_test.go
  xds/internal/xdsclient/e2e_test/rds_watchers_test.go
  xds/internal/xdsclient/watchers_route_test.go
Labels: Type: Testing

#5731 client: synchronously verify server preface in newClientTransport
  clientconn.go
  internal/grpcsync/oncefunc.go
  internal/grpcsync/oncefunc_test.go
  internal/transport/http2_client.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#5680 google-c2p resolver: add authority entry to bootstrap config
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Bug

#5739 Fix flaky test MultipleClientStatsHandler
  stats/stats_test.go
Labels: Type: Testing

#5734 balancer/weightedtarget: use ConnectivityStateEvaluator
  balancer/conn_state_evaluator.go
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget.go
  internal/balancergroup/balancergroup_test.go
Labels: Type: Internal Cleanup

#5745 google-c2p: include federation env var in the logic which determines when to use directpath
  xds/googledirectpath/googlec2p.go
Labels: Type: Internal Cleanup

#5747 balancer/weightedtarget: fix ConnStateEvltr to ignore transition from TF to Connecting
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget_test.go
Labels: Type: Bug

#5743 google-c2p: use new-style resource name for LDS subscription
  xds/googledirectpath/googlec2p.go
Labels: Type: Internal Cleanup

#5752 transport/test: implement staticcheck suggestion
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup
