Repository grpc/grpc-go, pull requests merged in 2022-02, with the labels that each got.

#5182 leakcheck: ignore http read/write goroutine
  internal/leakcheck/leakcheck.go
Labels: Type: Internal Cleanup

#5056 cmd/protoc-gen-go-grpc: add hooks to allow overriding generated code
  cmd/protoc-gen-go-grpc/grpc.go
Labels: Type: Internal Cleanup

#5136 xds/bootstrap: add plugin system for credentials specified in bootstrap file
  credentials/insecure/insecure.go
  xds/bootstrap/bootstrap.go
  xds/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
Labels: Type: Feature

#5169 benchmark: update client to include xds library
  benchmark/worker/benchmark_client.go
Labels: Type: Testing

#5174 xds/interop: update RPC timeout in blackhole after fallback case
  interop/grpclb_fallback/client_linux.go
Labels: Type: Testing

#5183 xds: Add support for Outlier Detection configuration in xdsclient
  internal/envconfig/xds.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature

#5185 xds/priority: log warnings instead of errors
  xds/internal/balancer/priority/balancer_priority.go
Labels: Type: Internal Cleanup

#5177 cleanup: replace grpc.WithInsecure with insecure.NewCredentials
  admin/test/utils.go
  authz/sdk_end2end_test.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer/rls/control_channel.go
  benchmark/benchmain/main.go
  benchmark/client/main.go
  benchmark/worker/benchmark_client.go
  binarylog/binarylog_end2end_test.go
  clientconn.go
  credentials/alts/internal/handshaker/service/service.go
  examples/features/cancellation/client/main.go
  examples/features/compression/client/main.go
  examples/features/deadline/client/main.go
  examples/features/deadline/server/main.go
  examples/features/debugging/client/main.go
  examples/features/errors/client/main.go
  examples/features/health/client/main.go
  examples/features/keepalive/client/main.go
  examples/features/load_balancing/client/main.go
  examples/features/metadata/client/main.go
  examples/features/multiplex/client/main.go
  examples/features/name_resolving/client/main.go
  examples/features/retry/README.md
  examples/features/retry/client/main.go
  examples/features/unix_abstract/client/main.go
  examples/features/wait_for_ready/main.go
  internal/stubserver/stubserver.go
  interop/client/client.go
  interop/http2/negative_http2_client.go
  profiling/cmd/remote.go
  reflection/serverreflection_test.go
  stats/stats_test.go
  stress/client/main.go
  stress/metrics_client/main.go
  test/authority_test.go
  test/balancer_test.go
  test/end2end_test.go
  test/goaway_test.go
  test/gracefulstop_test.go
  test/healthcheck_test.go
  test/insecure_creds_test.go
  test/local_creds_test.go
  test/retry_test.go
  xds/csds/csds_test.go
  xds/internal/test/e2e/e2e.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/xdsclient/controller/controller_test.go
  xds/internal/xdsclient/singleton_test.go
Labels: Status: Requires Reporter Clarification, Type: Internal Cleanup

#5184 Format directory/file references
  examples/route_guide/README.md
Labels: Type: Documentation

#5190 channelz: rename NewChannelzStorage to NewChannelzStorageForTesting
  channelz/service/service_sktopt_test.go
  channelz/service/service_test.go
  internal/channelz/funcs.go
  test/channelz_linux_test.go
  test/channelz_test.go
Labels: Type: Internal Cleanup

#5191 authz: removes sdk term from grpc authz
  authz/grpc_authz_end2end_test.go
  authz/grpc_authz_server_interceptors.go
  authz/grpc_authz_server_interceptors_test.go
Labels: Type: Internal Cleanup

#5148 transport: Add an Unwrap method to ConnectionError
  internal/transport/transport.go
  internal/transport/transport_test.go
Labels: Status: Requires Reporter Clarification, Type: Feature, stale

#5180 reflection: use protobuf/reflect instead of go reflection, fix dynamic messages
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  reflection/grpc_testing_not_regenerate/README.md
  reflection/grpc_testing_not_regenerate/dynamic.pb.go
  reflection/grpc_testing_not_regenerate/dynamic.proto
  reflection/grpc_testing_not_regenerate/testv3.pb.go
  reflection/grpc_testing_not_regenerate/testv3.proto
  reflection/grpc_testingv3/README.md
  reflection/serverreflection.go
  reflection/serverreflection_test.go
  regenerate.sh
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  vet.sh
Labels: Type: Bug

#5195 xds: minor cleanup in xdsclient bootstrap code
  internal/envconfig/xds.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/singleton.go
  xds/server.go
  xds/server_options.go
  xds/xds.go
Labels: Type: Internal Cleanup

#5197 reflection: improve server implementation
  reflection/serverreflection.go
  reflection/serverreflection_test.go
Labels: Type: Feature

#5094 authz: add additional logs to sdk authz
  authz/grpc_authz_server_interceptors.go
  internal/xds/rbac/rbac_engine.go
Labels: Type: Internal Cleanup

#5204 Change version to 1.46.0-dev
  version.go
Labels: Type: Meta

#5205 xds: rename rls proto import
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/clusterspecifier/rls/rls_test.go
Labels: Type: Internal Cleanup

#5192 channelz: include channelz identifier in logs
  balancer/balancer.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer_conn_wrappers.go
  call_test.go
  channelz/channelz.go
  channelz/service/service_sktopt_test.go
  channelz/service/service_test.go
  clientconn.go
  dialoptions.go
  internal/balancergroup/balancergroup_test.go
  internal/channelz/funcs.go
  internal/channelz/id.go
  internal/channelz/logging.go
  internal/channelz/types.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/keepalive_test.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  resolver/resolver.go
  resolver_conn_wrapper.go
  server.go
  test/channelz_test.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: API Change, Type: Internal Cleanup

#4886 fix: does not validate metadata keys and values
  internal/metadata/metadata.go
  internal/metadata/metadata_test.go
  stream.go
  test/metadata_test.go
Labels: Type: Bug

#5194 example: add mutual TLS example
  examples/data/x509/client_ca_cert.pem
  examples/data/x509/client_cert.pem
  examples/data/x509/client_key.pem
  examples/features/encryption/README.md
  examples/features/encryption/mTLS/client/main.go
  examples/features/encryption/mTLS/server/main.go
Labels: Type: Documentation, Status: Requires Reporter Clarification

#5209 reflection: add comments on protos
  reflection/grpc_testing_not_regenerate/dynamic.proto
  reflection/grpc_testing_not_regenerate/testv3.pb.go
  reflection/grpc_testing_not_regenerate/testv3.proto
Labels: Type: Testing, Type: Internal Cleanup

#5212 channelz: replace deprecated timestamp API with recommended ones
  channelz/service/service_test.go
Labels: Type: Internal Cleanup
