Repository grpc/grpc-go, pull requests merged in 2022-03, with the labels that each got.

#5213 test: use real grpc.Server in call tests
  call_test.go
  test/interceptor_test.go
  test/invoke_test.go
Labels: Type: Testing

#5222 internal: update service config proto
  internal/proto/grpc_service_config/service_config.pb.go
Labels: Type: Internal Cleanup

#5227 grpc: document ClientConn fields
  clientconn.go
Labels: Type: Internal Cleanup

#5202 Change version to 1.45.0
  version.go
Labels: Type: Meta

#5203 Change version to 1.45.1-dev
  version.go
Labels: Type: Meta

#5232 grpc: delete deprecated API WithBalancerName()
  balancer_switching_test.go
  clientconn.go
  clientconn_state_transition_test.go
  clientconn_test.go
  dialoptions.go
  test/balancer_test.go
  test/end2end_test.go
  test/healthcheck_test.go
Labels: Type: API Change

#5237 proto: regenerate proto to pick up latest
  internal/proto/grpc_service_config/service_config.pb.go
Labels: Type: Internal Cleanup

#5241 xds/client: reset backoff when a message is received, even when the message is invalid
  xds/internal/xdsclient/controller/transport.go
Labels: Type: Bug

#5243 security/authorization: upgrade cel-v0.10.1 and fix breaking API change.
  security/authorization/engine/engine_test.go
  security/authorization/go.mod
  security/authorization/go.sum
Labels: Type: Dependencies

#5236 test: cleanup roundrobin tests to use stubserver
  balancer/roundrobin/roundrobin_test.go
  test/insecure_creds_test.go
  test/roundrobin_test.go
  test/timeouts.go
Labels: Type: Testing

#5238 grpc: handle invalid service configs by applying the default, if applicable
  balancer_conn_wrappers.go
  clientconn.go
Labels: Type: Bug

#5223 xds/client: include Node ID in error messages from the XdsClient
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/pubsub/pubsub.go
  xds/internal/xdsclient/pubsub/watch.go
Labels: Type: Feature

#5246 grpc: remove remaining usages of grpc.WithInsecure()
  clientconn_authority_test.go
  clientconn_parsed_target_test.go
  dialoptions.go
  pickfirst_test.go
  resolver_conn_wrapper_test.go
Labels: Type: Testing

#5242 xds/client: accept resources wrapped in discoverypb.Resource message
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/xdsresource/type.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/internal/xdsclient/xdsresource/version/version.go
Labels: Type: Feature

#5215 xds: avoid log spam during server mode switches (better A36 compliance)
  interop/xds/server/server.go
  xds/internal/server/listener_wrapper.go
  xds/internal/test/xds_server_integration_test.go
  xds/internal/test/xds_server_serving_mode_test.go
  xds/server.go
  xds/server_test.go
Labels: Type: Bug

#5245 balancergroup: Switched subBalancerWrapper to wrap a gracefulswitch.Balancer
  internal/balancergroup/balancergroup.go
  xds/internal/balancer/clusterresolver/priority_test.go
Labels: Type: Internal Cleanup

#5248 interop/client: simplify fallback test client and parameterize fallback deadline
  interop/grpclb_fallback/client_linux.go
Labels: Type: Testing

#5250 xds/interop: add xds_k8s_lb test suite
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
Labels: Type: Testing

#5244 binarylog: generalize binarylog's MethodLogger preparing for new observability features
  internal/binarylog/binarylog.go
  internal/binarylog/binarylog_test.go
  internal/binarylog/method_logger.go
  internal/binarylog/method_logger_test.go
  stream.go
Labels: Type: Internal Cleanup

#5239 internal/googlecloud: refactor OS-dependent code
  internal/googlecloud/googlecloud.go
  internal/googlecloud/googlecloud_test.go
  internal/googlecloud/manufacturer.go
  internal/googlecloud/manufacturer_linux.go
  internal/googlecloud/manufacturer_windows.go
Labels: Type: Internal Cleanup

#5261 grpc: add a comment to balancer_conn_wrapper
  balancer_conn_wrappers.go
Labels: Type: Internal Cleanup

#5219 server: set TCP_USER_TIMEOUT socket option for linux
  internal/transport/http2_server.go
  internal/transport/keepalive_test.go
Labels: Type: Feature

#5259 make the RLS LB policy name available in the internal package
  balancer/rls/balancer.go
  internal/internal.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/clusterspecifier/rls/rls_test.go
  xds/xds.go
Labels: Type: Internal Cleanup

#5258 xds: suppress redundant updates only when we are SERVING
  xds/internal/server/listener_wrapper.go
Labels: Type: Bug

#5257 grpc: do not apply default service config upon receipt of invalid service config
  clientconn.go
  resolver_conn_wrapper_test.go
  service_config.go
  test/config_selector_test.go
  test/resolver_update_test.go
Labels: Type: Bug

#5262 github: update to test with Go 1.18
  .github/workflows/testing.yml
Labels: Type: Meta

#5267 metadata: copy slices in FromContext() functions
  metadata/metadata.go
Labels: Type: Bug

#5264 test: add a test for clientConn close with pending RPC
  test/clientconn_test.go
Labels: Type: Testing

#5263 pickfirst: cleanup tests
  balancer_switching_test.go
  pickfirst_test.go
  test/pickfirst_test.go
Labels: Type: Testing

#5266 test: use `t.Fatal` instead of `panic` for service config parsing errors
  test/channelz_test.go
  test/config_selector_test.go
  test/end2end_test.go
  test/healthcheck_test.go
  test/parse_config.go
Labels: Type: Testing

#5251 balancergroup: Add trigger point to gracefully switch a child
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
Labels: Type: Feature

#5218 advancedtls: remove the usage of CDP in CRL enforcement
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
Labels: Type: Behavior Change

#5275 test: use channelz instead of stats handler to determine RPC count
  test/roundrobin_test.go
Labels: Type: Testing

#5279 clientconn: fix target parsing tests to be tolerant to new url.URL field OmitHost
  clientconn_parsed_target_test.go
Labels: Type: Testing

#5282 github: run all testing jobs to completion even if one fails
  .github/workflows/testing.yml
Labels: Type: Testing

#5274 grpc: move to `TransientFailure` in `pick_first` LB policy when all addresses are removed
  picker_wrapper_test.go
  pickfirst.go
  test/balancer_test.go
  test/pickfirst_test.go
Labels: Type: Behavior Change

#5271 test: cleanup balancer switching tests
  balancer_switching_test.go
  call_test.go
  clientconn.go
  clientconn_state_transition_test.go
  clientconn_test.go
  internal/testutils/fakegrpclb/server.go
  interop/fake_grpclb/fake_grpclb.go
  reflection/serverreflection_test.go
  server_test.go
  test/balancer_switching_test.go
  test/pickfirst_test.go
  test/resolver_update_test.go
  test/roundrobin_test.go
Labels: Type: Testing

#5265 cluster manager: Add Graceful Switch functionality to Cluster Manager
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: Feature

#5269 xds: ignore routes with unsupported cluster specifiers
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  xds/internal/clusterspecifier/cluster_specifier.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Behavior Change
