Repository grpc/grpc-go, pull requests merged in 2022-06, with the labels that each got.

#5352 internal: add global DialOptions and ServerOptions for all clients and servers
  clientconn.go
  default_dial_option_server_option_test.go
  dialoptions.go
  internal/internal.go
  server.go
Labels: Type: Internal Cleanup

#5347 stats: add support for multiple stats handlers in a single client or server
  dialoptions.go
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  server.go
  stats/stats_test.go
  stream.go
Labels: Type: Feature

#5399 credentials/google: support new-style xDS cluster names
  credentials/google/google_test.go
  credentials/google/xds.go
  credentials/google/xds_test.go
Labels: Type: Feature

#5395 interop: remove duplicated xDS tests in GCE framework
  test/kokoro/xds.sh
Labels: Type: Testing

#5400 rls: use UNAVAILABLE instead of status from control plane
  balancer/rls/picker.go
  balancer/rls/picker_test.go
Labels: Type: Bug

#5372 gcp/observability: Implement tracing/metrics via OpenCensus
  gcp/observability/config.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  gcp/observability/internal/config/config.pb.go
  gcp/observability/internal/config/config.proto
  gcp/observability/observability.go
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
Labels: Type: Feature

#5414 gcp/observability: update log name
  gcp/observability/exporting.go
Labels: Type: Behavior Change

#5424 internal/proto: pull in recent changes to service config proto
  internal/proto/grpc_service_config/service_config.pb.go
Labels: Type: Dependencies

#5427 weightedroundrobin: update comments to indicate where addrInfo is stored
  balancer/weightedroundrobin/weightedroundrobin.go
Labels: Type: Internal Cleanup

#5428 ringhash: use grpctest.Tester in unit tests
  xds/internal/balancer/ringhash/config_test.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Testing

#5426 resolver: minor improvements to AddressMap
  resolver/map.go
  resolver/map_test.go
Labels: Type: Internal Cleanup

#5434 test/kokoro: use standard TESTING_VERSION in the new framework builds
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#5371 xds: Outlier Detection configuration in Cluster Resolver Balancer
  internal/internal.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
Labels: Type: Feature

#5417 xds/priority: bug fix and minor behavior change
  balancer/base/balancer.go
  internal/testutils/balancer.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/balancer/priority/balancer_child.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Bug

#5451 interop: update grpc_testing proto
  interop/grpc_testing/messages.pb.go
Labels: Type: Internal Cleanup

#5457 outlierdetection: fix package level comments
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/config.go
Labels: Type: Internal Cleanup

#5461 xdsclient: only include nodeID in error strings, not the whole nodeProto
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/pubsub/pubsub.go
  xds/internal/xdsclient/pubsub/watch.go
Labels: Type: Internal Cleanup

#5463 test/xds: fail only when state changes to something other than READY and IDLE
  test/xds/xds_server_serving_mode_test.go
Labels: Type: Testing

#5462 clusterresolver: merge P(p)arseConfig functions
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
Labels: Type: Internal Cleanup

#5421 interop client: provide new flag, --soak_min_time_ms_between_rpcs
  interop/client/client.go
  interop/test_utils.go
Labels: Type: Testing

#5466 health: split imports into healthpb and healthgrpc
  examples/features/health/server/main.go
  examples/features/xds/server/main.go
  interop/xds/server/server.go
  test/end2end_test.go
  test/healthcheck_test.go
Labels: Type: Internal Cleanup

#5467 fix typo in the binary log
  internal/binarylog/binarylog.go
Labels: Type: Internal Cleanup

#5464 transport: remove unused `bufWriter.onFlush()`
  internal/transport/http_util.go
Labels: Type: Internal Cleanup

#5475 interop: update proto to make vet happy
  interop/grpc_testing/control.pb.go
Labels: Type: Internal Cleanup

#5476 xds: drop localities with zero weight at the xdsClient layer
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/eds_impl_test.go
  xds/internal/xdsclient/xdsresource/type_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Internal Cleanup
