Repository grpc/grpc-go, pull requests merged in 2023-05, with the labels that each got.

#6235 authz: Swap to using the correct TypedConfig in audit logger parsing
  authz/rbac_translator.go
  authz/rbac_translator_test.go
Labels: Type: Security

#6240 stubserver: add option for allowing more services to be registered
  internal/stubserver/stubserver.go
Labels: Type: Testing

#6237 xds: make glaze happy for test packages
  xds/internal/xdsclient/xdslbregistry/tests/converter_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
Labels: Type: Internal Cleanup

#6228 grpc: handle RemoveSubConn inline in balancerWrapper
  balancer_conn_wrappers.go
Labels: Type: Internal Cleanup

#6239 orca: minor cleanups
  orca/call_metric_recorder_test.go
  orca/internal/internal.go
  orca/orca.go
  orca/orca_test.go
  orca/service.go
Labels: Type: Internal Cleanup

#6238 multiple: standardize import renaming for typed structs
  authz/rbac_translator.go
  authz/rbac_translator_test.go
  xds/internal/xdsclient/xdslbregistry/converter.go
  xds/internal/xdsclient/xdslbregistry/tests/converter_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
Labels: Type: Internal Cleanup

#6236 balancer: make producer RPCs block until the SubConn is READY
  balancer_conn_wrappers.go
  clientconn.go
  orca/producer.go
  test/balancer_test.go
Labels: Type: Feature

#6243 googledirectpatph: enable ignore_resource_deletion in bootstrap
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Feature

#6246 googledirectpatph: enable ignore_resource_deletion in bootstrap (#6243)
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Feature

#6220 server/transport: send appropriate debug_data in GOAWAY frames
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_server.go
  internal/transport/keepalive_test.go
  internal/transport/transport.go
  server.go
Labels: Type: Bug

#6245 orca: fix race at producer startup
  orca/producer.go
  orca/producer_test.go
  orca/service_test.go
Labels: Type: Bug

#6211 Change version to 1.55.0
  version.go
Labels: Type: Meta

#6212 Change version to 1.55.1-dev
  version.go
Labels: Type: Meta

#6234 grpc: use CallbackSerializer in resolver_wrapper
  internal/grpcsync/callback_serializer.go
  internal/grpcsync/callback_serializer_test.go
  resolver_conn_wrapper.go
  test/service_config_deprecated_test.go
Labels: Type: Internal Cleanup

#6253 alts: Revert #6077
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Bug

#6247 Update ClientStream.SendMsg doc
  stream.go
Labels: Type: Documentation

#6255 Update version to 1.54.1
  version.go
Labels: Type: Meta

#6257 test: deflake TestBalancerProducerHonorsContext
  test/balancer_test.go
Labels: Type: Testing

#6256 Update version.go to 1.54.2-dev
  version.go
Labels: Type: Meta

#6258 orca: fix race when calling listeners coincides with updating the run goroutine
  orca/producer.go
Labels: Type: Bug

#6254 grpc: use CallbackSerializer in balancer wrapper
  balancer_conn_wrappers.go
Labels: Type: Internal Cleanup

#6224 xds: Add support for Custom LB Policies
  attributes/attributes.go
  balancer/weightedroundrobin/weightedroundrobin.go
  balancer/weightedtarget/weightedaggregator/aggregator.go
  balancer/weightedtarget/weightedtarget.go
  balancer/weightedtarget/weightedtarget_test.go
  internal/testutils/xds/e2e/clientresources.go
  resolver/resolver.go
  test/xds/xds_client_custom_lb_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_handler_test.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/wrrlocality/balancer.go
  xds/internal/balancer/wrrlocality/balancer_test.go
  xds/internal/balancer/wrrlocality/logging.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
Labels: Type: Feature

#6266 interop: add ORCA test cases and functionality
  interop/client/client.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/orcalb.go
  interop/server/server.go
  interop/test_utils.go
Labels: Type: Testing

#6268 xds/internal/xdsclient/xdslbregistry: Continue in converter if type not found
  xds/internal/xdsclient/xdslbregistry/converter.go
  xds/internal/xdsclient/xdslbregistry/tests/converter_test.go
Labels: Type: Bug

#6262 interop/xds: Add Custom LB needed for interop test
  balancer/balancer.go
  balancer/rls/picker.go
  interop/xds/client/client.go
  interop/xds/custom_lb.go
  interop/xds/custom_lb_test.go
  stream.go
  test/balancer_test.go
Labels: Type: Testing

#6269 weightedroundrobin: fix test race accessing timeNow
  balancer/weightedroundrobin/balancer_test.go
Labels: Type: Testing

#6271 weightedroundrobin: fix duration format in lb config
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/balancer_test.go
  balancer/weightedroundrobin/config.go
  balancer/weightedroundrobin/internal/internal.go
  internal/serviceconfig/duration.go
  internal/serviceconfig/duration_test.go
Labels: Type: Bug

#6276 test: fix flaky TimeoutOnDeadServer test; some cleanups
  test/channelz_test.go
  test/clientconn_state_transition_test.go
  test/creds_test.go
  test/end2end_test.go
  test/goaway_test.go
  test/healthcheck_test.go
  test/pickfirst_test.go
  test/roundrobin_test.go
Labels: Type: Testing

#6272 xds: WRR in xDS
  test/xds/xds_client_custom_lb_test.go
  xds/internal/xdsclient/xdslbregistry/converter.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdslbregistry/converter.go
  xds/internal/xdslbregistry/converter_test.go
Labels: Type: Feature

#6277 interop: hold lock on server for OOB metrics updates; share 30s timeout
  interop/interop_test.sh
  interop/test_utils.go
Labels: Type: Testing

#6279 interop: fix interop_test.sh shutdown
  interop/interop_test.sh
Labels: Type: Testing

#6278 xds/internal/xdsclient: Split registry up and two separate packages
  xds/internal/xdsclient/xdslbregistry/converter/converter.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/xds.go
Labels: Type: Bug

#6284 cleanup: use new Duration type in base ServiceConfig
  service_config.go
  service_config_test.go
Labels: Type: Internal Cleanup

#6283 proto: update generated code to match grpc-proto changes
  interop/grpc_testing/messages.pb.go
Labels: Type: Meta

#6280 github: upgrade to v3 of checkout & setup-go
  .github/workflows/testing.yml
Labels: Type: Meta

#6287 xds/outlierdetection: forward metadata from child picker
  xds/internal/balancer/outlierdetection/balancer.go
Labels: Type: Bug

#6290 test/kokoro: Add custom_lb_test to the xds_k8s_lb job
  test/kokoro/xds_k8s_lb.sh
Labels: Type: Testing

#6230 authz: Stdout logger
  authz/audit/stdout/stdout_logger.go
  authz/audit/stdout/stdout_logger_test.go
Labels: Type: Feature, Type: Security

#6225 authz: Rbac engine audit logging
  authz/grpc_authz_server_interceptors.go
  authz/rbac_translator.go
  authz/rbac_translator_test.go
  internal/xds/rbac/converter.go
  internal/xds/rbac/converter_test.go
  internal/xds/rbac/rbac_engine.go
  internal/xds/rbac/rbac_engine_test.go
  xds/internal/httpfilter/rbac/rbac.go
Labels: Status: Requires Reporter Clarification, Type: Security

#6293 examples: add error_handling example; move errors to error_details
  examples/examples_test.sh
  examples/features/error_details/README.md
  examples/features/error_details/client/main.go
  examples/features/error_details/server/main.go
  examples/features/error_handling/README.md
  examples/features/error_handling/client/main.go
  examples/features/error_handling/server/main.go
Labels: Type: Documentation

#6263 grpc: support channel idleness
  balancer_conn_wrappers.go
  call.go
  clientconn.go
  clientconn_test.go
  dialoptions.go
  idle.go
  idle_test.go
  internal/grpcsync/callback_serializer.go
  internal/grpcsync/callback_serializer_test.go
  picker_wrapper.go
  resolver_conn_wrapper.go
  stream.go
  test/clientconn_state_transition_test.go
  test/idleness_test.go
Labels: Type: Feature

#6295 [interop client] let the interop client send additional arbitrary metadata, controlled by a flag
  interop/client/client.go
Labels: Type: Testing

#6307 authz: use pointer to to structpb.Struct instead of value
  authz/rbac_translator.go
Labels: Type: Testing

#6308 Remove interface check related to ResourceData
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/route_config_resource_type.go
Labels: Type: Internal Cleanup

#6306 grpc: support sticky TF in pick_first LB policy
  pickfirst.go
  test/pickfirst_test.go
Labels: Type: Feature

#6311 client: add support for pickfirst address shuffling from gRFC A62
  balancer_conn_wrappers.go
  internal/grpcrand/grpcrand.go
  pickfirst.go
  test/pickfirst_test.go
  test/resolver_update_test.go
Labels: Type: Feature

#6298 xds: support built-in Stdout audit logger type
  authz/audit/stdout/stdout_logger.go
  examples/go.mod
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  internal/xds/rbac/converter.go
  internal/xds/rbac/converter_test.go
  interop/observability/go.sum
  stats/opencensus/go.sum
Labels: Type: Security

#6296 stats/opencensus: Fix flaky test span
  stats/opencensus/e2e_test.go
  stats/opencensus/trace.go
Labels: Type: Testing

#6313 xds/internal/xdsclient: Add support for String Matcher Header Matcher in RDS
  internal/xds/matcher/matcher_header.go
  internal/xds/matcher/matcher_header_test.go
  xds/internal/xdsclient/xdsresource/matcher.go
  xds/internal/xdsclient/xdsresource/type_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Feature

#6300 alts: Fix flaky ALTS TestFullHandshake test.
  credentials/alts/alts_test.go
  credentials/alts/internal/testutil/testutil.go
Labels: Type: Testing

#6317 internal/envconfig: Set Custom LB Env Var to true by default
  internal/envconfig/xds.go
Labels: Type: Feature

#6328 client: disable channel idleness by default
  dialoptions.go
Labels: Type: Feature

#6331 client: fix Connect to handle channel idleness properly
  clientconn.go
  test/idleness_test.go
Labels: Type: Bug
