Repository grpc/grpc-go, pull requests merged in 2023-10, with the labels that each got.

#6662 status: fix/improve status handling
  internal/status/status.go
  internal/stubserver/stubserver.go
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  status/status_ext_test.go
  status/status_test.go
  test/balancer_test.go
Labels: Type: Behavior Change

#6673 Revert "status: fix/improve status handling (#6662)"
  internal/status/status.go
  internal/stubserver/stubserver.go
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  status/status_ext_test.go
  status/status_test.go
  test/balancer_test.go
Labels: Type: Bug

#6674 authz: Replace the gRFC pull request with the permanent link.
  authz/audit/audit_logger.go
Labels: Type: Internal Cleanup, no release notes

#6675 github: update actions/setup-go and actions/checkout
  .github/workflows/testing.yml
Labels: Type: Meta

#6680 xds: move virtual host matcher test to the xdsresource package
  xds/internal/resolver/watch_service_test.go
  xds/internal/xdsclient/xdsresource/matcher_test.go
Labels: Type: Testing

#6676 github: add code coverage with codecov.io
  .github/codecov.yml
  .github/workflows/coverage.yml
  README.md
Labels: Type: Meta

#6687 readme: fix badges
  README.md
Labels: Type: Documentation

#6678 client: add a test for NewSubConn / StateListener / cc.Close racing
  balancer_conn_wrappers_test.go
Labels: Type: Testing

#6688 Reapply "status: fix/improve status handling (#6662)" (#6673)
  internal/status/status.go
  internal/stubserver/stubserver.go
  internal/transport/handler_server.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
  status/status_ext_test.go
  test/balancer_test.go
Labels: Type: Feature

#6652 transport: Pass Header metadata to tap handle.
  internal/transport/http2_server.go
  tap/tap.go
  test/end2end_test.go
Labels: Type: Feature

#6697 Change version to 1.60.0-dev
  version.go
Labels: Type: Meta

#6689 xds/internal/server: stop using a fake xDS client in rds handler tests
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler_test.go
Labels: Type: Testing

#6698 deps: update dependencies for all modules
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#6666 randomWRR: remove lock for accessing WRR.items
  internal/wrr/random.go
  internal/wrr/wrr.go
Labels: Type: Internal Cleanup

#6703 server: prohibit more than MaxConcurrentStreams handlers from running at once
  benchmark/primitives/primitives_test.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  server.go
  server_ext_test.go
Labels: Type: Security

#6704 server: prohibit more than MaxConcurrentStreams handlers from running at once (#6703)
  benchmark/primitives/primitives_test.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  server.go
  server_ext_test.go
Labels: Type: Security

#6705 server: prohibit more than MaxConcurrentStreams handlers from running at once (#6703)
  benchmark/primitives/primitives_test.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  server.go
  server_ext_test.go
Labels: Type: Security

#6701 codes: update docstring to indicate expected usage
  codes/codes.go
Labels: Type: Documentation

#6711 Change version.go to 1.58.4-dev
  version.go
Labels: Type: Meta

#6708 server: prohibit more than MaxConcurrentStreams handlers from running at once (#6703)
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  server.go
  server_ext_test.go
Labels: Type: Security

#6712 Change version to 1.57.1
  version.go
Labels: Type: Meta

#6713 Update version.go to 1.56.3
  version.go
Labels: Type: Meta

#6714 Update version.go to 1.56.4-dev
  version.go
Labels: Type: Meta

#6709 Use Go cipher suites to find TLS suite string name
  credentials/tls.go
Labels: Type: Internal Cleanup

#6715 Change version to 1.57.2-dev
  version.go
Labels: Type: Meta

#6681 xds/resolver: move cluster specifier plugin tests to test only package
  resolver/resolver.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6682 xds/resolver: move service watching tests to resolver_test package
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/helpers_test.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6700 xds/internal/server: stop using a fake xDS client in listenerWrapper tests
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_client_ignore_resource_deletion_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_serving_mode_test.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler_test.go
  xds/server_test.go
Labels: Type: Testing

#6658 grpc: add a warning for unsupported codec
  server.go
Labels: Type: Internal Cleanup

#6692 experimental: add package and move recv buffer pool APIs into it
  benchmark/benchmain/main.go
  dialoptions.go
  experimental/experimental.go
  experimental/shared_buffer_pool_test.go
  internal/experimental.go
  server.go
Labels: Type: Feature

#6728 encoding: move codec tests out of top-level test package
  encoding/encoding_test.go
  test/codec_test.go
  test/end2end_test.go
Labels: Type: Testing

#6726 xds/internal/server: switch to generic xDS API for LDS/RDS
  xds/internal/server/listener_wrapper.go
  xds/internal/server/rds_handler.go
  xds/internal/server/rds_handler_test.go
Labels: Type: Internal Cleanup

#6725 xds/internal/resolver: final bit of test cleanup
  xds/internal/resolver/helpers_test.go
  xds/internal/resolver/internal/internal.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6721 crl provider: Delete deprecated CRL functionality
  security/advancedtls/crl_deprecated.go
  security/advancedtls/crl_deprecated_test.go
Labels: Type: Feature, Type: Security

#6679 resolver: Add an endpoint map type
  resolver/map.go
  resolver/map_test.go
Labels: Type: Feature

#6695 Change version to 1.59.0
  version.go
Labels: Type: Meta

#6737 server: fix semaphore release
  server.go
Labels: Type: Bug

#6735 balancer/rls: Fix RLS failure mode by treating response with no targets as an error
  balancer/rls/picker.go
  balancer/rls/picker_test.go
Labels: Type: Bug

#6699 alts: Reduce ALTS counter overflow length from 5 to 4.
  credentials/alts/internal/conn/aes128gcm.go
  credentials/alts/internal/conn/aes128gcmrekey.go
  credentials/alts/internal/conn/counter_test.go
Labels: Type: Security

#6746 Revert "alts: Reduce ALTS counter overflow length from 5 to 4."
  credentials/alts/internal/conn/aes128gcm.go
  credentials/alts/internal/conn/aes128gcmrekey.go
  credentials/alts/internal/conn/counter_test.go
Labels: Type: Security

#6716 grpc: Move some stats handler calls to gRPC layer, and add local address to peer.Peer
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  internal/xds/rbac/rbac_engine.go
  peer/peer.go
  server.go
Labels: Type: Internal Cleanup

#6749 envconfig: remove env vars for on-by-default features
  internal/envconfig/envconfig.go
  internal/envconfig/xds.go
  internal/grpcutil/compressor.go
  internal/grpcutil/compressor_test.go
  internal/testutils/xds/bootstrap/bootstrap.go
  pickfirst.go
  test/compressor_test.go
  test/pickfirst_test.go
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_custom_lb_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_server_rbac_test.go
  xds/googledirectpath/googlec2p.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/httpfilter/rbac/rbac.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/xdslbregistry/converter/converter.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/name.go
  xds/internal/xdsclient/xdsresource/name_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/server.go
Labels: Type: Internal Cleanup

#6750 grpc: Add a pointer of server to ctx passed into stats handler
  internal/internal.go
  internal/testutils/stubstatshandler.go
  server.go
  stats/stats_test.go
Labels: Type: Feature

#6743 metadata: Use strings.EqualFold for ValueFromIncomingContext
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Performance

#6670 crl provider: Static and FileWatcher provider implementations
  security/advancedtls/advancedtls_test.go
  security/advancedtls/crl.go
  security/advancedtls/crl_provider.go
  security/advancedtls/crl_provider_test.go
  security/advancedtls/crl_test.go
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/advancedtls/internal/testutils/testutils.go
  security/advancedtls/testdata/crl/README.md
  security/advancedtls/testdata/crl/provider_client_cert.key
  security/advancedtls/testdata/crl/provider_client_cert.pem
  security/advancedtls/testdata/crl/provider_client_trust_cert.pem
  security/advancedtls/testdata/crl/provider_client_trust_key.pem
  security/advancedtls/testdata/crl/provider_create.sh
  security/advancedtls/testdata/crl/provider_crl.cnf
  security/advancedtls/testdata/crl/provider_crl_empty.pem
  security/advancedtls/testdata/crl/provider_crl_server_revoked.pem
  security/advancedtls/testdata/crl/provider_extensions.conf
  security/advancedtls/testdata/crl/provider_server_cert.key
  security/advancedtls/testdata/crl/provider_server_cert.pem
  security/advancedtls/testdata/crl/provider_server_trust_cert.pem
  security/advancedtls/testdata/crl/provider_server_trust_key.pem
Labels: Type: Feature, Type: Security

#6489 grpc: Wait until resources finish cleaning up in Stop() and GracefulStop()
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  server.go
  test/gracefulstop_test.go
Labels: Type: Behavior Change
