Repository grpc/grpc-go, pull requests merged in 2023-11, with the labels that each got.

#6764 envconfig: re-add AdvertiseCompressors temporarily
  internal/envconfig/envconfig.go
  internal/grpcutil/compressor.go
Labels: Type: Feature

#6768 xds/resolver: extend test to re-add listener
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6762 stress: client logs total num of calls made
  stress/client/main.go
Labels: Type: Testing

#6769 stress: Move package under interop
  interop/stress/client/main.go
  interop/stress/grpc_testing/metrics.pb.go
  interop/stress/grpc_testing/metrics.proto
  interop/stress/grpc_testing/metrics_grpc.pb.go
  interop/stress/metrics_client/main.go
  vet.sh
Labels: Type: Internal Cleanup

#6754 resolver: manual resolver crashes if grpc.Dial isn't called before some methods
  resolver/manual/manual.go
  resolver/manual/manual_test.go
Labels: Type: Bug

#6720 github: modify codecov.yml
  .github/codecov.yml
Labels: Type: Meta

#6672 grpc: disable and document overrides of OS default TCP keepalive by Go
  benchmark/benchmain/main.go
  dialoptions.go
  internal/transport/http2_client.go
  internal/transport/proxy.go
  server.go
Labels: Type: Bug

#6773 interop/stress: Remove wait-for-ready
  interop/stress/client/main.go
Labels: Type: Testing

#6760 security/advancedtls: FileWatcher CRL provider initialization enhancement
  security/advancedtls/crl_provider.go
  security/advancedtls/crl_provider_test.go
Labels: Type: Behavior Change

#6775 Set top-level read-only workflow permissions
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/lock.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
Labels: Type: Meta

#6779 Add LocalAddr to http2Client.getPeer()
  internal/transport/http2_client.go
Labels: Type: Feature

#6780 vet: various cleanups
  balancer/rls/internal/adaptive/adaptive_test.go
  benchmark/benchmain/main.go
  test/end2end_test.go
  test/tools/go.mod
  test/tools/go.sum
  test/tools/tools.go
  vet.sh
  xds/internal/balancer/outlierdetection/callcounter_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
Labels: Type: Testing

#6784 resolver: remove ClientConn.NewServiceConfig
  resolver/resolver.go
  resolver_conn_wrapper.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
Labels: Type: API Change

#6794 Change version to 1.61.0-dev
  version.go
Labels: Type: Meta

#6771 reflection: don't serialize placeholders
  reflection/serverreflection.go
  reflection/serverreflection_test.go
Labels: Type: Bug

#6795 deps: update dependencies for all modules
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Meta

#6776 credentials: if not set, restrict to TLS v1.2+ and CipherSuites per RFC7540
  credentials/tls.go
  credentials/tls_ext_test.go
Labels: Type: Security

#6785 buffer & grpcsync: various cleanups and improvements
  internal/buffer/unbounded.go
  internal/buffer/unbounded_test.go
  internal/grpcsync/callback_serializer.go
Labels: Type: Internal Cleanup

#6797 credentials: if not set, restrict to TLS v1.2+ and CipherSuites per RFC7540
  credentials/tls.go
  credentials/tls_ext_test.go
Labels: Type: Security

#6798 client: simplify initialization and cleanup a bit
  balancer_conn_wrappers.go
  clientconn.go
Labels: Type: Internal Cleanup

#6796 xDS: Atomically read and write xDS security configuration client side
  credentials/xds/xds.go
  credentials/xds/xds_client_test.go
  credentials/xds/xds_server_test.go
  internal/credentials/xds/handshake_info.go
  internal/credentials/xds/handshake_info_test.go
  internal/internal.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/server/conn_wrapper.go
Labels: Type: Bug

#6801 client: rename balancer and resolver wrapper files to be consistent
  balancer_wrapper.go
  balancer_wrapper_test.go
  resolver_wrapper.go
Labels: Type: Internal Cleanup

#6800 client: remove deprecated WithServiceConfig DialOption
  clientconn.go
  dialoptions.go
  test/end2end_test.go
  test/service_config_deprecated_test.go
Labels: Type: API Change

#6802 client: further streamlining of Dial
  balancer_wrapper.go
  clientconn.go
  dialoptions.go
Labels: Type: Internal Cleanup

#6803 resolver_wrapper: remove serializerScheduleLocked; the lock is unnecessary
  resolver_wrapper.go
Labels: Type: Internal Cleanup

#6810 Mark old CRL APIs as deprecated
  security/advancedtls/crl.go
Labels: Type: Documentation, Type: Security

#6816 Fix for broken import
  security/advancedtls/crl_provider_test.go
Labels: Type: Bug

#6809 interop: Custom creds for stress test client
  interop/stress/client/main.go
Labels: Type: Testing

#6820 xds/internal/server: cleanup formatting directives in some logs
  xds/internal/server/listener_wrapper.go
Labels: Type: Internal Cleanup
