Repository grpc/grpc-go, pull requests merged in 2023-02, with the labels that each got.

#5886 cmd/protoc-gen-go-grpc: export consts for full method names
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/grpc_testing/test_grpc.pb.go
Labels: Type: Feature

#5923 stats/opencensus: Add OpenCensus metrics support
  codes/code_string.go
  internal/internal.go
  stats/opencensus/client_metrics.go
  stats/opencensus/e2e_test.go
  stats/opencensus/go.mod
  stats/opencensus/opencensus.go
  stats/opencensus/server_metrics.go
  stats/opencensus/stats.go
Labels: Type: Feature

#6009 github: update codeQL action to v2
  .github/workflows/codeql-analysis.yml
Labels: Type: Internal Cleanup

#6003 tests: reduce the degree of stress testing in long running tests
  clientconn_test.go
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup

#6008 metadata: slightly improve operateHeaders
  internal/transport/http2_server.go
  metadata/metadata.go
Labels: Type: Performance

#5935 internal/transport: fix severity of log when receiving a GOAWAY with error code ENHANCE_YOUR_CALM
  clientconn_test.go
  internal/transport/http2_client.go
  internal/transport/keepalive_test.go
  test/goaway_test.go
Labels: Type: Internal Cleanup

#6012 client: Revert dialWithGlobalOption
  clientconn.go
  default_dial_option_server_option_test.go
  dialoptions.go
  internal/internal.go
Labels: Type: Internal Cleanup

#6002 resolver: document handling UpdateState errors by resolvers
  resolver/resolver.go
Labels: Type: Documentation

#6016 client: Add dial option to disable global dial options
  clientconn.go
  default_dial_option_server_option_test.go
  dialoptions.go
  internal/internal.go
Labels: Type: Feature

#6020 github: update tests to use go version 1.20
  .github/workflows/testing.yml
Labels: Type: Meta

#5978 stats/opencensus: Add OpenCensus traces support
  stats/opencensus/e2e_test.go
  stats/opencensus/opencensus.go
  stats/opencensus/stats.go
  stats/opencensus/trace.go
Labels: Type: Feature

#6013 xds: remove support for v2 Transport API
  admin/test/utils.go
  internal/testutils/xds/bootstrap/bootstrap.go
  internal/testutils/xds/e2e/setup_management_server.go
  test/xds/xds_client_federation_test.go
  xds/csds/csds.go
  xds/csds/csds_e2e_test.go
  xds/csds/csds_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/test/e2e/controlplane.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/e2e_test/authority_test.go
  xds/internal/xdsclient/e2e_test/cds_watchers_test.go
  xds/internal/xdsclient/e2e_test/eds_watchers_test.go
  xds/internal/xdsclient/e2e_test/federation_watchers_test.go
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
  xds/internal/xdsclient/e2e_test/rds_watchers_test.go
  xds/internal/xdsclient/e2e_test/resource_update_test.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/singleton.go
  xds/internal/xdsclient/singleton_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/type.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
  xds/internal/xdsclient/xdsresource/version/version.go
  xds/server_test.go
Labels: Type: Feature

#6023 xds/internal/xdsclient: NACK empty clusters in aggregate clusters
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#6014 resolver: update Resolver.Scheme() docstring to mention requirement of lowercase scheme names
  clientconn.go
  resolver/resolver.go
  resolver_test.go
Labels: Type: Documentation

#6021 gcp/observability: Switch observability module to use new opencensus instrumentation code
  gcp/observability/go.mod
  gcp/observability/go.sum
  gcp/observability/opencensus.go
Labels: Type: Internal Cleanup

#6017 stats/opencensus: Add per call latency metric
  rpc_util.go
  stats/opencensus/client_metrics.go
  stats/opencensus/e2e_test.go
  stats/opencensus/opencensus.go
  stream.go
Labels: Type: Feature

#6026 gcp/observability: Register new views
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
Labels: Type: Internal Cleanup

#6030 stats/opencensus: Add top level call span
  stats/opencensus/e2e_test.go
  stats/opencensus/opencensus.go
  stats/opencensus/trace.go
Labels: Type: Feature

#5977 testing: add helpers to configure cluster specifier plugin type
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6055 xdsclient: minor cleanup in eds parsing
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
Labels: Type: Internal Cleanup

#5992 xdsclient/transport: reduce chattiness of logs
  internal/grpclog/prefixLogger.go
  xds/internal/xdsclient/transport/loadreport.go
  xds/internal/xdsclient/transport/transport.go
Labels: Type: Internal Cleanup

#6050 channelz: remove dependency on testing package
  channelz/service/func_linux.go
Labels: Type: Internal Cleanup

#6058 admin/test: split channelz imports
  admin/test/utils.go
Labels: Type: Internal Cleanup

#6059 internal/transport: Fix flaky keep alive test
  internal/transport/keepalive_test.go
Labels: Type: Bug

#6061 internal/transport: reduce running time of test from 5s to 1s
  internal/transport/keepalive_test.go
Labels: Type: Testing

#6062 test: move e2e health checking tests out of end2end_test.go
  test/end2end_test.go
  test/healthcheck_test.go
Labels: Type: Testing

#6001 metadata: fix validation issues
  internal/metadata/metadata.go
  internal/metadata/metadata_test.go
  stream.go
  test/metadata_test.go
Labels: Type: Bug

#6063 test: move compressor tests out of end2end_test.go
  test/compressor_test.go
  test/end2end_test.go
Labels: Type: Testing

#5996 xds/xdsclient: improve failure mode behavior (gRFC A57)
  xds/internal/internal.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/client_test.go
  xds/internal/xdsclient/e2e_test/cds_watchers_test.go
  xds/internal/xdsclient/e2e_test/eds_watchers_test.go
  xds/internal/xdsclient/e2e_test/lds_watchers_test.go
  xds/internal/xdsclient/e2e_test/rds_watchers_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
  xds/internal/xdsclient/xdsresource/errors.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/internal/xdsclient/xdsresource/route_config_resource_type.go
Labels: Type: Behavior Change

#6065 channelz: use protocmp.Transform() to compare protos
  channelz/service/service_sktopt_test.go
  channelz/service/service_test.go
Labels: Type: Testing

#6068 fakeserver: remove ADS and LRS v2 support
  xds/internal/testutils/fakeserver/server.go
Labels: Type: Testing
