Repository grpc/grpc-go, pull requests merged in 2023-06, with the labels that each got.

#6332 [PSM interop] Don't fail target if sub-target already failed
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
Labels: Type: Testing

#6343 xds: enable RLS in xDS by default
  internal/envconfig/xds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Feature

#6304 authz: End2End test for AuditLogger
  authz/audit/audit_logging_test.go
  testdata/x509/client_with_spiffe_cert.pem
  testdata/x509/client_with_spiffe_key.pem
  testdata/x509/client_with_spiffe_openssl.cnf
  testdata/x509/create.sh
Labels: Type: Testing

#6346 Change version to 1.57.0-dev
  version.go
Labels: Type: Meta

#6319 deps: google.golang.org/genproto to latest in all modules
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Dependencies

#6299 benchmark: Add sleepBetweenRPCs and connections parameters
  benchmark/benchmain/main.go
  benchmark/benchmark.go
  benchmark/stats/stats.go
Labels: Status: Requires Reporter Clarification, Type: Testing

#6351 xds/ringhash: cache connectivity state of subchannels inside picker
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#6358 weightedroundrobin: prefer application_utilization to cpu_utilization
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/balancer_test.go
Labels: Type: Feature

#6360 weightedroundrobin: cherry-pick 2 commits from master
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/balancer_test.go
  examples/go.mod
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  orca/call_metrics_test.go
  orca/orca_test.go
  orca/producer_test.go
  orca/server_metrics.go
  orca/server_metrics_test.go
  orca/service_test.go
  stats/opencensus/go.sum
Labels: Type: Feature

#6267 alts: Read max number of concurrent ALTS handshakes from environment variable.
  credentials/alts/alts_test.go
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  internal/envconfig/envconfig.go
Labels: Type: Feature

#6356 grpclb: fix typo
  balancer/grpclb/grpclb_test.go
Labels: Type: Testing

#6349 protoc-gen-go-grpc: Update README.md file
  cmd/protoc-gen-go-grpc/README.md
Labels: Type: Documentation, Status: Requires Reporter Clarification

#6362 benchmark: fix package used to reference service to use grpc suffix instead of pb
  benchmark/benchmain/main.go
Labels: Type: Bug

#6365 Revert "client: encode the authority by default (#6318)"
  clientconn.go
  test/authority_test.go
Labels: Type: Bug

#6361 xds/outlierdetection: fix config handling
  internal/balancer/nop/nop.go
  test/xds/xds_client_outlier_detection_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/balancer/outlierdetection/config.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#6367 xds/outlierdetection: Cherry pick 1 commit from master.
  internal/balancer/nop/nop.go
  test/xds/xds_client_outlier_detection_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/balancer/outlierdetection/config.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#6329 reflection: expose both v1 and v1alpha reflection services
  reflection/adapt.go
  reflection/serverreflection.go
  reflection/serverreflection_test.go
Labels: Type: Feature

#6344 Change version to 1.56.0
  version.go
Labels: Type: Meta

#6372 stats/opencensus: Fix flaky metrics test
  stats/opencensus/e2e_test.go
Labels: Type: Bug

#6385 client: cherry-pick 1 commit from master
  clientconn.go
  test/subconn_test.go
Labels: Type: Bug

#6386 Update version.go to v1.56.1
  version.go
Labels: Type: Meta

#6387 Update version.go to v1.56.2-dev
  version.go
Labels: Type: Meta

#6388 clusterresolver: remove redundant tests
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/resource_resolver_test.go
Labels: Type: Testing

#6392 clusterresolver: move tests around to different files
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Labels: Type: Testing

#6390 [PSM interop] Don't fail target if sub-target already failed
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6405 [PSM interop] Don't fail target if sub-target already failed (v1.56.x backport)
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6391 xds: clusterresolver e2e test cleanup
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_client_custom_lb_test.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Labels: Type: Testing

#6395 clusterresolver: remove priority LB related tests
  xds/internal/balancer/clusterresolver/priority_test.go
  xds/internal/balancer/clusterresolver/testutil_test.go
  xds/internal/balancer/priority/balancer_test.go
Labels: Type: Testing

#6394 clusterresolver: switch a couple of tests to e2e style
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
Labels: Type: Testing

#6404 [PSM interop] Don't fail target if sub-target already failed (v1.47.x backport)
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6411 reflection: rename proto imports for disambiguation in import script
  reflection/adapt.go
  reflection/serverreflection.go
  reflection/serverreflection_test.go
Labels: Type: Internal Cleanup

#6321 server: with TLS, set TCP user timeout on the underlying raw connection (#5646)
  internal/transport/http2_server.go
  internal/transport/keepalive_test.go
  internal/transport/transport_test.go
Labels: Type: Bug

#6414 xds: switch EDS watch to new generic xdsClient API
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/type_eds.go
Labels: Type: Internal Cleanup

#6410 xds: Fail xDS Server Serve() if called after Stop() or GracefulStop()
  xds/server.go
  xds/server_test.go
Labels: Type: Bug

#6419 internal/xds/rbac: Add support for string matcher in RBAC header matching
  internal/xds/rbac/matchers.go
  internal/xds/rbac/rbac_engine_test.go
Labels: Type: Feature

#6377 xds: E2E Test for Audit Logging
  test/xds/xds_server_rbac_test.go
Labels: Type: Testing

#6425 xdsclient: indicate authority serverURI in authority + transport logs
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/logging.go
Labels: Type: Internal Cleanup

#6424 orca: remove useless log statement
  orca/orca.go
Labels: Type: Internal Cleanup

#6420 xds/internal/balancer/clusterimpl: Switch cluster impl child to graceful switch
  xds/internal/balancer/clusterimpl/clusterimpl.go
Labels: Type: Internal Cleanup

#6167 internal/grpcsync: Provide an internal-only pub-sub type API
  internal/grpcsync/pubsub.go
  internal/grpcsync/pubsub_test.go
Labels: Type: Feature

#6427 internal/grpcsync: refactor test
  internal/grpcsync/pubsub_test.go
Labels: Type: Internal Cleanup
