Repository grpc/grpc-go, pull requests merged in 2023-09, with the labels that each got.

#6598 grpc: Change server stream context handling
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  server.go
  stats/stats_test.go
Labels: Type: Internal Cleanup

#6602 balancer/leastrequest: Cache atomic load and also add concurrent rpc test
  balancer/leastrequest/balancer_test.go
  balancer/leastrequest/leastrequest.go
Labels: Type: Internal Cleanup

#6606 leastrequest: fix data race in leastrequest picker
  balancer/leastrequest/leastrequest.go
Labels: Type: Bug

#6607 balancer/leastrequest: Cache atomic load and also add concurrent rpc test
  balancer/leastrequest/balancer_test.go
  balancer/leastrequest/leastrequest.go
Labels: Type: Bug

#6609 xds: fix hash policy header to skip bin headers and use extra metadata
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/serviceconfig_test.go
Labels: Type: Bug

#6610 idle: decrement active call count for streaming RPCs only when the call completes
  call.go
  internal/idle/idle_e2e_test.go
  stream.go
Labels: Type: Bug

#6614 interop/xds: improve error message
  interop/xds/custom_lb_test.go
Labels: Type: Testing

#6616 health/grpc_health_v1: update pb.go
  health/grpc_health_v1/health_grpc.pb.go
Labels: Type: Dependencies

#6600 cdsbalancer: switch cluster watch to generic xDS client API
  xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cluster_handler.go
  xds/internal/balancer/cdsbalancer/cluster_watcher.go
Labels: Type: Internal Cleanup

#6620 grpc: ensure transports are closed when the channel enters IDLE
  clientconn.go
  internal/idle/idle_e2e_test.go
Labels: Type: Bug

#6628 idle: use LB policy close event as a proxy for channel idleness
  internal/idle/idle_e2e_test.go
Labels: Type: Testing

#6629 update version to 1.58.1
  version.go
Labels: Type: Meta

#6633 update version to 1.58.2-dev
  version.go
Labels: Type: Meta

#6638 resolver/manual: support restarts, required for channel idleness
  clientconn_test.go
  resolver/manual/manual.go
Labels: Type: Feature

#6634 grpclb: some minor cleanups
  balancer/grpclb/grpclb.go
  balancer/grpclb/grpclb_picker.go
  balancer/grpclb/grpclb_remote_balancer.go
  interop/observability/go.mod
Labels: Type: Internal Cleanup

#6621 xdsclient: completely remove the old WatchCluster API
  xds/internal/testutils/fakeclient/client.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
Labels: Type: Internal Cleanup

#6643 balancer/weightedroundrobin: fix ticker leak on update
  balancer/weightedroundrobin/balancer.go
Labels: Type: Bug

#6635 grpclb: teach the manual resolver to handle restarts
  balancer/grpclb/grpclb.go
  balancer/grpclb/grpclb_util.go
Labels: Type: Bug

#6617 Improve testutils.MarshalAny
  internal/testutils/marshal_any.go
  internal/testutils/xds/e2e/clientresources.go
  internal/xds/rbac/converter_test.go
  test/xds/xds_client_custom_lb_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_rbac_test.go
  xds/csds/csds_e2e_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/clusterspecifier/rls/rls_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Testing

#6653 interop/grpc_testing: regenerate pb.gos
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test_grpc.pb.go
Labels: Type: Testing

#6655 balancer/weightedroundrobin: fix ticker leak on update
  balancer/weightedroundrobin/balancer.go
Labels: Type: Bug

#6654 Change version to 1.58.2
  version.go
Labels: Type: Meta

#6574 attributes: print typed nil values instead of panic
  attributes/attributes.go
  attributes/attributes_test.go
  resolver_test.go
Labels: Type: Internal Cleanup

#6646 Fix: testing parameter in xds_client_custom_lb_test
  test/xds/xds_client_custom_lb_test.go
Labels: Type: Testing

#6657 xds/googledirectpath: fix google-c2p resolver test case involving bootstrap env config
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Testing

#6645 googlec2p: remove support for the experimental scheme
  xds/googledirectpath/googlec2p.go
Labels: Type: Internal Cleanup

#6647 balancer: add a warning for balancer names that contain upper case letters
  balancer/balancer.go
  xds/internal/balancer/clusterresolver/config_test.go
Labels: Type: Behavior Change

#6664 attributes: avoid the use of %#v formatting verb
  attributes/attributes.go
  attributes/attributes_test.go
Labels: Type: Testing

#6661 internal/backoff: add a helper to run a function with backoff
  internal/backoff/backoff.go
  orca/producer.go
  xds/internal/xdsclient/transport/loadreport.go
  xds/internal/xdsclient/transport/transport.go
Labels: Type: Internal Cleanup

#6663 test: move codec tests to a separate file
  test/codec_test.go
  test/end2end_test.go
Labels: Type: Testing

#6665 encoding: fix mention of DecompressedSize in docstring
  encoding/encoding.go
Labels: Type: Documentation

#6648 examples: add an example of flow control behavior
  examples/examples_test.sh
  examples/features/flow_control/README.md
  examples/features/flow_control/client/main.go
  examples/features/flow_control/server/main.go
Labels: Type: Documentation

#6575 interop: implement rpc-behavior for UnaryCall()
  interop/xds/custom_lb_test.go
  interop/xds/server/server.go
Labels: Type: Testing

#6659 internal/idle: add a test that invokes ClientConn methods concurrently
  clientconn.go
  internal/idle/idle_e2e_test.go
  internal/internal.go
Labels: Type: Testing
