Repository grpc/grpc-go, pull requests merged in 2023-12, with the labels that each got.

#6833 doc: fix link to the reflection protocol
  reflection/README.md
Labels: Type: Documentation

#6804 client: rework resolver and balancer wrappers to avoid deadlock
  balancer_wrapper.go
  balancer_wrapper_test.go
  clientconn.go
  internal/channelz/funcs.go
  internal/idle/idle.go
  internal/idle/idle_e2e_test.go
  internal/idle/idle_test.go
  internal/internal.go
  picker_wrapper.go
  resolver_balancer_ext_test.go
  resolver_wrapper.go
Labels: Type: Bug

#6752 grpc: optional interface to provide channel authority
  clientconn.go
  internal/resolver/unix/unix.go
  resolver/resolver.go
Labels: Type: Feature

#6815 [infra] Hash-pin GitHub Actions, keep them updated with dependabot
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/lock.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/testing.yml
Labels: Type: Meta

#6834 client: always enable TCP keepalives with OS defaults
  benchmark/benchmain/main.go
  dialoptions.go
  internal/tcp_keepalive.go
  internal/transport/http2_client.go
  internal/transport/proxy.go
  server.go
Labels: Type: Bug

#6838 Cherry-pick #6804 and dependencies to v1.60.x release branch
  balancer_wrapper.go
  balancer_wrapper_test.go
  clientconn.go
  dialoptions.go
  internal/buffer/unbounded.go
  internal/buffer/unbounded_test.go
  internal/channelz/funcs.go
  internal/grpcsync/callback_serializer.go
  internal/idle/idle.go
  internal/idle/idle_e2e_test.go
  internal/idle/idle_test.go
  internal/internal.go
  picker_wrapper.go
  resolver_balancer_ext_test.go
  resolver_conn_wrapper.go
  resolver_wrapper.go
  test/end2end_test.go
  test/service_config_deprecated_test.go
Labels: Type: Bug

#6729 xds/internal/resolver: switch to generic xDS API for LDS/RDS
  test/xds/xds_client_federation_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Internal Cleanup

#6792 Change version to 1.60.0
  version.go
Labels: Type: Meta

#6841 internal: use OS defaults for TCP keepalive params only on unix
  internal/tcp_keepalive_nonunix.go
  internal/tcp_keepalive_unix.go
Labels: Type: Bug

#6847 Cherry-pick #6841 to v1.60.x release branch
  internal/tcp_keepalive_nonunix.go
  internal/tcp_keepalive_unix.go
Labels: Type: Bug

#6793 Change version to 1.60.1-dev
  version.go
Labels: Type: Meta

#6824 security/advancedtls: fix test that relies on min TLS version
  security/advancedtls/advancedtls_test.go
Labels: Type: Testing, Type: Internal Cleanup

#6852 Forbid dependabot from performing major version bumps
  .github/dependabot.yml
Labels: Type: Dependencies

#6857 credentials/alts: update handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
Labels: Type: Dependencies

#6849 completely delete WatchListener and WatchRouteConfig APIs
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/resource_watcher.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/type_lds.go
  xds/internal/xdsclient/xdsresource/type_rds.go
Labels: Type: Internal Cleanup

#6856 grpc: eliminate panics in server worker implementation
  server.go
  server_ext_test.go
Labels: Type: Bug

#6851 alts: Record network latency and pass it to the handshaker service.
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
  credentials/alts/internal/testutil/testutil.go
Labels: Type: Feature

#6859 test/kokoro: Use the Kokoro shared install lib from the new repo
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6799 orca: use atomic pointer instead of mutex in server metrics recorder to improve performance
  orca/server_metrics.go
Labels: Type: Performance

#6860 interop/xds: Increase go log verbosity to 99 so that EDS is logged
  interop/xds/client/Dockerfile
  interop/xds/server/Dockerfile
Labels: Type: Testing

#6864 Cherry-pick #6856 to v1.60.x release branch
  server.go
  server_ext_test.go
Labels: Type: Bug

#6865 Update version.go to v1.60.1
  version.go
Labels: Type: Meta

#6866 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.60.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6867 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.59.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6868 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.58.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6869 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.57.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6870 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.56.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6871 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.55.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6872 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.54.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6873 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.53.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6874 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.52.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6875 test/kokoro: Use the Kokoro shared install lib from the new repo (v1.51.x backport)
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#6883 Update version.go to 1.60.2-dev
  version.go
Labels: Type: Meta

#6863 internal: use OS defaults for TCP keepalive params in Windows
  internal/tcp_keepalive_others.go
  internal/tcp_keepalive_windows.go
Labels: Type: Bug

#6884 alts: Queue ALTS handshakes once limit is reached rather than dropping.
  credentials/alts/alts_test.go
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Feature

#6885 reflection: rename non-regenerated pb.go files to not be called '.pb.go'
  reflection/grpc_testing_not_regenerate/README.md
  reflection/grpc_testing_not_regenerate/dynamic.go
  reflection/grpc_testing_not_regenerate/testv3.go
  vet.sh
Labels: Type: Testing

#6848 xds: don't fail channel/server startup when xds creds is specified, but bootstrap is missing certificate providers
  internal/testutils/xds/e2e/setup_certs.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_server_certificate_providers_test.go
  test/xds/xds_server_integration_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/server.go
  xds/server_test.go
Labels: Type: Bug

#6886 removing deprecated http closenotifier function
  internal/transport/handler_server_test.go
Labels: Type: Testing

#6903 Revert "alts: Queue ALTS handshakes once limit is reached rather than dropping."
  credentials/alts/alts_test.go
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Bug
