Repository grpc/grpc-go, pull requests merged in 2023-03, with the labels that each got.

#6064 cmd/protoc-gen-go-grpc: bump -version to 1.3.0 for release
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/main.go
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  profiling/proto/service.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  stress/grpc_testing/metrics.pb.go
  stress/grpc_testing/metrics_grpc.pb.go
  test/codec_perf/perf.pb.go
  test/grpc_testing/test.pb.go
  test/grpc_testing/test_grpc.pb.go
  vet.sh
Labels: Type: Meta

#6071 metadata: Lowercase appended metadata
  metadata/metadata.go
Labels: Type: Bug

#6052 clusterresolver: cleanup resource resolver implementation
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
Labels: Type: Internal Cleanup

#5920 examples: add an example to illustrate authorization (authz) support
  examples/examples_test.sh
  examples/features/authz/README.md
  examples/features/authz/client/main.go
  examples/features/authz/server/main.go
  examples/features/authz/token/token.go
Labels: Type: Documentation

#6022 gcp/observability: Disable logging and traces on channels to cloud ops backends
  gcp/observability/exporting.go
  gcp/observability/go.mod
  gcp/observability/logging.go
  gcp/observability/logging_test.go
  gcp/observability/opencensus.go
Labels: Type: Internal Cleanup

#6042 stats/opencensus: Add client api latency and upgrade go.mod
  gcp/observability/go.mod
  gcp/observability/go.sum
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
Labels: Type: Feature

#6073 xdsclient: move tests from `e2e_test` to `tests` directory
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
Labels: Type: Testing

#6066 ringhash: ensure addresses are consistenly hashed across updates
  xds/internal/balancer/ringhash/ring.go
Labels: Type: Bug

#6078 xdsclient: send Node proto only on first discovery request on ADS stream
  xds/internal/testutils/fakeserver/server.go
  xds/internal/testutils/resource_watcher.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_resource_test.go
Labels: Type: Feature

#6076 grpc: Log server trailers before writing status
  server.go
Labels: Type: Behavior Change

#6051 stats/opencensus: New uncompressed metrics and align with tracing spec
  rpc_util.go
  server.go
  stats/opencensus/client_metrics.go
  stats/opencensus/e2e_test.go
  stats/opencensus/server_metrics.go
  stats/opencensus/stats.go
  stats/opencensus/trace.go
  stats/stats.go
  stats/stats_test.go
  stream.go
Labels: Type: Feature

#5979 interop/observability: add GCP Observability Testing Client/Server
  interop/observability/Dockerfile
  interop/observability/build_docker.sh
  interop/observability/client/client.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/observability/run.sh
  interop/observability/server/server.go
Labels: Type: Testing

#6082 xds/resolver/test: use a non-blocking send instead of closing the channel
  xds/internal/resolver/xds_resolver_test.go
Labels: Type: Testing

#6086 xdsclient: handle race with watch timer handling
  xds/internal/xdsclient/authority.go
Labels: Type: Bug

#6098 transport: stop returning errors that are always nil
  internal/transport/controlbuf.go
Labels: Type: Internal Cleanup

#6093 Deflake the integration test.
  security/advancedtls/advancedtls_integration_test.go
Labels: Type: Testing, no release notes, fixit, Type: Security

#6085 xds: NACK route configuration if sum of weights of weighted clusters exceeds uint32_max
  xds/internal/xdsclient/xdsresource/unmarshal_rds.go
  xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Labels: Type: Behavior Change

#6103 testutils: add support for creating endpoint resources with options
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
Labels: Type: Testing

#6106 go.mod: upgrade golang.org/x/net to address CVE-2022-41723
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Meta

#6089 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Meta

#6102 tests: support LRS on the same port as ADS
  internal/testutils/xds/e2e/server.go
  internal/testutils/xds/fakeserver/server.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
Labels: Type: Testing

#6108 xdsclient/tests: fix flaky test NodeProtoSentOnlyInFirstRequest
  xds/internal/xdsclient/tests/misc_watchers_test.go
Labels: Type: Testing

#6111 interop/observability: Pass interop parameters to client/server as-is
  interop/observability/run.sh
Labels: Type: Testing

#6110 transport: stop always closing connections when loopy returns
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/http_util.go
Labels: Type: Bug

#6118 gcp/observability: Change logging schema and set queue size limit for logs and batching delay
  gcp/observability/exporting.go
  gcp/observability/logging.go
  gcp/observability/logging_test.go
Labels: Type: Feature

#6112 xds: make comparison of server configs in bootstrap more reliable
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/testutils/testutils.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
  xds/server_test.go
Labels: Type: Bug

#6105 gcp/observability: Add compressed metrics to observability module and synchronize View data with exporter
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
  stats/opencensus/server_metrics.go
Labels: Type: Feature

#6109 client: log last error on subchannel connectivity change
  clientconn.go
Labels: Type: Internal Cleanup

#6117 add benchmark test for FromIncomingContext and ValueFromIncomingContext
  metadata/metadata_test.go
Labels: Type: Testing

#6077 credentials/alts: defer ALTS stream creation until handshake time
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Bug

#6126 stats/opencensus: Add message prefix to metrics names
  gcp/observability/observability_test.go
  gcp/observability/opencensus.go
  stats/opencensus/client_metrics.go
  stats/opencensus/e2e_test.go
  stats/opencensus/server_metrics.go
Labels: Type: Internal Cleanup

#6031 status: handle wrapped errors
  status/status.go
  status/status_test.go
Labels: Type: Feature

#6122 observability: remove import replace directive and switch it to point to latest commit
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Dependencies

#6141 stats/opencensus: remove leading slash for per call metrics
  stats/opencensus/e2e_test.go
  stats/opencensus/opencensus.go
Labels: Type: Bug

#6121 examples: organize READMEs better
  examples/README.md
  examples/helloworld/README.md
Labels: Type: Documentation

#6129 Change version to 1.54.0
  version.go
Labels: Type: Meta

#6125 clusterresolver: push empty config to child policy upon removal of cluster resource
  xds/internal/balancer/clusterresolver/clusterresolver_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/clientimpl_watchers.go
Labels: Type: Bug

#6139 CONTRIBUTING.md: remove duplicated bullet point
  CONTRIBUTING.md
Labels: Type: Documentation

#6130 Change version to 1.54.1-dev
  version.go
Labels: Type: Meta

#6134 cdsbalancer: improve log messages
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Labels: Type: Internal Cleanup

#6148 Revert "credentials/alts: defer ALTS stream creation until handshake …
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Bug

#6149 examples: Add observability example
  examples/features/observability/README.md
  examples/features/observability/client/clientConfig.json
  examples/features/observability/client/main.go
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/features/observability/server/main.go
  examples/features/observability/server/serverConfig.json
Labels: Type: Documentation

#6151 xds: enable XDS federation by default
  internal/envconfig/xds.go
  xds/internal/xdsclient/xdsresource/name_test.go
Labels: Type: Behavior Change

#6150 status: FromError: return entire error message text for wrapped errors
  status/status.go
  status/status_test.go
Labels: Type: Feature

#6132 go.mod: update all dependencies after 1.54 branch cut
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  credentials/xds/xds.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  internal/testutils/xds/e2e/server.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stress/grpc_testing/metrics.pb.go
  test/codec_perf/perf.pb.go
  test/grpc_testing/test.pb.go
  test/tools/go.mod
  test/tools/go.sum
  test/xds/xds_client_ack_nack_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
Labels: Type: Meta

#6074 Use anypb.New instead of ptypes.MarshalAny
  channelz/service/func_linux.go
  channelz/service/service.go
Labels: Type: Internal Cleanup

#6155 gcp/observability: Set the opencensus_task label only for metrics, not tracing and logging
  gcp/observability/opencensus.go
Labels: Type: Internal Cleanup

#6156 stats/opencensus: Switch helper to return Span Context from context
  interop/observability/go.mod
  interop/observability/go.sum
  stats/opencensus/opencensus.go
Labels: Type: Bug

#6160 gcp/observability: Add isSampled bool to log entries
  gcp/observability/go.mod
  gcp/observability/go.sum
  gcp/observability/logging.go
  gcp/observability/logging_test.go
  gcp/observability/observability_test.go
  interop/observability/go.mod
  interop/observability/go.sum
Labels: Type: Internal Cleanup

#6162 examples/features/observability: Point o11y example to latest gcp/observability module
  examples/features/observability/go.mod
  examples/features/observability/go.sum
Labels: Type: Dependencies

#6153 internal/grpcsync: move CallbackSerializer from xdsclient/internal to here
  internal/grpcsync/callback_serializer.go
  internal/grpcsync/callback_serializer_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl.go
Labels: Type: Internal Cleanup
