Repository grpc/grpc-go, pull requests merged in 2024-04, with the labels that each got.

#7033 grpc: Export header list sizes in DialOption and ServerOption
  default_dial_option_server_option_test.go
  dialoptions.go
  server.go
Labels: Type: Feature

#7071 cmd/protoc-gen-go-grpc: replace usages of deprecated API
  cmd/protoc-gen-go-grpc/grpc.go
Labels: Type: Internal Cleanup

#7079 channelz: fix race accessing channelMap without lock
  internal/channelz/funcs.go
Labels: Type: Bug

#7080 cherry-pick: channelz: fix race accessing channelMap without lock (#7079)
  internal/channelz/funcs.go
Labels: Type: Bug

#7081 *: update http2 dependency
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Dependencies

#7082 *: update http2 dependency
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Dependencies

#7083 *: update http2 dependency
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#7084 *: update http2 dependency
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#7086 Change version to 1.62.2
  version.go
Labels: Type: Meta

#7088 Change version to 1.62.3-dev
  version.go
Labels: Type: Meta

#7087 Change version to 1.61.2
  version.go
Labels: Type: Meta

#7089 Change version to 1.61.3-dev
  version.go
Labels: Type: Meta

#7038 Fix: error message using correct keepalive config value
  internal/transport/http2_server.go
Labels: Status: Requires Reporter Clarification, Type: Bug

#7097 grpc: Deprecate WithBlock, WithReturnConnectionError, FailOnNonTempDialError
  clientconn.go
  dialoptions.go
Labels: Type: Documentation

#6962 resolver/dns: Add SetMinResolutionInterval Option
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/resolver/dns/internal/internal.go
  resolver/dns/dns_resolver.go
Labels: Type: Feature

#7059 deps: move from github.com/golang/protobuf to google.golang.org/protobuf/proto
  channelz/internal/protoconv/channel.go
  channelz/internal/protoconv/server.go
  channelz/internal/protoconv/socket.go
  channelz/internal/protoconv/sockopt_linux.go
  channelz/internal/protoconv/subchannel.go
  channelz/service/service_test.go
  credentials/credentials.go
  vet.sh
Labels: Type: Dependencies

#7098 pb.go: regenerate
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
Labels: Type: Dependencies

#7099 vet: split vet-proto from vet.sh
  .github/workflows/testing.yml
  CONTRIBUTING.md
  Makefile
  scripts/vet-common.sh
  scripts/vet-proto.sh
  scripts/vet.sh
Labels: Type: Meta

#7072 cmd/protoc-gen-go-grpc: add change detector test
  .github/workflows/testing.yml
  cmd/protoc-gen-go-grpc/README.md
  cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
  cmd/protoc-gen-go-grpc/testdata/golden.pb.go
  cmd/protoc-gen-go-grpc/testdata/golden.proto
  cmd/protoc-gen-go-grpc/testdata/golden_grpc.pb.go
  regenerate.sh
Labels: Type: Meta

#7101 channelz: pass parent pointer instead of parent ID to RegisterSubChannel
  channelz/service/service_test.go
  clientconn.go
  internal/channelz/funcs.go
  internal/transport/keepalive_test.go
  internal/transport/transport_test.go
  test/channelz_test.go
Labels: Type: Bug

#7103 v1.63.x: grpc: un-deprecate Dial and DialContext and cherry-pick #7101
  channelz/service/service_test.go
  clientconn.go
  internal/channelz/funcs.go
  internal/transport/keepalive_test.go
  internal/transport/transport_test.go
  test/channelz_test.go
Labels: Type: Documentation, Type: Bug

#7102 test/kokoro: Migrate PSM Interop to Artifact Registry
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#7076 Makefile: perfect PHONY
  Makefile
Labels: Type: Internal Cleanup

#7085 xds/internal/xdsclient: Process string metadata in CDS for com.google.csm.telemetry_labels
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature

#7120 xds: remove -v when running xds e2e tests
  xds/internal/test/e2e/run.sh
Labels: Type: Testing

#7121 stats: mark InPayload.Data and OutPayload.Data for deletion (experimental)
  stats/stats.go
Labels: Type: API Change

#7123 pb.go: regenerate
  channelz/grpc_channelz_v1/channelz.pb.go
Labels: Type: Dependencies

#7122 deps: remove dependency of github.com/golang/protobuf from main module
  codegen.sh
  examples/gotutorial.md
  go.mod
  reflection/adapt.go
  reflection/internal/internal.go
  reflection/serverreflection.go
  reflection/test/go.mod
  reflection/test/go.sum
  reflection/test/grpc_testing_not_regenerate/README.md
  reflection/test/grpc_testing_not_regenerate/dynamic.go
  reflection/test/grpc_testing_not_regenerate/dynamic.proto
  reflection/test/grpc_testing_not_regenerate/testv3.go
  reflection/test/grpc_testing_not_regenerate/testv3.proto
  reflection/test/serverreflection_test.go
  scripts/vet.sh
Labels: Type: Dependencies

#7116 xds: Process telemetry labels from CDS in xDS Balancers
  internal/stats/labels.go
  test/xds/xds_telemetry_labels_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/config.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/configbuilder.go
Labels: Type: Feature

#7133 chore: fix lint
  cmd/protoc-gen-go-grpc/testdata/golden.pb.go
  cmd/protoc-gen-go-grpc/testdata/golden.proto
  cmd/protoc-gen-go-grpc/testdata/golden_grpc.pb.go
  reflection/test/serverreflection_test.go
Labels: Type: Internal Cleanup

#7134 cmd/protoc-gen-go-grpc: reuse route_guide_grpc.pb.go as golden file
  cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
  cmd/protoc-gen-go-grpc/testdata/golden.pb.go
  cmd/protoc-gen-go-grpc/testdata/golden.proto
  cmd/protoc-gen-go-grpc/testdata/golden_grpc.pb.go
Labels: Type: Internal Cleanup

#7132 client: Drop two calls to `pretty.ToJSON` and move code outside of lock
  clientconn.go
Labels: Type: Performance

#7118 advancedtls: unexport parts of API not meant to be public
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
Labels: Type: Internal Cleanup

#6691 examples: Add custom load balancer example
  balancer/endpointsharding/endpointsharding.go
  balancer/endpointsharding/endpointsharding_test.go
  examples/examples_test.sh
  examples/features/customloadbalancer/README.md
  examples/features/customloadbalancer/client/customroundrobin/customroundrobin.go
  examples/features/customloadbalancer/client/main.go
  examples/features/customloadbalancer/server/main.go
  internal/balancer/gracefulswitch/config.go
  internal/balancer/gracefulswitch/gracefulswitch.go
  pickfirst.go
  test/pickfirst_test.go
Labels: Type: Documentation

#7015 Send GOAWAY to server on Client Transport Shutdown
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  test/goaway_test.go
Labels: Type: Bug

#7130 xds/internal/xdsclient/xdslbregistry: remove unused call to type url
  xds/internal/xdsclient/xdslbregistry/xdslbregistry.go
Labels: Type: Internal Cleanup

#7147 transport: misc cleanups
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup

#7148 transport: make nextID accessed inside t.mu only
  internal/transport/http2_client.go
Labels: Type: Bug

#7139 *: fix regenerate.sh
  channelz/internal/protoconv/sockopt_linux.go
  channelz/internal/protoconv/sockopt_nonlinux.go
  channelz/internal/protoconv/util.go
  reflection/test/grpc_testing_not_regenerate/dynamic.proto
  reflection/test/grpc_testing_not_regenerate/testv3.proto
  regenerate.sh
Labels: Type: Meta

#7149 advancedtls: Rename VType
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/examples/credential_reloading_from_files/client/main.go
  security/advancedtls/examples/credential_reloading_from_files/server/main.go
Labels: Type: Security

#7117 grpc: fix function names in comments
  default_dial_option_server_option_test.go
  dialoptions.go
Labels: Type: Documentation

#7153 stats/opencensus: Handle `PickerUpdated` to avoid "Received unexpected stats" error
  stats/opencensus/stats.go
Labels: Type: Bug

#7140 advancedtls: Rename custom verification function APIs
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/examples/credential_reloading_from_files/client/main.go
  security/advancedtls/examples/credential_reloading_from_files/server/main.go
Labels: Type: Internal Cleanup, Type: Security

#7157 xds/internal/xdsclient/xdsresource: Preallocate VirtualHost slice correctly
  xds/internal/xdsclient/xdsresource/filter_chain.go
Labels: Type: Bug

#7162 examples: fix the quickstart link in the routeguide example
  examples/gotutorial.md
Labels: Type: Documentation

#7166 stats/opentelemetry: Add OpenTelemetry instrumentation component
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7165 advancedtls: Add notes about required vs. optional for FileWatcherOptions
  security/advancedtls/crl_provider.go
Labels: Type: Internal Cleanup

#7151 advancedtls: Rename RevocationConfig
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/crl.go
  security/advancedtls/crl_provider.go
  security/advancedtls/crl_test.go
Labels: Type: Internal Cleanup, Type: Security
