Repository grpc/grpc-go, pull requests merged in 2024-06, with the labels that each got.

#7268 xds: unify xDS client creation APIs meant for testing
  internal/internal.go
  internal/testutils/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap.go
  test/xds/xds_server_test.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/server.go
  xds/server_ext_test.go
Labels: Type: Internal Cleanup

#7238 documentation: on server, use FromIncomingContext for retrieving context and `SetHeader`, `SetTrailer` to send metadata to client
  Documentation/grpc-metadata.md
  examples/features/metadata_interceptor/client/main.go
  examples/features/metadata_interceptor/server/main.go
Labels: Type: Documentation

#7308 Change version to 1.66.0-dev
  version.go
Labels: Type: Meta

#7262 dns: fix constant 30s backoff for re-resolution
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/resolver/dns/internal/internal.go
Labels: Type: Bug

#7305 vet: remove --quiet from git grep when output is expected
  scripts/vet.sh
Labels: Type: Meta

#7303 [advancedTLS] Removed deprecated APIs in advancedTLS
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
  security/advancedtls/examples/credential_reloading_from_files/client/main.go
  security/advancedtls/examples/credential_reloading_from_files/server/main.go
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
Labels: Type: API Change

#7299 xds: cleanup bootstrap processing functionality
  internal/testutils/xds/bootstrap/bootstrap.go
  internal/testutils/xds/e2e/setup_management_server.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  stats/opentelemetry/csm/pluginoption.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/config_test.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/server/conn_wrapper.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/testutils.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/clientimpl_dump.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/singleton.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/internal/internal.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
  xds/server.go
Labels: Type: Internal Cleanup

#7310 deps: update dependencies for all modules
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  interop/xds/go.mod
  interop/xds/go.sum
  reflection/test/go.mod
  reflection/test/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#7309 xds/internal/xdsclient: Emit unknown for CSM Labels if not present in CDS
  xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/internal.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#7064 scripts: improve regenerate.sh to use the correct proto compiler version
  doc.go
  scripts/install_protoc.sh
  scripts/regenerate.sh
  scripts/vet-proto.sh
Labels: Type: Meta

#7279 stats/opentelemetry: Add e2e testing for CSM Observability
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/internal/testutils/testutils.go
  stats/opentelemetry/opentelemetry.go
Labels: Type: Testing

#7316 stats/opentelemetry: Add e2e testing for CSM Observability (#7279)
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/internal/testutils/testutils.go
  stats/opentelemetry/opentelemetry.go
Labels: Type: Testing

#7317 xds/internal/xdsclient: Emit unknown for CSM Labels if not present in CDS (#7309)
  xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/internal.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#7302 examples: Add CSM Observability example
  examples/features/csm_observability/README.md
  examples/features/csm_observability/client/Dockerfile
  examples/features/csm_observability/client/main.go
  examples/features/csm_observability/server/Dockerfile
  examples/features/csm_observability/server/main.go
  examples/go.mod
  examples/go.sum
Labels: Type: Documentation

#7271 ringhash: port e2e tests from c-core
  internal/testutils/blocking_context_dialer.go
  internal/testutils/xds/e2e/clientresources.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Testing

#7320 stats/opentelemetry: Fix protobuf import
  stats/opentelemetry/e2e_test.go
Labels: Type: Internal Cleanup

#7324 fix testclient type in ringhash_balancer_test checkRPCSendOK
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Internal Cleanup

#7301 credentials/alts: fix defer in TestDial
  credentials/alts/internal/handshaker/service/service.go
  credentials/alts/internal/handshaker/service/service_test.go
Labels: Type: Bug

#7323 github: add cache-dependency-path to setup-go
  .github/workflows/testing.yml
Labels: Type: Meta

#7319 internal/transport: minor cleanup of controlBuffer code
  internal/transport/controlbuf.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
Labels: Type: Internal Cleanup

#7318 examples: Add CSM Observability example (#7302)
  examples/features/csm_observability/README.md
  examples/features/csm_observability/client/Dockerfile
  examples/features/csm_observability/client/main.go
  examples/features/csm_observability/server/Dockerfile
  examples/features/csm_observability/server/main.go
  examples/go.mod
  examples/go.sum
Labels: Type: Documentation

#7332 test: fix typo in pickfirst_test.go
  test/pickfirst_test.go
Labels: Type: Testing

#7337 github: use latest release of qemu emulator
  .github/workflows/testing.yml
Labels: Type: Meta

#7331 examples/features/retry: Improve docstring
  examples/features/retry/client/main.go
Labels: Type: Meta

#7338 golint fix: context.Context should be the first parameter of a function
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Internal Cleanup

#7340 go.mod: update go-control-plane dependency for xDS fallback
  examples/go.mod
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.sum
  interop/xds/go.mod
  interop/xds/go.sum
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
Labels: Type: Dependencies

#7336 grpc: Readd pick first name
  clientconn.go
Labels: Type: Bug

#7330 grpclog: remove Debugf method to avoid unnecessary evaluation
  internal/grpclog/prefixLogger.go
  internal/xds/bootstrap/bootstrap.go
  xds/internal/balancer/priority/balancer_priority.go
  xds/internal/balancer/ringhash/ring.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/transport/transport.go
Labels: Type: Internal Cleanup

#7284 MAINTAINERS.md: add new members and move ex-members to emeritus
  MAINTAINERS.md
Labels: Type: Meta

#7348 github: update codecov with token and fail_ci_if_error
  .github/workflows/coverage.yml
Labels: Type: Meta

#7345 doc: fix link to error_details example
  Documentation/rpc-errors.md
Labels: Type: Documentation

#7353 *: update deps
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Dependencies

#7352 *: update deps
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Meta

#7351 cmd/protoc-gen-go-grpc: enable edition 2023 support
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/main.go
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  examples/route_guide/routeguide/route_guide.proto
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  scripts/install_protoc.sh
  test/codec_perf/perf.pb.go
Labels: Type: Feature

#7355 metadata: make Stringer implementation consistent
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Internal Cleanup

#7357 xds: Add a test for incorrect load reporting when using pickfirst with servers in multiple localities
  internal/stubserver/stubserver.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
Labels: Type: Bug
