Repository grpc/grpc-go, pull requests merged in 2024-10, with the labels that each got.

#7683 Change version to 1.67.2-dev
  version.go
Labels: Type: Meta

#7687 Change version to 1.66.4-dev
  version.go
Labels: Type: Meta

#7689 Cherry pick #7664 into v1.65.x
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
Labels: Type: Bug

#7675 xds: Fix flaky test TestUnmarshalListener_WithUpdateValidatorFunc
  test/xds/xds_server_integration_test.go
Labels: Type: Testing, Area: Testing

#7697 Change version to 1.65.1
  version.go
Labels: Type: Meta

#7678 vet : add check for tabs in text files
  Documentation/benchmark.md
  scripts/vet.sh
Labels: Type: Testing, Area: Tooling

#7658 examples: improve package comments
  examples/features/authz/client/main.go
  examples/features/authz/server/main.go
  examples/features/cancellation/client/main.go
  examples/features/cancellation/server/main.go
  examples/features/compression/client/main.go
  examples/features/compression/server/main.go
  examples/features/deadline/client/main.go
  examples/features/deadline/server/main.go
  examples/features/debugging/client/main.go
  examples/features/debugging/server/main.go
  examples/features/encryption/ALTS/client/main.go
  examples/features/encryption/ALTS/server/main.go
  examples/features/encryption/TLS/client/main.go
  examples/features/encryption/TLS/server/main.go
  examples/features/error_details/client/main.go
  examples/features/error_details/server/main.go
  examples/features/error_handling/client/main.go
  examples/features/error_handling/server/main.go
  examples/features/flow_control/client/main.go
  examples/features/flow_control/server/main.go
  examples/features/health/client/main.go
  examples/features/health/server/main.go
  examples/features/interceptor/client/main.go
  examples/features/interceptor/server/main.go
  examples/features/keepalive/client/main.go
  examples/features/keepalive/server/main.go
  examples/features/load_balancing/client/main.go
  examples/features/load_balancing/server/main.go
  examples/features/metadata/client/main.go
  examples/features/metadata/server/main.go
  examples/features/metadata_interceptor/client/main.go
  examples/features/metadata_interceptor/server/main.go
  examples/features/multiplex/client/main.go
  examples/features/multiplex/server/main.go
  examples/features/name_resolving/client/main.go
  examples/features/name_resolving/server/main.go
  examples/features/observability/client/main.go
  examples/features/observability/server/main.go
  examples/features/orca/client/main.go
  examples/features/orca/server/main.go
  examples/features/reflection/server/main.go
  examples/features/retry/client/main.go
  examples/features/retry/server/main.go
Labels: Type: Documentation

#7645 vet: add check to ensure terminating newline
  Documentation/grpc-metadata.md
  examples/data/rbac/policy.json
  examples/features/name_resolving/README.md
  reflection/test/grpc_testing_not_regenerate/dynamic.proto
  scripts/vet.sh
  testdata/x509/client_with_spiffe_openssl.cnf
Labels: Type: Testing

#7703 Revert "protoc-gen-go-grpc: remove `use_generic_streams_experimental` flag (defaults to true) (#7654)
  cmd/protoc-gen-go-grpc/grpc.go
  cmd/protoc-gen-go-grpc/main.go
  cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
Labels: Type: Meta

#7699 Change version to 1.65.2-dev
  version.go
Labels: Type: Meta

#7692 xdsclient: invoke watch callback when new update matches cached one, but previous update was NACKed (1/N)
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
Labels: Type: Bug

#7693 xdsclient: switch more transport tests to e2e style (2/N)
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/tests/ads_stream_backoff_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Internal Cleanup

#7694 xdsclient: make load reporting tests e2e style (3/N)
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/tests/loadreport_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Testing

#7695 xds: misc test cleanup (4/N)
  internal/testutils/channel.go
  test/xds/xds_client_federation_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/server_test.go
Labels: Type: Testing

#7696 xdsclient: e2e style tests for ads stream restart (5/N)
  xds/internal/xdsclient/tests/ads_stream_restart_test.go
Labels: Type: Testing

#7662 transport: prevent deadlock in transport Close when GoAway write hangs
  internal/transport/http2_client.go
Labels: Type: Bug, Area: Testing

#7705 xds: address merge conflict gotcha and missed review comment from previous PRs
  xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go
  xds/internal/xdsclient/tests/ads_stream_restart_test.go
Labels: Type: Testing

#7680 xds: return all ServerConfig dial options together
  internal/xds/bootstrap/bootstrap.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Internal Cleanup

#7710 xdsclient: fix test build breakage
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Testing

#7712 revert xds: return all ServerConfig dial options together
  internal/xds/bootstrap/bootstrap.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Testing, Area: Testing

#7698 pickfirst: Move var for mocking the shuffle func from internal/internal to pickfirst/internal
  balancer/pickfirst/internal/internal.go
  balancer/pickfirst/pickfirst.go
  balancer/pickfirst/pickfirst_ext_test.go
  internal/internal.go
  test/balancer_switching_test.go
Labels: Type: Internal Cleanup

#7718 xds: return all ServerConfig dial options together
  internal/xds/bootstrap/bootstrap.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_test.go
Labels: Type: Internal Cleanup

#7720 xdsclient: deflake TestADS_ResourcesAreRequestedAfterStreamRestart
  xds/internal/xdsclient/tests/ads_stream_backoff_test.go
  xds/internal/xdsclient/tests/ads_stream_restart_test.go
Labels: Type: Testing

#7716 testutils: add couple of log statements to the restartable listener type
  internal/testutils/restartable_listener.go
Labels: Type: Testing

#7498 pickfirst: New pick first policy for dualstack
  .github/workflows/coverage.yml
  .github/workflows/testing.yml
  balancer/pickfirst/pickfirst.go
  balancer/pickfirst/pickfirst_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_test.go
  balancer/rls/balancer_test.go
  clientconn.go
  clientconn_test.go
  internal/balancergroup/balancergroup_test.go
  internal/envconfig/envconfig.go
  test/balancer_switching_test.go
  test/balancer_test.go
  test/clientconn_state_transition_test.go
  test/resolver_update_test.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: Feature

#7666 transport : wait for goroutines to exit before transport closes
  clientconn.go
  internal/transport/http2_client.go
  internal/transport/keepalive_test.go
  internal/transport/transport_test.go
Labels: Type: Bug

#7731 pickfirstleaf: minor simplification to reconcileSubConnsLocked method
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
Labels: Type: Internal Cleanup

#7740 stats/opentelemetry/csm: Get mesh_id local label from "CSM_MESH_ID" environment variable, rather than parsing from bootstrap file
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/csm/pluginoption.go
  stats/opentelemetry/csm/pluginoption_test.go
Labels: Type: Behavior Change

#7746 Change version to 1.69.0-dev
  version.go
Labels: Type: Meta

#7747 vet: Use go1.22 instead of go1.21 for tidy and staticcheck
  scripts/vet.sh
Labels: Type: Testing

#7700 clientconn: remove redundant check
  clientconn.go
Labels: Type: Internal Cleanup

#7734 transport: refactor `trInFlow.onData` to eliminate redundant logic
  internal/transport/flowcontrol.go
Labels: Type: Internal Cleanup

#7717 xdsclient: new Transport interface and LRS stream implementation
  xds/internal/xdsclient/internal/internal.go
  xds/internal/xdsclient/transport/grpctransport/grpctransport.go
  xds/internal/xdsclient/transport/grpctransport/grpctransport_ext_test.go
  xds/internal/xdsclient/transport/lrs/lrs_stream.go
  xds/internal/xdsclient/transport/transport_interface.go
Labels: Type: Internal Cleanup

#7721 xdsclient: new Transport interface and ADS stream implementation
  xds/internal/xdsclient/internal/internal.go
  xds/internal/xdsclient/transport/ads/ads_stream.go
  xds/internal/xdsclient/transport/grpctransport/grpctransport_ext_test.go
  xds/internal/xdsclient/transport/transport_interface.go
Labels: Type: Internal Cleanup

#7732 resolver: update ReportError() docstring
  resolver/resolver.go
Labels: Type: Documentation

#7755 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  reflection/test/go.mod
  reflection/test/go.sum
  scripts/revive.toml
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#7761 vet: Don't use GOROOT to set PATH if GOROOT is unset
  scripts/vet.sh
Labels: Type: Testing

#7724 status: Fix status incompatibility introduced by #6919 and move non-regeneratable proto code into /testdata
  go.mod
  go.sum
  internal/status/status.go
  interop/xds/go.sum
  reflection/test/go.mod
  reflection/test/go.sum
  reflection/test/serverreflection_test.go
  scripts/regenerate.sh
  scripts/vet.sh
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  stats/opencensus/go.sum
  stats/opentelemetry/go.sum
  status/status_ext_test.go
  testdata/grpc_testing_not_regenerated/README.md
  testdata/grpc_testing_not_regenerated/dynamic.go
  testdata/grpc_testing_not_regenerated/dynamic.proto
  testdata/grpc_testing_not_regenerated/simple.proto
  testdata/grpc_testing_not_regenerated/simple_message_v1.go
  testdata/grpc_testing_not_regenerated/testv3.go
  testdata/grpc_testing_not_regenerated/testv3.proto
Labels: Type: Bug

#7757 xdsclient: implementation of the xdsChannel
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/channel.go
  xds/internal/xdsclient/channel_test.go
  xds/internal/xdsclient/transport/ads/ads_stream.go
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/internal/xdsclient/xdsresource/route_config_resource_type.go
Labels: Type: Internal Cleanup

#7771 xds/resolver: add a way to specify the xDS client to use for testing purposes
  internal/internal.go
  xds/internal/resolver/xds_resolver.go
Labels: Type: Testing

#7702 mem: use slice capacity instead of length, to determine whether to pool buffers or directly allocate them
  mem/buffers.go
  mem/buffers_test.go
Labels: Type: Bug

#7776 clusterresolver: fix a comment in a test
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
Labels: Type: Testing

#7766 vet: add dependency checks
  .github/workflows/deps.yml
  scripts/gen-deps.sh
Labels: Type: Testing

#7774 xdsclient: make sending requests more deterministic
  xds/internal/xdsclient/transport/ads/ads_stream.go
Labels: Type: Bug

#7751 github: add Go 1.23 testing and make staticcheck work locally with go1.23
  .github/workflows/testing.yml
  scripts/vet.sh
Labels: Type: Testing

#7775 credentials: Support ALTSPerRPCCreds in DefaultCredentialsOptions
  credentials/google/google.go
  credentials/google/google_test.go
Labels: Type: Security

#7708 cleanup: switching to stubserver in tests instead of testservice implementation
  test/xds/xds_client_ignore_resource_deletion_test.go
  test/xds/xds_server_certificate_providers_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_serving_mode_test.go
  test/xds/xds_server_test.go
Labels: Type: Testing

#7759 stats/opentelemetry: Remove OpenTelemetry module and add RLS Metrics e2e tests
  balancer/rls/metrics_test.go
  examples/go.mod
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.sum
  interop/xds/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
Labels: Type: Testing

#7674 balancer/endpointsharding: Ignore empty endpoints
  balancer/endpointsharding/endpointsharding.go
  resolver/resolver.go
  resolver/resolver_test.go
Labels: Type: Feature

#7785 multiple: add verbosity checks to logs that use pretty.JSON
  balancer/rls/config.go
  balancer/rls/control_channel.go
  balancer/weightedtarget/weightedtarget.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Internal Cleanup

#7781 server: Only call FromIncomingContext with stats handlers
  server.go
Labels: Type: Performance, Area: Server

#7762 Disable buffer_pooling tests
  .github/workflows/testing.yml
Labels: Type: Testing

#7711 multiple: switch to math/rand/v2
  balancer/endpointsharding/endpointsharding.go
  balancer/grpclb/grpclb_picker.go
  balancer/leastrequest/leastrequest.go
  balancer/pickfirst/pickfirst.go
  balancer/rls/internal/adaptive/adaptive.go
  balancer/roundrobin/roundrobin.go
  balancer/weightedroundrobin/balancer.go
  benchmark/benchmain/main.go
  benchmark/benchmark.go
  benchmark/stats/curve.go
  benchmark/worker/benchmark_client.go
  examples/features/debugging/server/main.go
  examples/features/xds/server/main.go
  examples/route_guide/client/client.go
  internal/backoff/backoff.go
  internal/resolver/dns/dns_resolver.go
  internal/serviceconfig/duration_test.go
  internal/transport/http2_server.go
  internal/wrr/random.go
  internal/wrr/wrr_test.go
  interop/stress/client/main.go
  stream.go
  xds/googledirectpath/googlec2p.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/xdsclient/xdsresource/matcher.go
  xds/internal/xdsclient/xdsresource/matcher_test.go
Labels: Type: Internal Cleanup

#7784 ringhash: fix a couple of flakes in e2e style tests
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Testing

#7782 balancer/endpointsharding: Call ExitIdle() on child if child reports IDLE
  balancer/endpointsharding/endpointsharding.go
Labels: Type: Behavior Change

#7792 Cherry-pick #7702 to 1.68.x
  mem/buffers.go
  mem/buffers_test.go
Labels: Type: Bug
