Repository grpc/grpc-go, pull requests merged in 2024-05, with the labels that each got.

#7126 Add atollena to MAINTAINERS.md
  MAINTAINERS.md
Labels: Type: Meta

#7180 xds/internal: Replace calls to `Debugf` with `V(2)` checks and `Infof`
  xds/internal/balancer/priority/balancer.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
Labels: Type: Performance

#7178 *: fix typos
  balancer/endpointsharding/endpointsharding.go
  balancer/rls/picker_test.go
  balancer/weightedroundrobin/balancer_test.go
  clientconn.go
  credentials/credentials.go
  credentials/local/local.go
  gcp/observability/logging_test.go
  gcp/observability/opencensus.go
  internal/balancer/gracefulswitch/gracefulswitch_test.go
  internal/balancergroup/balancergroup_test.go
  internal/binarylog/method_logger.go
  internal/channelz/syscall_test.go
  internal/grpcsync/callback_serializer_test.go
  internal/resolver/dns/internal/internal.go
  internal/testutils/resolver.go
  internal/transport/handler_server_test.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  service_config.go
  stats/opencensus/e2e_test.go
  stats/stats_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_server_test.go
  xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/priority/balancer_test.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/load/store_test.go
  xds/internal/xdsclient/requests_counter.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
  xds/server_test.go
Labels: Type: Documentation

#7189 channelz: fix missing Target on SubChannel type
  clientconn.go
  test/channelz_test.go
Labels: Type: Bug

#7057 Add an optional implementation of streams using generics
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  cmd/protoc-gen-go-grpc/main.go
  cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
  regenerate.sh
  rpc_util.go
  stream_interfaces.go
Labels: Type: Feature

#7183 test: fix possible leaked goroutine in TestDetailedConnectionCloseErrorPropagatesToRpcError
  test/end2end_test.go
Labels: Type: Testing

#7182 xds: Move bootstrap config to internal/xds
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  internal/xds/bootstrap/logging.go
  internal/xds/bootstrap/template.go
  internal/xds/bootstrap/template_test.go
  internal/xds/bootstrap/tlscreds/bundle.go
  internal/xds/bootstrap/tlscreds/bundle_ext_test.go
  internal/xds/bootstrap/tlscreds/bundle_test.go
  xds/bootstrap/bootstrap_test.go
  xds/bootstrap/credentials.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/config.go
  xds/internal/balancer/clusterimpl/config_test.go
  xds/internal/balancer/clusterresolver/config.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/testutils/fakeclient/client.go
  xds/internal/testutils/testutils.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/clientimpl_loadreport.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/singleton.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/server.go
Labels: Type: Internal Cleanup

#7171 test/kokoro: simplify PSM Interop Kokoro buildscripts
  test/kokoro/psm-interop-build-go.sh
  test/kokoro/psm-interop-test-go.sh
  test/kokoro/psm-security.cfg
  test/kokoro/psm-security.sh
  test/kokoro/xds_k8s_lb.cfg
  test/kokoro/xds_k8s_lb.sh
  test/kokoro/xds_url_map.cfg
  test/kokoro/xds_url_map.sh
Labels: Type: Testing

#7173 advancedTLS: Rename {Min/Max}Version to {Min/Max}TLSVersion
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Internal Cleanup

#7179 advancedTLS: Swap to DenyUndetermined from AllowUndetermined in revocation settings
  security/advancedtls/advancedtls_test.go
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
Labels: Type: Internal Cleanup

#7202 advancedTLS: Combine `ClientOptions` and `ServerOptions` to just `Options`
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
  security/advancedtls/sni.go
Labels: Type: Internal Cleanup

#7137 peer and metadata: Implement the Stringer interface for Peer and Metadata
  metadata/metadata.go
  metadata/metadata_test.go
  peer/peer.go
  peer/peer_test.go
Labels: Type: Behavior Change

#7204 peer: remove change detector test
  peer/peer_test.go
Labels: Type: Testing

#7206 client: add user-friendly error message of LB policy update timed out
  picker_wrapper.go
Labels: Type: Feature

#7203 codec: remove option to suppress setting supported compressors in headers
  internal/envconfig/envconfig.go
  internal/grpcutil/compressor.go
Labels: Type: Behavior Change

#7207 advancedTLS: Rename get root certs related pieces
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Internal Cleanup

#7191 xds: store server config for LRS server in xdsresource.ClusterUpdate
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/clientimpl_authority.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
  xds/internal/xdsclient/xdsresource/type_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature

#7188 codes: replace %q to %d in error string when invalid code is an integer
  codes/codes.go
  codes/codes_test.go
Labels: Type: Bug

#7217 resolver/dns: Add docstring to SetMinResolutionInterval
  resolver/dns/dns_resolver.go
Labels: Type: Internal Cleanup

#7221 advancedTLS: Add in deprecated name for transitionary period
  security/advancedtls/advancedtls.go
Labels: Type: Internal Cleanup

#7220 Change version to 1.65.0-dev
  version.go
Labels: Type: Meta

#7213 advancedTLS: Documentation
  security/advancedtls/advancedtls.go
Labels: Type: Documentation

#7214 pickerwrapper: use atomic instead of locks
  balancer_wrapper.go
  picker_wrapper.go
Labels: Type: Performance

#7237 documentation: fix typo in anti-patterns.md
  Documentation/anti-patterns.md
Labels: Type: Documentation

#7239 advancedTLS: unset a deprecated field after copying it
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Bug

#7234 grpc: Add perTargetDialOption type and global list
  clientconn.go
  default_dial_option_server_option_test.go
  dialoptions.go
  internal/internal.go
Labels: Type: Feature

#7248 examples: update remaining uses of grpc.Dial to NewClient
  examples/features/customloadbalancer/client/main.go
  examples/features/health/README.md
  examples/features/observability/client/main.go
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/features/retry/README.md
  examples/go.mod
  examples/go.sum
  examples/gotutorial.md
  examples/helloworld/greeter_client/main.go
  examples/route_guide/client/client.go
  security/advancedtls/examples/go.mod
  security/advancedtls/go.mod
Labels: Type: Documentation

#7205 stats/opentelemetry: Add CSM Plugin Option
  .github/workflows/testing.yml
  stats/opentelemetry/csm/pluginoption.go
  stats/opentelemetry/csm/pluginoption_test.go
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  stats/opentelemetry/internal/pluginoption.go
  test/xds/xds_telemetry_labels_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature

#7184 credentials/tls: reject connections with ALPN disabled
  credentials/tls.go
  credentials/tls_ext_test.go
  internal/envconfig/envconfig.go
Labels: Type: Behavior Change

#7240 xds: change the DumpResources API to return proto message containing the resource dump
  xds/csds/csds.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/clientimpl_dump.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
Labels: Type: Feature

#7232 balancergroup: add a `ParseConfig` API and remove the `UpdateBuilder` API
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
  xds/internal/balancer/clustermanager/balancerstateaggregator.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/clustermanager/e2e_test/clustermanager_test.go
Labels: Type: Internal Cleanup

#7224 test: fix flaky test ClientSendsAGoAway
  test/goaway_test.go
Labels: Type: Bug

#7243 protoc-gen-go-grpc: copy service comment to interfaces
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  profiling/proto/service_grpc.pb.go
Labels: Type: Feature

#7255 grpc: Move Pick First Balancer to separate package
  balancer/grpclb/grpclb_config.go
  balancer/pickfirst/pickfirst.go
  balancer/rls/balancer_test.go
  balancer/rls/internal/test/e2e/rls_child_policy.go
  clientconn.go
  internal/balancergroup/balancergroup_test.go
  service_config.go
  test/balancer_switching_test.go
  test/balancer_test.go
  test/resolver_update_test.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/clustermanager/e2e_test/clustermanager_test.go
  xds/internal/xdsclient/xdslbregistry/converter/converter.go
Labels: Type: Internal Cleanup

#7181 advancedtls: populate verified chains when using custom buildVerifyFunc
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Security

#7263 test/kokoro: Add psm-csm build config
  test/kokoro/psm-csm.cfg
Labels: Type: Testing

#7256 stats/opentelemetry: CSM Observability client side component changes
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7250 *: end support for Go v1.20
  .github/workflows/testing.yml
  README.md
Labels: Type: Dependencies

#7273 advancedtls: use realistic ciphersuite in test
  security/advancedtls/advancedtls_test.go
Labels: Type: Testing

#7269 advancedtls: add CipherSuites to Options
  security/advancedtls/advancedtls.go
  security/advancedtls/advancedtls_test.go
Labels: Type: Feature

#7274 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  reflection/test/go.mod
  reflection/test/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Meta

#7264 stats/opentelemetry: CSM Observability server side component changes
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7277 stats/opentelemetry: Add CSM Observability API
  stats/opentelemetry/csm/observability.go
  stats/opentelemetry/csm/pluginoption.go
  stats/opentelemetry/internal/pluginoption.go
  stats/opentelemetry/opentelemetry.go
Labels: Type: Feature

#7278 stats: Various CSM Observability bug fixes
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
  test/xds/xds_telemetry_labels_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Bug

#7156 ringhash: fix normalizeWeights
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Feature

#7128 Fix close in use certificate providers after double `Close()` method call on wrapper object
  credentials/tls/certprovider/store.go
Labels: Type: Bug

#7283 grpcrand: delete all of grpcrand and call the rand package directly
  balancer/endpointsharding/endpointsharding.go
  balancer/grpclb/grpclb_picker.go
  balancer/leastrequest/balancer_test.go
  balancer/leastrequest/leastrequest.go
  balancer/pickfirst/pickfirst.go
  balancer/rls/internal/adaptive/adaptive.go
  balancer/roundrobin/roundrobin.go
  balancer/weightedroundrobin/balancer.go
  benchmark/worker/benchmark_client.go
  examples/features/debugging/server/main.go
  internal/backoff/backoff.go
  internal/grpcrand/grpcrand.go
  internal/grpcrand/grpcrand_go1.21.go
  internal/internal.go
  internal/resolver/dns/dns_resolver.go
  internal/serviceconfig/duration_test.go
  internal/transport/http2_server.go
  internal/wrr/random.go
  internal/wrr/wrr_test.go
  scripts/vet.sh
  stream.go
  test/pickfirst_test.go
  xds/googledirectpath/googlec2p.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/httpfilter/fault/fault.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/xdsclient/xdsresource/matcher.go
  xds/internal/xdsclient/xdsresource/matcher_test.go
Labels: Type: Internal Cleanup

#7281 security: remove security/authorization module
  security/authorization/engine/engine.go
  security/authorization/engine/engine_test.go
  security/authorization/engine/util.go
  security/authorization/engine/util_test.go
  security/authorization/go.mod
  security/authorization/go.sum
Labels: Type: Internal Cleanup

#7282 *: update deps
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  examples/features/metadata/server/main.go
  examples/features/xds/server/main.go
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/client/main.go
  reflection/test/go.mod
  reflection/test/go.sum
  scripts/vet.sh
  security/advancedtls/crl.go
  security/advancedtls/crl_test.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Meta

#7294 cmd/protoc-gen-go-grpc: update version for release
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/main.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Meta

#7280 interop/xds: Interop client and server changes for CSM Observability
  interop/xds/client/Dockerfile
  interop/xds/client/client.go
  interop/xds/go.mod
  interop/xds/go.sum
  interop/xds/server/Dockerfile
  interop/xds/server/server.go
  stats/opentelemetry/csm/observability.go
  stats/opentelemetry/csm/pluginoption.go
Labels: Type: Testing
