Repository grpc/grpc-go, pull requests merged in 2024-03, with the labels that each got.

#7018 cherry-pick #6997 to 1.62.x release branch (#6979)
  clientconn.go
  internal/testutils/xds/e2e/clientresources.go
  resolver/resolver.go
  resolver_wrapper.go
  test/xds/xds_client_federation_test.go
  xds/internal/resolver/helpers_test.go
  xds/internal/resolver/xds_resolver.go
Labels: Type: Bug

#7020 Change version to 1.62.1
  version.go
Labels: Type: Meta

#7022 Change version to 1.62.2-dev
  version.go
Labels: Type: Meta

#6917 DNS resolving with timeout
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/resolver/dns/fake_net_resolver_test.go
  resolver/dns/dns_resolver.go
Labels: Type: Bug

#7026 xdsclient: correct logic used to suppress empty ADS requests on new streams
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_resource_test.go
Labels: Type: Bug

#7028 Update github.com/golang/protobuf and google.golang.org/protobuf modules
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
Labels: Type: Meta

#7010 chore: expose `NewClient` method to end users
  clientconn.go
  clientconn_parsed_target_test.go
  credentials/google/google_test.go
  credentials/google/xds.go
  credentials/google/xds_test.go
  dialoptions.go
  internal/internal.go
  internal/xds/xds.go
  resolver/resolver.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
Labels: Type: Feature

#7029 grpc: clean up doc strings and some code around Dial vs NewClient
  clientconn.go
  clientconn_parsed_target_test.go
  dialoptions.go
Labels: Type: Documentation

#7036 chore: remove repetitive words
  balancer/leastrequest/balancer_test.go
  balancer/weightedroundrobin/scheduler.go
  clientconn.go
  examples/features/observability/client/main.go
  examples/features/observability/server/main.go
  test/authority_test.go
  test/xds/xds_client_outlier_detection_test.go
  xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
Labels: Type: Internal Cleanup

#7027 xds: add LRS named metrics support
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/xdsclient/transport/loadreport_test.go
Labels: Type: Feature

#6969 channelz: major cleanup / reorganization
  balancer/balancer.go
  balancer/grpclb/grpclb_remote_balancer.go
  balancer_wrapper.go
  channelz/service/func_linux.go
  channelz/service/service.go
  channelz/service/service_sktopt_test.go
  channelz/service/service_test.go
  channelz/service/util_sktopt_386_test.go
  channelz/service/util_sktopt_amd64_test.go
  clientconn.go
  dialoptions.go
  internal/balancergroup/balancergroup_test.go
  internal/channelz/channel.go
  internal/channelz/channelmap.go
  internal/channelz/funcs.go
  internal/channelz/id.go
  internal/channelz/logging.go
  internal/channelz/server.go
  internal/channelz/socket.go
  internal/channelz/subchannel.go
  internal/channelz/syscall_linux.go
  internal/channelz/syscall_nonlinux.go
  internal/channelz/syscall_test.go
  internal/channelz/trace.go
  internal/channelz/types.go
  internal/channelz/util_linux.go
  internal/channelz/util_nonlinux.go
  internal/idle/idle_e2e_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/keepalive_test.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  resolver_balancer_ext_test.go
  resolver_wrapper.go
  rpc_util.go
  server.go
  stream.go
  test/channelz_linux_test.go
  test/channelz_test.go
  test/clientconn_test.go
  test/healthcheck_test.go
  test/pickfirst_test.go
  test/roundrobin_test.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
Labels: Type: Internal Cleanup

#7042 channelz: re-add target and state
  clientconn.go
  internal/channelz/funcs.go
  test/channelz_test.go
Labels: Type: Bug

#7046 channelz: re-add state for subchannels
  clientconn.go
  test/channelz_test.go
Labels: Type: Bug

#7035 gracefulswitch: add ParseConfig and make UpdateClientConnState call SwitchTo if needed
  balancer/balancer.go
  balancer/rls/config_test.go
  balancer_wrapper.go
  clientconn.go
  internal/balancer/gracefulswitch/config.go
  internal/balancer/gracefulswitch/gracefulswitch.go
  pickfirst.go
  service_config.go
  service_config_test.go
  test/balancer_switching_test.go
  vet.sh
Labels: Type: Internal Cleanup

#7048 googlec2p: use xdstp style template for client LDS resource name
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Behavior Change

#7052 Change version to 1.64.0-dev
  version.go
Labels: Type: Meta

#7055 cmd/protoc-gen-go-grpc: don't emit const blocks for services with no methods
  cmd/protoc-gen-go-grpc/grpc.go
Labels: Type: Bug

#7062 channelz: add LocalAddr to listen sockets and test
  server.go
  test/channelz_test.go
Labels: Type: Bug

#7045 examples: Update features/encryption/README.md file
  examples/features/encryption/README.md
Labels: Type: Documentation

#7063 channelz: add LocalAddr to listen sockets and test (#7062)
  server.go
  test/channelz_test.go
Labels: Type: Bug

#7040 googlec2p: use the bootstrap parsing code to generate parsed bootstrap config instead of handcrafting it
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/client_new.go
Labels: Type: Internal Cleanup

#7061 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/observability/go.mod
  examples/features/observability/go.sum
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  security/authorization/go.mod
  security/authorization/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies
