Repository grpc/grpc-go, pull requests merged in 2024-08, with the labels that each got.

#7432 mem: introduce `mem` package to facilitate memory reuse
  internal/internal.go
  mem/buffer_pool.go
  mem/buffer_pool_test.go
  mem/buffer_slice.go
  mem/buffer_slice_test.go
  mem/buffers.go
  mem/buffers_test.go
Labels: Type: Feature

#7467 balancer/leastrequest: Add verbosity check around build log
  balancer/leastrequest/leastrequest.go
Labels: Type: Meta

#7472 tools: Add github.com/mgechev/revive
  scripts/vet.sh
  test/tools/go.mod
  test/tools/go.sum
  test/tools/tools.go
Labels: Type: Meta

#7482 mem: fix comment typo
  mem/buffer_pool.go
Labels: Type: Documentation

#7476 balancergroup: remove mentions of locality from comments
  internal/balancergroup/balancergroup.go
Labels: Type: Internal Cleanup

#7461 grpc: make client report `Internal` status when server response contains unsupported encoding
  rpc_util.go
  server.go
  stream.go
  test/compressor_test.go
Labels: Type: Bug

#7477 transport/grpchttp2: change types to include `mem` package
  internal/transport/grpchttp2/framer.go
Labels: Type: Internal Cleanup

#7485 transport/grpchttp2: revert #7477 usage of mem package
  internal/transport/grpchttp2/framer.go
Labels: Type: Internal Cleanup

#7394 transport/bufWriter: fast-fail on error returned from flushKeepBuffer()
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Bug

#7483 xds: env var protection for xds fallback
  internal/envconfig/envconfig.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
Labels: Type: Feature

#7488 internal/transport: Unlock mutex before panic
  internal/transport/handler_server.go
Labels: Type: Internal Cleanup

#7493 *.pb.go: regenerate protos
  channelz/grpc_channelz_v1/channelz.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
Labels: Type: Internal Cleanup

#7484 balancer/rls: Add picker metrics
  balancer/rls/balancer.go
  balancer/rls/picker.go
Labels: Type: Feature

#7466 balancer/weightedroundrobin: Add recording point for endpoint weight not yet usable and add metrics tests
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/balancer_test.go
  balancer/weightedroundrobin/metrics_test.go
  balancer/weightedroundrobin/scheduler.go
  internal/stats/metrics_recorder_list_test.go
  internal/testutils/stats/test_metrics_recorder.go
  internal/testutils/xds/e2e/setup/setup.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_client_custom_lb_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_integration_test.go
  test/xds/xds_client_outlier_detection_test.go
  test/xds/xds_client_retry_test.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_certificate_providers_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
  test/xds/xds_server_test.go
  test/xds/xds_telemetry_labels_test.go
Labels: Type: Testing

#7458 xds: implement ADS stream flow control mechanism
  internal/testutils/xds_bootsrap.go
  internal/xds/bootstrap/bootstrap.go
  xds/csds/csds_e2e_test.go
  xds/internal/balancer/cdsbalancer/cluster_watcher.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
  xds/internal/resolver/watch_service.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/rds_handler.go
  xds/internal/testutils/resource_watcher.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/internal/internal.go
  xds/internal/xdsclient/tests/ads_stream_flow_control_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/transport/loadreport_test.go
  xds/internal/xdsclient/transport/transport.go
  xds/internal/xdsclient/transport/transport_ack_nack_test.go
  xds/internal/xdsclient/transport/transport_backoff_test.go
  xds/internal/xdsclient/transport/transport_new_test.go
  xds/internal/xdsclient/transport/transport_resource_test.go
  xds/internal/xdsclient/transport/transport_test.go
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/internal/xdsclient/xdsresource/route_config_resource_type.go
Labels: Type: Feature

#7486 benchmark: wire in new gzip compressor
  benchmark/benchmain/main.go
Labels: Type: Testing

#7505 grpc: fix a bug introduced in #7461
  stream.go
Labels: Type: Bug

#7453 transport/grpchttp2: add http2.Framer bridge
  internal/transport/grpchttp2/framer.go
  internal/transport/grpchttp2/http2bridge.go
  internal/transport/grpchttp2/http2bridge_test.go
Labels: Type: Feature

#7506 latency: don't wrap when all the latencies are zero
  benchmark/latency/latency.go
Labels: Type: Performance

#7504 .*: fix comments
  server.go
  stream.go
Labels: Type: Documentation

#7495 balancer/rls: Add cache metrics
  balancer/rls/balancer.go
  balancer/rls/cache.go
  balancer/rls/cache_test.go
  internal/testutils/stats/test_metrics_recorder.go
Labels: Type: Feature

#7509 test/tools: update staticcheck version to latest
  examples/features/customloadbalancer/client/main.go
  internal/transport/transport_test.go
  test/bufconn/bufconn_test.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Testing

#7511 balancer/rls: Fix RLS Cache metrics
  balancer/rls/cache.go
Labels: Type: Bug

#7512 transport: change `*http2Client` to interface `ClientTransport`
  internal/transport/transport.go
Labels: Type: Internal Cleanup

#7502 csds: unskip e2e test
  xds/csds/csds_e2e_test.go
Labels: Type: Testing

#7412 rls: update picker synchronously on configuration update
  balancer/rls/balancer.go
  balancer/rls/balancer_test.go
Labels: Type: Bug

#7520 Change version to 1.67.0-dev
  version.go
Labels: Type: Meta

#7371 transport: add timeout for writing GOAWAY on http2Client.Close()
  internal/transport/http2_client.go
  internal/transport/transport_test.go
Labels: Type: Bug

#7522 rbac: fix usage of AuthInfo
  internal/xds/rbac/rbac_engine.go
Labels: Type: Bug

#7478 Use builtin min and max functions
  balancer/rls/internal/adaptive/lookback.go
  benchmark/stats/stats.go
  credentials/alts/internal/conn/record.go
  internal/channelz/channelmap.go
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  test/end2end_test.go
  xds/internal/balancer/outlierdetection/balancer.go
Labels: Type: Internal Cleanup

#7540 cherry-pick: transport: add timeout for writing GOAWAY on http2Client.Close() #7371
  internal/transport/http2_client.go
  internal/transport/transport_test.go
Labels: Type: Bug

#7469 doc: update keepalive ClientParameters doc about doubling the interval upon GOAWAY
  dialoptions.go
  keepalive/keepalive.go
Labels: Type: Documentation

#7364 ringhash: fix bug where ring hash can be stuck in transient failure despite having available endpoints
  internal/testutils/blocking_context_dialer.go
  internal/testutils/blocking_context_dialer_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#7537 bootstrap: add `String` method to ServerConfigs type
  internal/testutils/xds/e2e/bootstrap.go
  internal/xds/bootstrap/bootstrap.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_ignore_resource_deletion_test.go
  test/xds/xds_server_certificate_providers_test.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/server_test.go
Labels: Type: Internal Cleanup

#7356 Implement new Codec that uses `mem.BufferSlice` instead of `[]byte`
  .github/workflows/testing.yml
  benchmark/benchmain/main.go
  codec.go
  dialoptions.go
  encoding/encoding_v2.go
  encoding/proto/proto_v2.go
  experimental/experimental.go
  experimental/shared_buffer_pool_test.go
  gcp/observability/logging_test.go
  internal/experimental.go
  internal/grpctest/grpctest.go
  internal/internal.go
  internal/leakcheck/leakcheck.go
  internal/leakcheck/leakcheck_enabled.go
  internal/leakcheck/leakcheck_test.go
  internal/transport/controlbuf.go
  internal/transport/grpchttp2/http2bridge.go
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  mem/buffer_pool.go
  mem/buffer_pool_test.go
  mem/buffer_slice.go
  mem/buffer_slice_test.go
  mem/buffers.go
  mem/buffers_test.go
  preloader.go
  rpc_util.go
  rpc_util_test.go
  server.go
  shared_buffer_pool.go
  stats/stats.go
  stats/stats_test.go
  stream.go
  test/context_canceled_test.go
  test/retry_test.go
Labels: Type: Performance

#7523 balancer: disallow producer streams until SubConn has reported READY
  balancer_wrapper.go
  clientconn.go
  producer_ext_test.go
  resolver_balancer_ext_test.go
Labels: Type: Bug

#7551 testing: Remove trailing whitespace in testing.yml
  .github/workflows/testing.yml
Labels: Type: Internal Cleanup

#7547 cherry-pick #7523 to v1.66.x branch
  balancer_wrapper.go
  clientconn.go
  producer_ext_test.go
  resolver_balancer_ext_test.go
Labels: Type: Bug

#7528 Fix revive identified linter issues: var-declaration, indent-error-flow, increment-decrement, superfluous-else
  cmd/protoc-gen-go-grpc/grpc.go
  examples/features/flow_control/client/main.go
  examples/features/flow_control/server/main.go
  internal/channelz/funcs.go
  internal/internal.go
  internal/transport/http2_client.go
  internal/transport/http_util.go
  profiling/cmd/remote.go
  stats/opentelemetry/internal/testutils/testutils.go
Labels: Type: Internal Cleanup

#7546 cherry-pick #7356 to v1.66.x branch
  .github/workflows/testing.yml
  benchmark/benchmain/main.go
  codec.go
  dialoptions.go
  encoding/encoding_v2.go
  encoding/proto/proto_v2.go
  experimental/experimental.go
  experimental/shared_buffer_pool_test.go
  gcp/observability/logging_test.go
  internal/experimental.go
  internal/grpctest/grpctest.go
  internal/internal.go
  internal/leakcheck/leakcheck.go
  internal/leakcheck/leakcheck_enabled.go
  internal/leakcheck/leakcheck_test.go
  internal/transport/controlbuf.go
  internal/transport/grpchttp2/http2bridge.go
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport.go
  internal/transport/transport_test.go
  mem/buffer_pool.go
  mem/buffer_pool_test.go
  mem/buffer_slice.go
  mem/buffer_slice_test.go
  mem/buffers.go
  mem/buffers_test.go
  preloader.go
  rpc_util.go
  rpc_util_test.go
  server.go
  shared_buffer_pool.go
  stats/stats.go
  stats/stats_test.go
  stream.go
  test/context_canceled_test.go
  test/retry_test.go
Labels: Type: Performance

#7557 encoding: delete v1 proto codec and use one map for registry
  codec.go
  codec_test.go
  encoding/encoding.go
  encoding/encoding_test.go
  encoding/encoding_v2.go
  encoding/proto/proto.go
  encoding/proto/proto_benchmark_test.go
  encoding/proto/proto_test.go
  encoding/proto/proto_v2.go
Labels: Type: Bug

#7564 cherry-pick #7557 to v1.66.x branch
  codec.go
  codec_test.go
  encoding/encoding.go
  encoding/encoding_test.go
  encoding/encoding_v2.go
  encoding/proto/proto.go
  encoding/proto/proto_benchmark_test.go
  encoding/proto/proto_test.go
  encoding/proto/proto_v2.go
Labels: Type: Bug

#7559 xds/xdsclient: Fix flaky test TestLRSClient
  xds/internal/xdsclient/loadreport_test.go
Labels: Type: Testing

#7554 .*: Use `strings.ReplaceAll(.....)`
  internal/googlecloud/googlecloud.go
  internal/xds/bootstrap/template.go
  resolver_balancer_ext_test.go
  stats/opencensus/opencensus.go
  stats/opencensus/trace.go
  xds/server_test.go
Labels: Type: Internal Cleanup

#7529 balancer/wrr: prefer calling Equal() method of time.Time
  balancer/weightedroundrobin/balancer.go
  benchmark/latency/latency.go
  test/config_selector_test.go
Labels: Type: Internal Cleanup

#7560 grpc: Fix flaky picker_wrapper tests
  picker_wrapper_test.go
Labels: Type: Testing

#7544 xdsclient: Populate total_issued_requests count in LRS load report
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/xdsclient/load/store.go
  xds/internal/xdsclient/load/store_test.go
  xds/internal/xdsclient/transport/loadreport.go
  xds/internal/xdsclient/transport/loadreport_test.go
Labels: Type: Feature

#7565 cherry-pick #7544 to v1.66.x branch
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/xdsclient/load/store.go
  xds/internal/xdsclient/load/store_test.go
  xds/internal/xdsclient/transport/loadreport.go
  xds/internal/xdsclient/transport/loadreport_test.go
Labels: Type: Feature

#7474 examples/advancedtls: example code for different security configurations for grpc-go using `advancedtls`
  examples/examples_test.sh
  examples/features/advancedtls/README.md
  examples/features/advancedtls/client/main.go
  examples/features/advancedtls/creds/ca_cert.pem
  examples/features/advancedtls/creds/ca_key.pem
  examples/features/advancedtls/creds/client_cert.pem
  examples/features/advancedtls/creds/client_cert_revoked.pem
  examples/features/advancedtls/creds/client_key.pem
  examples/features/advancedtls/creds/crl/client_revoked.crl
  examples/features/advancedtls/creds/localhost-openssl.cnf
  examples/features/advancedtls/creds/openssl-ca.cnf
  examples/features/advancedtls/creds/server_cert.pem
  examples/features/advancedtls/creds/server_cert_revoked.pem
  examples/features/advancedtls/creds/server_key.pem
  examples/features/advancedtls/creds/server_revoked.crl
  examples/features/advancedtls/generate.sh
  examples/features/advancedtls/localhost-openssl.cnf
  examples/features/advancedtls/openssl-ca.cnf
  examples/features/advancedtls/server/main.go
  examples/go.mod
  examples/go.sum
Labels: Type: Documentation

#7518 Change version to 1.66.0
  version.go
Labels: Type: Meta

#7519 Change version to 1.66.1-dev
  version.go
Labels: Type: Meta

#7470 grpc: add docs for generic stream interfaces
  stream_interfaces.go
Labels: Type: Documentation

#7561 clusterresolver/e2e_test: Avoid making DNS requests
  resolver/manual/manual.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
Labels: Type: Testing

#7545 stats/otel: upgrade grpc version that contains the experimental/stats package
  examples/go.mod
  interop/xds/go.mod
  security/advancedtls/examples/go.mod
  security/advancedtls/go.mod
  stats/opentelemetry/go.mod
Labels: Type: Bug

#7571 grpc: fix regression by freeing request bufferslice after processing unary
  mem/buffer_slice.go
  server.go
Labels: Type: Bug

#7533 xds/clusterimpl: update UpdateClientConnState to handle updates synchronously
  xds/internal/balancer/clusterimpl/clusterimpl.go
Labels: Type: Internal Cleanup
