Repository grpc/grpc-go, pull requests merged in 2024-07, with the labels that each got.

#7374 metadata: remove String method
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Behavior Change

#7372 metadata: remove String method
  metadata/metadata.go
  metadata/metadata_test.go
Labels: Type: Behavior Change

#7375 *: update deps
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  reflection/test/go.mod
  reflection/test/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
Labels: Type: Dependencies

#7368 metadata: stabilize ValueFromIncomingContext
  metadata/metadata.go
Labels: Type: Feature

#7361 documentation: Update proxy docs to point to `WithContextDialer`
  Documentation/proxy.md
Labels: Type: Documentation

#7380 Change version to 1.63.3
  version.go
Labels: Type: Meta

#7347 xds: add support for multiple xDS clients, for fallback
  internal/testutils/xds/e2e/logging.go
  internal/xds/bootstrap/bootstrap.go
  xds/csds/csds.go
  xds/csds/csds_e2e_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/resolver/internal/internal.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/rds_handler_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/client_refcounted_test.go
  xds/internal/xdsclient/clientimpl_dump.go
  xds/internal/xdsclient/clientimpl_loadreport.go
  xds/internal/xdsclient/loadreport_test.go
  xds/internal/xdsclient/singleton_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/helpers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/server.go
  xds/server_ext_test.go
  xds/server_test.go
Labels: Type: Feature

#7342 scripts: add linter rule for using context.WithTimeout on tests
  credentials/alts/internal/handshaker/handshaker_test.go
  gcp/observability/observability_test.go
  internal/binarylog/method_logger_test.go
  internal/xds/bootstrap/tlscreds/bundle_ext_test.go
  internal/xds/bootstrap/tlscreds/bundle_test.go
  internal/xds/rbac/rbac_engine_test.go
  metadata/metadata_test.go
  peer/peer_test.go
  picker_wrapper_test.go
  scripts/vet.sh
  server_test.go
  stats/opentelemetry/csm/observability_test.go
  test/gracefulstop_test.go
Labels: Type: Internal Cleanup

#7387 cmd/protoc-gen-go-grpc: default use_generic_streams_experimental to true
  cmd/protoc-gen-go-grpc/main.go
Labels: Type: Behavior Change

#7296 examples: Add OpenTelemetry example
  examples/features/opentelemetry/README.md
  examples/features/opentelemetry/client/main.go
  examples/features/opentelemetry/server/main.go
Labels: Type: Documentation

#7396 test/channelz: change channelz_test to use write data
  test/channelz_test.go
  test/rawConnWrapper.go
Labels: Type: Internal Cleanup

#7390 grpc: hold ac.mu while calling resetTransport to prevent concurrent connection attempts
  clientconn.go
Labels: Type: Bug

#7378 xds: use locality from the connected address for load reporting
  balancer/balancer.go
  balancer_wrapper.go
  clientconn.go
  internal/internal.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/clusterimpl.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/internal.go
Labels: P1, Type: Bug

#7401 xds: make fallback bootstrap configuration per-process
  internal/testutils/xds/e2e/bootstrap.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  stats/opentelemetry/csm/pluginoption.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_ignore_resource_deletion_test.go
  test/xds/xds_server_certificate_providers_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/authority_test.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/server_test.go
Labels: Type: Feature

#7402 *.pb.go: regenerate
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
Labels: Type: Dependencies

#7405 xds: fix typos
  xds/bootstrap/credentials.go
  xds/csds/csds_e2e_test.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Internal Cleanup

#7392 protoc-gen-go-grpc: add period to end of generated comment
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Documentation

#7403 scripts: minor refactor to scripts
  scripts/common.sh
  scripts/install-protoc.sh
  scripts/install_protoc.sh
  scripts/regenerate.sh
  scripts/vet-proto.sh
  scripts/vet.sh
Labels: Type: Testing

#7349 experimental/stats: Add metrics registry
  experimental/stats/metricregistry.go
  experimental/stats/metricregistry_test.go
  experimental/stats/metrics.go
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7408 internal/grpcsync: support two ways to schedule a callback with the serializer
  balancer_wrapper.go
  internal/grpcsync/callback_serializer.go
  internal/grpcsync/callback_serializer_test.go
  internal/grpcsync/pubsub.go
  resolver_wrapper.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cluster_watcher.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/clientimpl_watchers.go
Labels: Type: Internal Cleanup

#7417 xds/balancer/priority: Unlock mutex before returning
  xds/internal/balancer/priority/balancer.go
Labels: Type: Bug

#7420 vet: remove trailing whitespace
  scripts/vet.sh
Labels: Type: Internal Cleanup

#7421 vet: fix option order when invoking grep
  scripts/vet.sh
Labels: Type: Internal Cleanup

#7334 ringhash: more e2e tests from c-core
  internal/testutils/blocking_context_dialer.go
  internal/testutils/blocking_context_dialer_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Testing

#7409 scripts: regenerate pbs with caching deps to a fixed tmp folder
  scripts/install-protoc.sh
  scripts/regenerate.sh
Labels: Type: Meta

#7410 stats/opentelemetry: Add usage of metrics registry
  experimental/stats/metricregistry.go
  internal/internal.go
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/metricsregistry_test.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7397 transport/grpcframer: create grpcframer package
  internal/transport/grpchttp2/errors.go
  internal/transport/grpchttp2/errors_test.go
  internal/transport/grpchttp2/framer.go
Labels: Type: Feature

#7411 xds: Fix flaky test Test/ServerSideXDS_WithValidAndInvalidSecurityConfiguration
  test/xds/xds_server_certificate_providers_test.go
Labels: Type: Testing

#7418 docs: fix and improve anti-patterns.md
  Documentation/anti-patterns.md
Labels: Type: Documentation

#7438 cmd/protoc-gen-go-grpc: test the embedded struct at registration time for proper usage
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/README.md
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  cmd/protoc-gen-go-grpc/grpc.go
  cmd/protoc-gen-go-grpc/unimpl_test.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Feature

#7434 stats: Add optional locality label in cluster_impl picker
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/csm/observability.go
  stats/opentelemetry/csm/observability_test.go
  test/xds/xds_telemetry_labels_test.go
  xds/internal/balancer/clusterimpl/picker.go
Labels: Type: Feature

#7426 scripts/vet: remove trailing spaces
  scripts/vet-proto.sh
  scripts/vet.sh
Labels: Type: Internal Cleanup

#7428 internal/stats: Add metrics recorder list and usage in ClientConn
  balancer/balancer.go
  balancer_wrapper.go
  clientconn.go
  experimental/stats/metricregistry.go
  experimental/stats/metricregistry_test.go
  internal/stats/metrics_recorder_list.go
  internal/stats/metrics_recorder_list_test.go
  internal/testutils/stats/test_metrics_recorder.go
  stats/opentelemetry/opentelemetry.go
Labels: Type: Feature

#7443 cmd/protoc-gen-go-grpc: update version for release
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/main.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Meta

#7439 balancer/weightedroundrobin: Add emissions of metrics through metrics registry
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/scheduler.go
  balancer/weightedtarget/weightedtarget.go
Labels: Type: Feature

#7451 cmd/protoc-gen-go-grpc: remove replace and skip test that requires it for now
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  cmd/protoc-gen-go-grpc/unimpl_test.go
Labels: Type: Bug

#7452 cmd/protoc-gen-go-grpc: update version to 1.5.1
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/main.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Meta

#7450 examples/retry: remove waitForReady from service config
  examples/features/retry/README.md
  examples/features/retry/client/main.go
  rpc_util.go
Labels: Type: Documentation

#7424 transport: Discard the buffer when empty after http connect handshake
  internal/transport/proxy.go
  internal/transport/proxy_test.go
Labels: Type: Performance

#7457 experimental/stats/metricregistry: Add comments on enum consts for Metrics Type
  experimental/stats/metricregistry.go
Labels: Type: Documentation

#7437 resolver_wrapper: add early return in addChannelzTraceEvent
  resolver_wrapper.go
Labels: Type: Performance

#7456 cmd/protoc-gen-go-grpc: fix typo pancis -> panics
  balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  channelz/grpc_channelz_v1/channelz_grpc.pb.go
  cmd/protoc-gen-go-grpc/grpc.go
  credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  examples/features/proto/echo/echo_grpc.pb.go
  examples/helloworld/helloworld/helloworld_grpc.pb.go
  examples/route_guide/routeguide/route_guide_grpc.pb.go
  health/grpc_health_v1/health_grpc.pb.go
  internal/proto/grpc_lookup_v1/rls_grpc.pb.go
  interop/grpc_testing/benchmark_service_grpc.pb.go
  interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
  interop/grpc_testing/test_grpc.pb.go
  interop/grpc_testing/worker_service_grpc.pb.go
  interop/stress/grpc_testing/metrics_grpc.pb.go
  profiling/proto/service_grpc.pb.go
  reflection/grpc_reflection_v1/reflection_grpc.pb.go
  reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  reflection/grpc_testing/test_grpc.pb.go
Labels: Type: Documentation

#7445 transport/grpchttp2: add doc to methods and values
  internal/transport/grpchttp2/errors.go
  internal/transport/grpchttp2/framer.go
Labels: Type: Internal Cleanup
