Repository grpc/grpc-go, pull requests merged in 2024-12, with the labels that each got.

#7874 stats/opentelemetry: Cleanup OpenTelemetry API's before stabilization
  experimental/stats/metricregistry.go
  experimental/stats/metrics.go
  internal/testutils/stats/test_metrics_recorder.go
  stats/metrics.go
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/example_test.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/server_metrics.go
Labels: Type: Feature

#7887 credentials/google: Add cloud-platform scope for ADC
  credentials/google/google.go
Labels: Type: Bug

#7890 scripts/gen-deps: filter out grpc modules
  scripts/common.sh
  scripts/gen-deps.sh
  scripts/vet.sh
Labels: Type: Testing

#7889 dns: Support link local IPv6 addresses
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
  channelz/service/service_test.go
  internal/credentials/xds/handshake_info_test.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
  internal/testutils/fakegrpclb/server.go
  internal/xds/rbac/matchers.go
  scripts/vet.sh
  security/advancedtls/crl_test.go
  test/local_creds_test.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
Labels: Type: Feature

#7872 pickfirst: Stop test servers without closing listeners
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Labels: Type: Testing

#7891 test: Split import paths for message and service generated code
  test/clientconn_state_transition_test.go
Labels: Type: Internal Cleanup

#7879 balancer/pickfirst: replace grpc.Dial with grpc.NewClient in tests
  balancer/pickfirst/pickfirst_ext_test.go
Labels: Type: Internal Cleanup

#7893 Change version to 1.67.2
  version.go
Labels: Type: Meta

#7894 Change version to 1.68.1
  version.go
Labels: Type: Meta

#7896 Change version to 1.67.3-dev
  version.go
Labels: Type: Meta

#7832 pickfirst: Register a health listener when used as a leaf policy
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Labels: Type: Feature, Area: Resolvers/Balancers

#7903 Change version to 1.70.0-dev
  version.go
Labels: Type: Meta

#7904 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#7905 serviceconfig: Return errors instead of skipping invalid retry policy config
  service_config.go
  service_config_test.go
Labels: Type: Behavior Change

#7899 test/kokoro: Add psm-fallback build config
  test/kokoro/psm-fallback.cfg
Labels: Type: Testing

#7865 examples/features/gracefulstop: add example to demonstrate server graceful stop
  examples/examples_test.sh
  examples/features/gracefulstop/README.md
  examples/features/gracefulstop/client/main.go
  examples/features/gracefulstop/server/main.go
Labels: Type: Documentation

#7910 internal/transport: replace hardcoded status codes with http constants
  internal/transport/http2_server.go
Labels: Type: Internal Cleanup, Area: Transport

#7921 examples/xds: Fix typo in README.md
  examples/features/xds/README.md
Labels: Type: Documentation, Area: xDS

#7900 health, grpc: Deliver health service updates through the health listener
  balancer_wrapper.go
  health/producer.go
  internal/internal.go
  test/healthcheck_test.go
Labels: Type: Feature, Area: Resolvers/Balancers

#7901 Change version to 1.69.0
  version.go
Labels: Type: Meta

#7902 Change version to 1.69.1-dev
  version.go
Labels: Type: Meta

#7927 Change version to 1.69.1
  version.go
Labels: Type: Meta

#7929 experimental/stats: re-add type aliases for migration
  experimental/stats/metrics.go
Labels: Type: Bug

#7924 xdsclient: stop caching xdsChannels for potential reuse, after all references are released
  internal/testutils/channel.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go
  xds/internal/xdsclient/tests/ads_stream_restart_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/fallback_test.go
  xds/internal/xdsclient/tests/helpers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
Labels: Type: Internal Cleanup

#7858 xds: Add support for multiple addresses per endpoint
  balancer/weightedroundrobin/weightedroundrobin.go
  internal/envconfig/xds.go
  internal/testutils/xds/e2e/clientresources.go
  stats/opentelemetry/e2e_test.go
  test/xds/xds_client_custom_lb_test.go
  test/xds/xds_client_priority_locality_test.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/clusterresolver.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_dns.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/wrrlocality/balancer.go
  xds/internal/internal.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/type_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Feature, Area: xDS

#7933 examples/features/csm_observability: Make CSM Observability example server listen on an IPV4 address
  examples/features/csm_observability/server/main.go
Labels: Type: Documentation

#7934 Cherry-pick #7933 into v1.69.x
  examples/features/csm_observability/server/main.go
Labels: Type: Bug, Area: Documentation

#7916 grpcs: update `WithContextDialer` documentation to include using passthrough resolver
  dialoptions.go
Labels: Type: Documentation

#7936 v1.68: remove opentelemetry module and pull into main module
  examples/go.mod
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.sum
  interop/xds/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
Labels: Type: Dependencies

#7935 v1.67: remove opentelemetry module and pull into main module
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  interop/xds/go.mod
  interop/xds/go.sum
  reflection/test/go.mod
  reflection/test/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  stats/opentelemetry/go.mod
  stats/opentelemetry/go.sum
Labels: Type: Dependencies

#7939 Update version to 1.67.3
  version.go
Labels: Type: Meta

#7940 Update version to 1.67.4-dev
  version.go
Labels: Type: Meta

#7928 Change version to 1.69.2-dev
  version.go
Labels: Type: Meta

#7942 Change version to 1.68.2
  version.go
Labels: Type: Meta

#7941 Cherry-pick #7929
  experimental/stats/metrics.go
Labels: Type: Meta

#7946 Change version to 1.68.3-dev
  version.go
Labels: Type: Meta

#7947 Change version to 1.69.2
  version.go
Labels: Type: Meta

#7925 test: switching to stubserver in tests instead of testservice
  test/balancer_test.go
Labels: Type: Testing

#7948 Change version to 1.69.3-dev
  version.go
Labels: Type: Meta

#7920 cleanup: replace dial with newclient
  balancer/grpclb/grpclb_test.go
  balancer/rls/picker_test.go
  resolver_balancer_ext_test.go
  test/creds_test.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#7956 deps: update crypto dependency to resolve CVE-2024-45337
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
Labels: Type: Dependencies

#7957 test: Workaround slow SRV lookups in flaking test
  test/creds_test.go
Labels: Type: Internal Cleanup, Area: Testing

#7949 envconfig: enable xDS client fallback by default
  internal/envconfig/envconfig.go
  internal/xds/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/tests/fallback_test.go
Labels: Type: Feature

#7938 test: Add a test for decompression exceeding max receive message size
  test/compressor_test.go
Labels: Type: Testing, Area: RPC Features

#7908 outlierdetection: Support health listener for ejection updates
  balancer/endpointsharding/endpointsharding.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
  balancer/weightedroundrobin/balancer.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/outlierdetection/balancer_test.go
  xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
  xds/internal/balancer/outlierdetection/subconn_wrapper.go
Labels: Type: Feature, Area: Resolvers/Balancers

#7857 internal/resolver: introduce a new delegating resolver to handle both target URI and proxy address resolution
  internal/proxyattributes/proxyattributes.go
  internal/proxyattributes/proxyattributes_test.go
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/resolver/delegatingresolver/delegatingresolver_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#7943 cleanup: replace dial with newclient
  balancer/rls/balancer_test.go
  internal/idle/idle_e2e_test.go
  orca/producer_test.go
  resolver/manual/manual_test.go
  test/authority_test.go
  test/roundrobin_test.go
Labels: Type: Internal Cleanup, Area: Testing

#7959 cleanup: Fix usages of non-constant format strings
  internal/testutils/blocking_context_dialer_test.go
  internal/transport/handler_server.go
  stream.go
  test/creds_test.go
  test/end2end_test.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/xdsclient/transport/ads/ads_stream.go
Labels: Type: Internal Cleanup, Area: Testing

#7965 rbac: add method name to :path in headers
  internal/xds/rbac/rbac_engine.go
  test/xds/xds_server_rbac_test.go
Labels: Type: Bug

#7945 examples/features/csm_observability: use helloworld client and server instead of echo client and server
  examples/features/csm_observability/client/main.go
  examples/features/csm_observability/server/main.go
Labels: Type: Documentation
