Repository grpc/grpc-go, pull requests merged in 2024-01, with the labels that each got.

#6757 xds: add support for mTLS Credentials in xDS bootstrap
  credentials/tls/certprovider/pemfile/builder.go
  internal/testutils/xds/e2e/setup_certs.go
  test/xds/xds_client_certificate_providers_test.go
  xds/bootstrap/bootstrap.go
  xds/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/bootstrap/bootstrap.go
  xds/internal/xdsclient/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/tlscreds/bundle.go
  xds/internal/xdsclient/tlscreds/bundle_ext_test.go
  xds/internal/xdsclient/tlscreds/bundle_test.go
Labels: Type: Feature

#6909 fix 'identitiy' typo in error message
  test/xds/xds_client_certificate_providers_test.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
Labels: Type: Internal Cleanup

#6911 vet: remove ignore of CloseNotifier
  vet.sh
Labels: Type: Internal Cleanup

#6842 grpc: skip compression of empty messages
  rpc_util.go
  test/compressor_test.go
Labels: Type: Performance

#6908 examples: Fixed the formatting in the Authentication README.md
  examples/features/authentication/README.md
Labels: Type: Internal Cleanup

#6916 deps: apply `make proto` changes
  binarylog/grpc_binarylog_v1/binarylog.pb.go
Labels: Type: Dependencies

#6891 internal/transport: convert `ConnectionError` to `Unavailable` status when writing headers
  internal/transport/http2_server.go
  internal/transport/transport_test.go
Labels: Type: Bug

#6906 alts: Forward-fix of ALTS queuing of handshake requests.
  credentials/alts/alts_test.go
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/handshaker/handshaker_test.go
Labels: Type: Feature, Type: Security

#6907 removing Roots deprecated Subjects field in tests
  credentials/tls/certprovider/pemfile/watcher_test.go
  credentials/tls/certprovider/store_test.go
  vet.sh
Labels: Type: Internal Cleanup

#6915 xds/server: fix RDS handling for non-inline route configs
  internal/internal.go
  internal/testutils/xds/e2e/clientresources.go
  server.go
  test/xds/xds_server_certificate_providers_test.go
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_serving_mode_test.go
  test/xds/xds_server_test.go
  xds/internal/server/conn_wrapper.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler.go
  xds/internal/server/rds_handler_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/filter_chain_test.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/server.go
  xds/server_test.go
  xds/xds.go
Labels: Type: Bug

#6922 server: block GracefulStop on method handlers and make blocking optional for Stop
  orca/producer_test.go
  server.go
  server_ext_test.go
Labels: Type: Bug

#6765 metadata: move FromOutgoingContextRaw() to internal
  internal/internal.go
  internal/transport/http2_client.go
  metadata/metadata.go
  stream.go
Labels: Status: Requires Reporter Clarification, Type: Internal Cleanup

#6931 alts: Extract AuthInfo after handshake in ALTS e2e test.
  credentials/alts/alts_test.go
Labels: Type: Internal Cleanup

#6930 transport: Remove redundant if in handleGoAway
  internal/transport/http2_client.go
Labels: Type: Internal Cleanup

#6933 test/xds: Use different import path for gRPC Messages
  test/xds/xds_server_test.go
Labels: Type: Meta

#6938 Change version to 1.62.0-dev
  version.go
Labels: Type: Meta

#6934 encoding/proto: make sure proto imports are renamed
  encoding/proto/proto_benchmark_test.go
  encoding/proto/proto_test.go
Labels: Type: Internal Cleanup

#6936 Change version to 1.61.0
  version.go
Labels: Type: Meta

#6937 Change version to 1.61.1-dev
  version.go
Labels: Type: Meta

#6946 internal/transport: Remove redundant if conditional in http2_server
  internal/transport/http2_server.go
Labels: Type: Internal Cleanup

#6949 xds/googlec2p: use xdstp names for LDS
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Behavior Change

#6827 interop: Replace context.Background() with passed ctx
  interop/client/client.go
  interop/http2/negative_http2_client.go
  interop/observability/client/client.go
  interop/stress/client/main.go
  interop/test_utils.go
  interop/xds_federation/client.go
Labels: Type: Testing
