Repository grpc/grpc-go, pull requests merged in 2025-05, with the labels that each got.

#8250 xds: generic lrs client for load reporting
  xds/internal/clients/lrsclient/load_store.go
  xds/internal/clients/lrsclient/load_store_test.go
  xds/internal/clients/lrsclient/loadreport_test.go
  xds/internal/clients/lrsclient/logging.go
  xds/internal/clients/lrsclient/lrs_stream.go
  xds/internal/clients/lrsclient/lrsclient.go
Labels: Type: Feature, Area: xDS

#8272 otel: Test streaming rpc sequence numbers
  stats/opentelemetry/e2e_test.go
Labels: Type: Testing, Area: Testing

#8284 alts: Add plumbing for the bound access token field in the ALTS StartClient request.
  credentials/alts/alts.go
  credentials/alts/alts_test.go
  credentials/alts/internal/handshaker/handshaker.go
  credentials/alts/internal/testutil/testutil.go
Labels: Type: Feature, Area: Auth

#8287 xds_test: Wait for server to start serving in RBAC test
  test/xds/xds_server_integration_test.go
  test/xds/xds_server_rbac_test.go
Labels: Type: Testing

#8215 internal/delegatingresolver: avoid proxy if networktype of target address is not tcp
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/http2_client.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8296 cherry-pick #8215 to v1.72.x branch
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/http2_client.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8293 [alts] add keepalive params to the alts handshaker client dial option
  credentials/alts/internal/handshaker/service/service.go
  internal/envconfig/envconfig.go
Labels: Type: Bug, Area: Auth

#8297 weightedroundrobin: Remove nil embedded SubConn from endpointWeight
  balancer/weightedroundrobin/balancer.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8292 grpc: Update ClientStream.CloseSend docs
  stream.go
Labels: Type: Documentation

#8301 xds: modify generic clients grpctransport to accept optional custom grpc new client function
  xds/internal/clients/grpctransport/examples_test.go
  xds/internal/clients/grpctransport/grpc_transport.go
  xds/internal/clients/grpctransport/grpc_transport_ext_test.go
  xds/internal/clients/grpctransport/grpc_transport_test.go
  xds/internal/clients/lrsclient/loadreport_test.go
  xds/internal/clients/xdsclient/channel_test.go
  xds/internal/clients/xdsclient/test/authority_test.go
  xds/internal/clients/xdsclient/test/dump_test.go
  xds/internal/clients/xdsclient/test/lds_watchers_test.go
  xds/internal/clients/xdsclient/test/misc_watchers_test.go
  xds/internal/clients/xdsclient/xdsclient_test.go
Labels: Type: Feature, Area: xDS

#8302 resolver/delegatingresolver: wait for proxy resolver to be built in test
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8274 xds: add MetricsReporter for generic xds client
  xds/internal/clients/config.go
  xds/internal/clients/xdsclient/authority.go
  xds/internal/clients/xdsclient/metrics/metrics.go
  xds/internal/clients/xdsclient/test/helpers_test.go
  xds/internal/clients/xdsclient/test/metrics_test.go
  xds/internal/clients/xdsclient/xdsclient.go
  xds/internal/clients/xdsclient/xdsconfig.go
Labels: Type: Feature, Area: xDS

#8291 credentials/local: implement ValidateAuthority
  credentials/credentials_ext_test.go
  credentials/local/local.go
Labels: Type: Feature

#8155 health: Add List method to gRPC Health service
  health/server.go
  health/server_internal_test.go
Labels: Type: Feature, Area: Observability

#8300 Update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: Type: Meta

#8196 cleanup: replace dial with newclient
  Documentation/encoding.md
  Documentation/grpc-auth-support.md
  balancer/endpointsharding/endpointsharding_test.go
  credentials/insecure/insecure.go
  dialoptions.go
  internal/stats/metrics_recorder_list_test.go
  stats/stats_test.go
  test/channelz_test.go
  test/end2end_test.go
Labels: Type: Internal Cleanup

#8290 transport: Reject non-positive timeout values in server
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Bug, Area: Server

#8304 resolver/delegatingresolver: wait for proxy resolver build before update in tests
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8289 transport: Propagate status code on receiving RST_STREAM during message read
  internal/transport/http2_client.go
  internal/transport/transport_test.go
  test/transport_test.go
Labels: Type: Bug

#8308 grpcsync/event: Simplify synchronization
  internal/grpcsync/event.go
Labels: Type: Internal Cleanup

#8298 cherry-pick #8215, #8302 and #8304 to v1.71.x branch
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/http2_client.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8303 cherry-pick #8302 and #8304 to v1.72.x branch
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8309 leakcheck: Fix flaky test TestCheck
  internal/leakcheck/leakcheck_test.go
Labels: Type: Bug

#8317 Cherry-pick #8289 to v1.72.x
  internal/transport/http2_client.go
  internal/transport/transport_test.go
  test/transport_test.go
Labels: Type: Bug

#8312 transport: Prevent sending negative timeouts
  internal/transport/http2_client.go
  test/end2end_test.go
Labels: Type: Testing, Area: Testing

#8315 cleanup: remove unused constants in generic xdsclient
  xds/internal/clients/xdsclient/xdsclient.go
Labels: Type: Internal Cleanup

#8319 Change version to 1.72.1
  version.go
Labels: Type: Meta

#8318 grpc: update contributing.md
  CONTRIBUTING.md
Labels: Type: Internal Cleanup

#8316 rls: removing unused channel
  balancer/rls/control_channel.go
Labels: Type: Internal Cleanup, Area: Resolvers/Balancers

#8321 Change version to v1.71.2
  version.go
Labels: Type: Meta

#8326 Change version to v1.72.2-dev
  version.go
Labels: Type: Meta

#8325 Change version to v1.71.3-dev
  version.go
Labels: Type: Meta

#8307 xds: generic xds client ads stream tests
  xds/internal/clients/internal/testutils/channel.go
  xds/internal/clients/xdsclient/ads_stream.go
  xds/internal/clients/xdsclient/internal/internal.go
  xds/internal/clients/xdsclient/internal/xdsresource/ads_stream.go
  xds/internal/clients/xdsclient/test/ads_stream_ack_nack_test.go
  xds/internal/clients/xdsclient/test/ads_stream_backoff_test.go
  xds/internal/clients/xdsclient/test/ads_stream_flow_control_test.go
  xds/internal/clients/xdsclient/test/ads_stream_restart_test.go
  xds/internal/clients/xdsclient/test/ads_stream_watch_test.go
  xds/internal/clients/xdsclient/test/authority_test.go
  xds/internal/clients/xdsclient/test/lds_watchers_test.go
  xds/internal/clients/xdsclient/xdsclient.go
Labels: Type: Testing, Area: xDS

#8333 balancer/least_request : Fix panic while handling resolver errors
  balancer/leastrequest/leastrequest.go
  balancer/leastrequest/leastrequest_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8340 Cherry-pick #8333 to v1.71.x
  balancer/leastrequest/leastrequest.go
  balancer/leastrequest/leastrequest_test.go
Labels: Type: Bug

#8339 Cherry-pick #8333 to v1.72.x
  balancer/leastrequest/leastrequest.go
  balancer/leastrequest/leastrequest_test.go
Labels: Type: Bug

#8338 Cherry-pick #8333 to v1.73.x
  balancer/leastrequest/leastrequest.go
  balancer/leastrequest/leastrequest_test.go
Labels: Type: Bug

#8306 internal/transport: Wait for server goroutines to exit during shutdown in test
  internal/transport/transport_test.go
Labels: Type: Testing, Area: Testing

#8350 Rename PSM interop fallback test suite to light
  test/kokoro/psm-light.cfg
Labels: Type: Testing, Type: Internal Cleanup

#8329 delegatingresolver: avoid proxy for resolved addresses in NO_PROXY env
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/proxy_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8352 Cherry-pick #8329 to v1.71.x
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/proxy_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8353 Cherry-pick #8329 to v1.72.x
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
  internal/transport/proxy_ext_test.go
Labels: Type: Bug

#8355 Change version to v1.71.3
  version.go
Labels: Type: Meta

#8357 Change version to v1.72.2
  version.go
Labels: Type: Meta

#8358 Update version to 1.71.4-dev
  version.go
Labels: Type: Meta

#8359 Update version to 1.72.3-dev
  version.go
Labels: Type: Meta

#8347 balacergroup: cleanup exitIdle()
  internal/balancergroup/balancergroup.go
Labels: Type: Internal Cleanup, Area: Resolvers/Balancers

#8363 xdsclient: Fix flakyness in `TestResourceUpdateMetrics` in the case of repeated NACKs
  xds/internal/clients/xdsclient/test/helpers_test.go
  xds/internal/clients/xdsclient/test/metrics_test.go
Labels: Type: Testing, Area: Testing

#8361 transport: Optimize allocations
  internal/transport/controlbuf.go
  internal/transport/http2_server.go
Labels: Type: Performance, Area: Transport

#8360 transport: Re-use slice buffer reader for a stream
  internal/transport/controlbuf.go
  internal/transport/http2_client.go
  internal/transport/http2_server.go
  internal/transport/transport_test.go
  mem/buffer_slice.go
Labels: Type: Performance, Area: Transport
