Repository grpc/grpc-go, pull requests merged in 2025-09, with the labels that each got.

#8528 transport: allow stream cancellation on the server when blocked on flow control
  internal/transport/http2_server.go
  test/transport_test.go
Labels: Type: Bug

#8556 github,test: fix internal CI build
  .github/pull_request_template.md
  test/transport_test.go
Labels: Type: Internal Cleanup

#8554 Cherry-pick #8528 to v1.74.x
  internal/transport/http2_server.go
  test/transport_test.go
Labels: Type: Bug

#8518 transport: handle 1xx HTTP status HEADERS at the client side
  internal/transport/http2_client.go
  internal/transport/transport_test.go
Labels: Type: Bug

#8558 priority: use new-style atomic APIs
  internal/xds/balancer/priority/ignore_resolve_now.go
Labels: Type: Internal Cleanup, Area: xDS

#8551 xds: move env var check for HTTP CONNECT metadata parsing to endpoint and locality parsing functions
  internal/xds/xdsclient/xdsresource/unmarshal_eds.go
  internal/xds/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Internal Cleanup, Area: xDS

#8559 Change version to 1.75.1
  version.go
Labels: Type: Meta

#8560 Change version to v1.74.3
  version.go
Labels: Type: Meta

#8342 stats/opentelemetry: record retry attempts from clientStream
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/trace.go
Labels: Type: Bug, Area: Observability

#8562 Change version to v1.73.1
  version.go
Labels: Type: Meta

#8565 Change version to v1.75.2-dev
  version.go
Labels: Type: Meta

#8568 Change version to 1.72.4-dev
  version.go
Labels: Type: Meta

#8571 Revert "stats/opentelemetry: record retry attempts from clientStream (#8342)"
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/opentelemetry.go
  stats/opentelemetry/trace.go
Labels: Type: Bug

#8575 internal/buffer: set closed flag when closing channel in the Load method
  internal/buffer/unbounded.go
Labels: Type: Bug

#8564 client: minor improvements to log messages
  clientconn.go
  internal/channelz/trace.go
Labels: Type: Internal Cleanup, Area: Client

#8586 Change version to 1.77.0-dev
  version.go
Labels: Type: Meta

#8588 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Meta

#8589 credentials: Remove TODO from public godoc
  credentials/credentials.go
Labels: Type: Internal Cleanup, Area: Auth

#8578 flowcontrol: change variable names for better understanding
  internal/transport/flowcontrol.go
Labels: Type: Internal Cleanup

#8600 xdsclient/tests: move fallback tests to separate directory
  internal/xds/xdsclient/tests/fallback/fallback_test.go
Labels: Type: Testing, Area: xDS

#8608 xds: Fix log level and message
  internal/xds/balancer/clusterimpl/clusterimpl.go
  internal/xds/clients/xdsclient/ads_stream.go
Labels: Type: Internal Cleanup

#8610 pickfirstleaf: Fix shuffling of addresses in resolver updates without endpoints
  balancer/pickfirst/pickfirst.go
  balancer/pickfirst/pickfirst_ext_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8549 xds/clusterimpl: Convert existing unit tests to e2e style (1/N)
  internal/xds/balancer/clusterimpl/balancer_test.go
  internal/xds/balancer/clusterimpl/tests/balancer_test.go
Labels: Type: Testing

#8615 pickfirstleaf: Avoid getting stuck in IDLE on connection breakage
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8609 xds/resolver: minor cleanup in the config selector implementation
  internal/xds/resolver/serviceconfig.go
  internal/xds/resolver/serviceconfig_test.go
  internal/xds/resolver/xds_resolver.go
Labels: Type: Internal Cleanup
