Repository grpc/grpc-go, pull requests merged in 2025-02, with the labels that each got.

#8052 endpointsharding, lazy: Remove intermediary gracefulswitch balancers
  balancer/endpointsharding/endpointsharding.go
  balancer/endpointsharding/endpointsharding_test.go
  balancer/lazy/lazy.go
  balancer/lazy/lazy_ext_test.go
  balancer/leastrequest/leastrequest.go
  balancer/weightedroundrobin/balancer.go
  examples/features/customloadbalancer/client/customroundrobin/customroundrobin.go
Labels: Type: Internal Cleanup

#8022 test: modify tests to use stubserver instead of Testservice implementation
  credentials/alts/alts_test.go
  test/stats_test.go
  xds/internal/server/listener_wrapper_test.go
Labels: Type: Testing

#8061 internal/dns: update TestDNSResolver_ExponentialBackoff to not return error before last resolution attempt
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Testing, Area: Testing

#8050 xds: resubmit xds client pool changes from #7898 along with fix to set fallback bootstrap config from googledirectpath to xdsclient pool
  internal/internal.go
  internal/testutils/xds/e2e/setup/setup.go
  internal/xds/bootstrap/bootstrap.go
  test/xds/xds_client_ack_nack_test.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_client_custom_dialer_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_client_ignore_resource_deletion_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_integration_test.go
  xds/csds/csds_e2e_test.go
  xds/googledirectpath/googlec2p.go
  xds/googledirectpath/googlec2p_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/httpfilter/fault/fault_test.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/helpers_test.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/rds_handler_test.go
  xds/internal/xdsclient/channel_test.go
  xds/internal/xdsclient/client.go
  xds/internal/xdsclient/client_new.go
  xds/internal/xdsclient/client_refcounted.go
  xds/internal/xdsclient/client_refcounted_test.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_dump.go
  xds/internal/xdsclient/pool.go
  xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go
  xds/internal/xdsclient/tests/ads_stream_backoff_test.go
  xds/internal/xdsclient/tests/ads_stream_flow_control_test.go
  xds/internal/xdsclient/tests/ads_stream_restart_test.go
  xds/internal/xdsclient/tests/ads_stream_watch_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/dump_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/fallback_test.go
  xds/internal/xdsclient/tests/federation_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/loadreport_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/errors.go
  xds/server.go
  xds/server_ext_test.go
  xds/server_options.go
  xds/server_test.go
Labels: Type: Internal Cleanup, Area: xDS

#8067 deps: bump envoyproxy/go-control-plane/envoy and synchronize go.mods
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies, Area: Tooling

#8026 balancer: Enforce embedding requirement for balancer.ClientConn
  balancer/balancer.go
  balancer/subconn.go
  balancer_wrapper.go
  internal/balancer/gracefulswitch/gracefulswitch.go
  internal/internal.go
  internal/testutils/balancer.go
  xds/internal/balancer/outlierdetection/balancer.go
Labels: Type: API Change, Area: Resolvers/Balancers

#8027 balancer: Move metrics recorder from BuildOptions to ClientConn
  balancer/balancer.go
  balancer/pickfirst/pickfirst_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_test.go
  balancer/rls/balancer.go
  balancer/weightedroundrobin/balancer.go
  balancer_wrapper.go
  internal/balancergroup/balancergroup_test.go
  internal/stats/metrics_recorder_list_test.go
  internal/testutils/balancer.go
  xds/internal/balancer/clustermanager/clustermanager_test.go
Labels: Type: API Change, Area: Resolvers/Balancers

#8038 xds/internal/xdsclient: Add counter metrics for valid and invalid resource updates
  internal/internal.go
  resolver/resolver.go
  resolver_wrapper.go
  server.go
  xds/internal/resolver/internal/internal.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/client_refcounted_test.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/metrics_test.go
  xds/internal/xdsclient/pool.go
  xds/server.go
Labels: Type: Feature

#8069 endpointsharding: cast EndpointMap values to *balancerWrapper instead of Balancer
  balancer/endpointsharding/endpointsharding.go
  balancer/endpointsharding/endpointsharding_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#7907 test/gracefulstop: use stubserver instead of testservice implementation
  test/gracefulstop_test.go
Labels: Type: Testing

#8060 interop: Fix logging and totalIterations issues in soak_tests.go
  interop/soak_tests.go
Labels: Type: Testing

#8073 advancedtls: update CRL provider certificates
  security/advancedtls/testdata/crl/provider_client_cert.key
  security/advancedtls/testdata/crl/provider_client_cert.pem
  security/advancedtls/testdata/crl/provider_client_trust_cert.pem
  security/advancedtls/testdata/crl/provider_client_trust_key.pem
  security/advancedtls/testdata/crl/provider_crl_empty.pem
  security/advancedtls/testdata/crl/provider_crl_server_revoked.pem
  security/advancedtls/testdata/crl/provider_malicious_client_trust_cert.pem
  security/advancedtls/testdata/crl/provider_malicious_client_trust_key.pem
  security/advancedtls/testdata/crl/provider_malicious_crl_empty.pem
  security/advancedtls/testdata/crl/provider_server_cert.key
  security/advancedtls/testdata/crl/provider_server_cert.pem
  security/advancedtls/testdata/crl/provider_server_trust_cert.pem
  security/advancedtls/testdata/crl/provider_server_trust_key.pem
Labels: Type: Testing, Area: Testing

#8075 xdsclient: invoke connectivity failure callback only after all listed servers have failed
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/fallback_test.go
Labels: Type: Bug

#8082 test: Remove fake petiole in health tests
  test/healthcheck_test.go
Labels: Type: Internal Cleanup, Area: Testing

#8047 ringhash: Delegate subchannel creation to pickfirst
  balancer/weightedroundrobin/weightedroundrobin.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/logging.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Feature, Area: Resolvers/Balancers

#8086 ringhash: Sort endpoints to prevent unnecessary connection attempts
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Bug

#8055 rls: change lossy GetState() and WaitForStateChange() to use grpcsync.PubSub
  balancer/rls/control_channel.go
Labels: Type: Bug

#8078 client: improve documentation of target strings
  clientconn.go
Labels: Type: Documentation

#8093 xdsclient: include xds node ID in errors from the WatchResource API
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
Labels: Type: Feature

#8088 lazy: Fix data race in TestGoodUpdateThenResolverError
  balancer/lazy/lazy_ext_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8091 ringhash: Replace DNS resolver before sending xDS Update in test
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Bug, Area: Testing

#7975 cleanup: replace dial with newclient
  clientconn_test.go
  security/advancedtls/advancedtls_integration_test.go
  server_ext_test.go
  test/balancer_switching_test.go
  test/balancer_test.go
  test/clientconn_state_transition_test.go
  test/end2end_test.go
  test/healthcheck_test.go
  test/local_creds_test.go
  test/resolver_update_test.go
  test/xds/xds_client_affinity_test.go
  test/xds/xds_client_certificate_providers_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_server_integration_test.go
  xds/googledirectpath/googlec2p_test.go
Labels: Type: Internal Cleanup

#8096 ringhash: Remove TODO comment
  xds/internal/balancer/ringhash/ringhash.go
Labels: Type: Internal Cleanup

#8107 Change version to 1.72.0-dev
  version.go
Labels: Type: Meta

#8087 weightedroundrobin: Move functions to get Address/Endpoint weights into a new internal package
  balancer/weightedroundrobin/balancer.go
  balancer/weightedroundrobin/weightedroundrobin.go
  balancer/weightedroundrobin/weightedroundrobin_test.go
  internal/balancer/weight/weight.go
  internal/balancer/weight/weight_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: Internal Cleanup

#8103 xdsclient: ensure xDS node ID in included in NACK and connectivity errors
  xds/internal/xdsclient/tests/ads_stream_backoff_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
Labels: Type: Feature

#8100 chore: enable early-return and unnecessary-stmt and useless-break from revive
  clientconn.go
  internal/stubserver/stubserver.go
  internal/transport/http2_client.go
  profiling/cmd/flags.go
  scripts/revive.toml
  test/bufconn/bufconn.go
  test/end2end_test.go
Labels: Type: Testing, Area: Testing

#8098 examples/features/dualstack: Demonstrate Dual Stack functionality
  examples/examples_test.sh
  examples/features/dualstack/README.md
  examples/features/dualstack/client/main.go
  examples/features/dualstack/server/main.go
Labels: Type: Documentation, Area: Documentation

#8115 Cherry pick #8098 to v1.71.x
  examples/examples_test.sh
  examples/features/dualstack/README.md
  examples/features/dualstack/client/main.go
  examples/features/dualstack/server/main.go
Labels: Type: Documentation, Area: Documentation

#8095 balancergroup: Make closing terminal
  balancer/rls/balancer.go
  balancer/weightedtarget/weightedtarget.go
  internal/balancergroup/balancergroup.go
  internal/balancergroup/balancergroup_test.go
  xds/internal/balancer/clustermanager/clustermanager.go
  xds/internal/balancer/priority/balancer.go
Labels: Type: Bug

#8108 deps: update dependencies for all modules
  .github/workflows/testing.yml
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  scripts/vet.sh
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#8123 xds: simplify code handling certain error conditions in the resolver
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/internal/xdsclient/xdsresource/matcher.go
Labels: Type: Internal Cleanup

#8126 xds, pickfirst: Enable additional addresses in xDS, set new pick_first as default
  .github/workflows/coverage.yml
  internal/envconfig/envconfig.go
  internal/envconfig/xds.go
Labels: Type: Feature

#8129 github/test: Run tests using the old pickfirst
  .github/workflows/testing.yml
Labels: Type: Testing

#7967 cleanup: replace dial with newclient
  balancer_wrapper_test.go
  clientconn_test.go
  examples/features/customloadbalancer/client/main.go
  resolver_test.go
  test/clientconn_state_transition_test.go
  test/goaway_test.go
  test/gracefulstop_test.go
  test/retry_test.go
  test/xds/xds_client_federation_test.go
  test/xds/xds_security_config_nack_test.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
Labels: Type: Internal Cleanup

#7970 cleanup: replace dial with newclient
  admin/test/utils.go
  balancer/grpclb/grpclb_remote_balancer.go
  benchmark/benchmark.go
  credentials/alts/internal/handshaker/service/service.go
  internal/stubserver/stubserver.go
  interop/alts/client/client.go
  interop/client/client.go
  interop/grpclb_fallback/client_linux.go
  interop/http2/negative_http2_client.go
  interop/observability/client/client.go
  interop/stress/client/main.go
  interop/stress/metrics_client/main.go
  interop/xds/client/client.go
  interop/xds_federation/client.go
  profiling/cmd/remote.go
  resolver/manual/manual.go
  resolver/manual/manual_test.go
  test/goaway_test.go
  test/xds/xds_client_certificate_providers_test.go
  xds/internal/test/e2e/e2e.go
Labels: Type: Internal Cleanup

#8077 stats/openetelemetry: refactor and make e2e test stats verification deterministic
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/internal/testutils/testutils.go
  stats/opentelemetry/trace.go
Labels: Type: Testing

#8066 xds: introduce simple grpc transport for generic xds clients
  xds/internal/clients/grpctransport/grpc_transport.go
  xds/internal/clients/grpctransport/grpc_transport_test.go
Labels: Type: Feature, Area: xDS

#8071 transport: Send RST stream from the server when deadline expires
  internal/grpctest/grpctest.go
  internal/internal.go
  internal/leakcheck/leakcheck.go
  internal/leakcheck/leakcheck_test.go
  internal/transport/client_stream.go
  internal/transport/http2_server.go
  internal/transport/server_stream.go
  internal/transport/transport_test.go
Labels: Type: Behavior Change

#8133 clusterresolver: Lower log level when ExitIdle is called with no child
  xds/internal/balancer/clusterresolver/clusterresolver.go
Labels: Type: Testing
