Repository grpc/grpc-go, pull requests merged in 2025-04, with the labels that each got.

#8212 Change version 1.71.2-dev
  version.go
Labels: Type: Meta

#8217 xdsclient: fix TestServerFailureMetrics_BeforeResponseRecv test to wait for watch to start before stopping the listener
  xds/internal/xdsclient/metrics_test.go
Labels: Type: Testing

#8220 Change version to 1.73.0-dev
  version.go
Labels: Type: Meta

#8221 deps: update dependencies for all modules
  balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  binarylog/grpc_binarylog_v1/binarylog.pb.go
  channelz/grpc_channelz_v1/channelz.pb.go
  cmd/protoc-gen-go-grpc/go.mod
  cmd/protoc-gen-go-grpc/go.sum
  credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  examples/features/proto/echo/echo.pb.go
  examples/go.mod
  examples/go.sum
  examples/helloworld/helloworld/helloworld.pb.go
  examples/route_guide/routeguide/route_guide.pb.go
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  health/grpc_health_v1/health.pb.go
  internal/proto/grpc_lookup_v1/rls.pb.go
  internal/proto/grpc_lookup_v1/rls_config.pb.go
  interop/grpc_testing/benchmark_service.pb.go
  interop/grpc_testing/control.pb.go
  interop/grpc_testing/core/stats.pb.go
  interop/grpc_testing/empty.pb.go
  interop/grpc_testing/messages.pb.go
  interop/grpc_testing/payloads.pb.go
  interop/grpc_testing/report_qps_scenario_service.pb.go
  interop/grpc_testing/stats.pb.go
  interop/grpc_testing/test.pb.go
  interop/grpc_testing/worker_service.pb.go
  interop/observability/go.mod
  interop/observability/go.sum
  interop/stress/grpc_testing/metrics.pb.go
  interop/xds/go.mod
  interop/xds/go.sum
  profiling/proto/service.pb.go
  reflection/grpc_reflection_v1/reflection.pb.go
  reflection/grpc_reflection_v1alpha/reflection.pb.go
  reflection/grpc_testing/proto2.pb.go
  reflection/grpc_testing/proto2_ext.pb.go
  reflection/grpc_testing/proto2_ext2.pb.go
  reflection/grpc_testing/test.pb.go
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/codec_perf/perf.pb.go
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#8074 stats/opentelemetry: add trace event for name resolution delay
  clientconn.go
  internal/internal.go
  stats/handlers.go
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/opentelemetry.go
  stream.go
  test/clientconn_test.go
Labels: Type: Feature, Area: Observability

#8180 [Security] Add support for SPIFFE Bundle Maps in XDS bundles
  credentials/tls/certprovider/pemfile/builder.go
  credentials/tls/certprovider/pemfile/watcher.go
  internal/credentials/spiffe/spiffe.go
  internal/credentials/spiffe/spiffe_test.go
  internal/testutils/tls_creds.go
  internal/xds/bootstrap/tlscreds/bundle.go
  internal/xds/bootstrap/tlscreds/bundle_ext_test.go
  internal/xds/bootstrap/tlscreds/bundle_test.go
  testdata/spiffe/README.md
  testdata/spiffe/spiffebundle_empty_keys.json
  testdata/spiffe/spiffebundle_empty_string_key.json
  testdata/spiffe/spiffebundle_match_client_spiffe.json
  testdata/spiffe_end2end/README.md
  testdata/spiffe_end2end/ca.key
  testdata/spiffe_end2end/ca.pem
  testdata/spiffe_end2end/client.key
  testdata/spiffe_end2end/client_spiffe.pem
  testdata/spiffe_end2end/client_spiffebundle.json
  testdata/spiffe_end2end/generate.sh
  testdata/spiffe_end2end/intermediate.cnf
  testdata/spiffe_end2end/intermediate_ca.key
  testdata/spiffe_end2end/intermediate_ca.pem
  testdata/spiffe_end2end/intermediate_gen.sh
  testdata/spiffe_end2end/leaf_and_intermediate_chain.pem
  testdata/spiffe_end2end/leaf_signed_by_intermediate.key
  testdata/spiffe_end2end/leaf_signed_by_intermediate.pem
  testdata/spiffe_end2end/server.key
  testdata/spiffe_end2end/server_spiffe.pem
  testdata/spiffe_end2end/server_spiffebundle.json
  testdata/spiffe_end2end/spiffe-openssl.cnf
Labels: Type: Security, Area: xDS, Area: Auth

#8204 credentials/alts: Optimize reads
  credentials/alts/internal/conn/common.go
  credentials/alts/internal/conn/record.go
  credentials/alts/internal/conn/record_test.go
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Performance, Area: Auth

#8232 credentials/alts: Add comments to clarify buffer sizing
  credentials/alts/internal/conn/record.go
Labels: Type: Internal Cleanup, Area: Auth

#8235 testdata: Wrap lines to 80 columns in markdown file
  testdata/spiffe_end2end/README.md
Labels: Type: Internal Cleanup

#8159 ringhash: implement gRFC A76
  internal/envconfig/envconfig.go
  internal/metadata/metadata.go
  internal/testutils/envconfig.go
  internal/testutils/xds/e2e/clientresources.go
  resolver/ringhash/attr.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/ringhash/config.go
  xds/internal/balancer/ringhash/config_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
  xds/internal/balancer/ringhash/util.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/xdsresource/type_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: P1, Type: Feature, Area: xDS, Area: Resolvers/Balancers

#8236 Rollback #8232 and #8204
  credentials/alts/internal/conn/common.go
  credentials/alts/internal/conn/record.go
  credentials/alts/internal/conn/record_test.go
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Bug

#8237 stats/opentelemetry: fix trace attributes message sequence numbers to start from 0
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/trace.go
Labels: Type: Bug, Area: Observability

#7977 xdsclient: update watcher API as per gRFC A88
  internal/xds/bootstrap/bootstrap.go
  xds/csds/csds_e2e_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/cdsbalancer/cluster_watcher.go
  xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
  xds/internal/balancer/clusterresolver/resource_resolver.go
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/rds_handler.go
  xds/internal/testutils/resource_watcher.go
  xds/internal/xdsclient/authority.go
  xds/internal/xdsclient/clientimpl_watchers.go
  xds/internal/xdsclient/metrics_test.go
  xds/internal/xdsclient/tests/ads_stream_flow_control_test.go
  xds/internal/xdsclient/tests/authority_test.go
  xds/internal/xdsclient/tests/cds_watchers_test.go
  xds/internal/xdsclient/tests/eds_watchers_test.go
  xds/internal/xdsclient/tests/lds_watchers_test.go
  xds/internal/xdsclient/tests/misc_watchers_test.go
  xds/internal/xdsclient/tests/rds_watchers_test.go
  xds/internal/xdsclient/tests/resource_update_test.go
  xds/internal/xdsclient/xdsresource/cluster_resource_type.go
  xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
  xds/internal/xdsclient/xdsresource/listener_resource_type.go
  xds/internal/xdsclient/xdsresource/resource_type.go
  xds/internal/xdsclient/xdsresource/route_config_resource_type.go
  xds/server_ext_test.go
  xds/server_security_ext_test.go
  xds/server_test.go
Labels: Type: Feature, Area: xDS

#8243 ringhash: normalize uppercase in requestHashHeader from service config
  xds/internal/balancer/ringhash/config.go
  xds/internal/balancer/ringhash/config_test.go
Labels: Type: Bug, Area: Resolvers/Balancers

#8224 Update lrs_stream.go fix use of wrong err
  xds/internal/xdsclient/transport/lrs/lrs_stream.go
Labels: Type: Bug

#8252 Cherry-pick #8237 to v1.72.x
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/trace.go
Labels: Type: Bug

#8255 Cherry-pick #8159 and #8243 to v1.72.x
  internal/envconfig/envconfig.go
  internal/metadata/metadata.go
  internal/testutils/envconfig.go
  internal/testutils/xds/e2e/clientresources.go
  resolver/ringhash/attr.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/ringhash/config.go
  xds/internal/balancer/ringhash/config_test.go
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
  xds/internal/balancer/ringhash/picker.go
  xds/internal/balancer/ringhash/picker_test.go
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
  xds/internal/balancer/ringhash/util.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/xdsresource/type_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Feature

#8254 xds: fix test data file name
  internal/xds/bootstrap/tlscreds/bundle_ext_test.go
Labels: Type: Testing, Area: Testing

#8259 Cherry-pick #8227 to v1.72.x
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Labels: Type: Bug

#8253 xds: make least request available by default
  internal/envconfig/envconfig.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry.go
  xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
Labels: Type: Feature, Area: Resolvers/Balancers

#8226 New A72 changes for OpenTelemetry #8216
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/server_tracing.go
  stats/opentelemetry/trace.go
Labels: Type: Internal Cleanup, Area: Observability

#8056 examples/features/opentelemetry: demonstrate tracing using OpenTelemetry plugin
  examples/features/opentelemetry/README.md
  examples/features/opentelemetry/client/main.go
  examples/features/opentelemetry/server/main.go
  examples/go.mod
  examples/go.sum
Labels: Type: Documentation, Area: Observability

#8256 xds: Make locality ID string representation consistent with A78
  stats/opentelemetry/e2e_test.go
  test/xds/xds_telemetry_labels_test.go
  xds/internal/balancer/clusterimpl/balancer_test.go
  xds/internal/balancer/clusterimpl/picker.go
  xds/internal/balancer/clusterresolver/configbuilder.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/balancer/wrrlocality/balancer.go
  xds/internal/balancer/wrrlocality/balancer_test.go
  xds/internal/internal.go
  xds/internal/internal_test.go
  xds/internal/xdsclient/tests/loadreport_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_eds.go
Labels: Type: Bug, Area: xDS

#8257 ringhash: fix flaky e2e tests
  xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Labels: Type: Testing

#8260 cleanup: status formatting bug and comment grammar fix
  xds/internal/resolver/serviceconfig.go
  xds/server_test.go
Labels: Type: Internal Cleanup

#8263 github: add printing of new packages to dependency checker
  .github/workflows/deps.yml
Labels: Type: Testing

#8249 ringhash: move out of the xds package
  balancer/ringhash/config.go
  balancer/ringhash/config_test.go
  balancer/ringhash/logging.go
  balancer/ringhash/picker.go
  balancer/ringhash/picker_test.go
  balancer/ringhash/ring.go
  balancer/ringhash/ring_test.go
  balancer/ringhash/ringhash.go
  balancer/ringhash/ringhash_e2e_test.go
  balancer/ringhash/ringhash_test.go
  internal/ringhash/ringhash.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/config_test.go
  xds/internal/balancer/clusterresolver/configbuilder_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/xdslbregistry/converter/converter.go
  xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
Labels: Type: Internal Cleanup, Area: xDS, Area: Resolvers/Balancers

#8218 Change version to v1.72.0
  version.go
Labels: Type: Meta

#8219 Change version to v1.72.1-dev
  version.go
Labels: Type: Meta

#8198 credentials: expose NewRequestInfoContext publicly
  credentials/credentials.go
  credentials/google/google_test.go
  credentials/sts/sts_test.go
  internal/credentials/credentials.go
  internal/transport/http2_client.go
Labels: Status: Requires Reporter Clarification, Type: Internal Cleanup

#8266 atls: Clarify usage of dst in ALTSRecordCrypto interface docs
  credentials/alts/internal/conn/record.go
Labels: Type: Documentation, Area: Auth

#8269 xds: fix TestServer_Security_WithValidAndInvalidSecurityConfiguration data race
  xds/server_ext_test.go
  xds/server_security_ext_test.go
Labels: Type: Bug

#8264 github: replace actions/upload-release-asset@v1 with gh cli
  .github/workflows/release.yml
Labels: Status: Requires Reporter Clarification, Type: Meta

#8273 xds: Remove redundant proto checks
  xds/internal/clients/xdsclient/helpers_test.go
  xds/internal/clients/xdsclient/test/helpers_test.go
  xds/internal/xdsclient/xdsresource/unmarshal_lds.go
Labels: Type: Internal Cleanup

#8120 grpc_test: add tests for cardinality violation
  test/end2end_test.go
Labels: Type: Testing

#8271 credentials/alts: Optimize Reads (Roll forward #8236)
  credentials/alts/internal/conn/common.go
  credentials/alts/internal/conn/record.go
  credentials/alts/internal/conn/record_test.go
  credentials/alts/internal/handshaker/handshaker.go
Labels: Type: Performance, Area: Auth

#8277 grpc: regenerate protos
  credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
Labels: Type: Meta

#8068 credentials, transport, grpc : add a call option to override the :authority header on a per-RPC basis
  credentials/credentials.go
  credentials/credentials_ext_test.go
  credentials/insecure/insecure.go
  credentials/tls.go
  credentials/tls_ext_test.go
  internal/transport/http2_client.go
  internal/transport/transport.go
  rpc_util.go
  stream.go
Labels: Type: Feature, Area: Auth
