Repository grpc/grpc-go, pull requests merged in 2025-08, with the labels that each got.

#8481 stats: change non-standard units to annotations
  balancer/pickfirst/pickfirstleaf/metrics_test.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/rls/balancer.go
  balancer/rls/metrics_test.go
  balancer/weightedroundrobin/balancer.go
  experimental/stats/metricregistry_test.go
  stats/opentelemetry/client_metrics.go
  stats/opentelemetry/csm/observability_test.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/internal/testutils/testutils.go
  stats/opentelemetry/server_metrics.go
  xds/internal/xdsclient/clientimpl.go
Labels: Type: Bug, Area: Observability

#8482 xds: remove xds client fallback environment variable
  internal/envconfig/envconfig.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
Labels: Type: Behavior Change

#8488 credentials: fix behavior of grpc.WithAuthority and credential handshake precedence
  clientconn.go
  credentials/alts/alts_test.go
  credentials/credentials.go
  credentials/tls.go
  credentials/xds/xds_client_test.go
  dialoptions.go
  experimental/credentials/tls.go
  resolver/resolver.go
  scripts/vet.sh
  security/advancedtls/advancedtls.go
  test/balancer_test.go
  test/creds_test.go
Labels: Type: Behavior Change

#8495 Change version to 1.76.0-dev
  version.go
Labels: Type: Meta

#8497 deps: update dependencies for all modules
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  interop/xds/go.mod
  interop/xds/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#8498 xdsclient: schedule serializer callback from the authority instead of from the xdsChannel
  xds/internal/clients/xdsclient/authority.go
  xds/internal/clients/xdsclient/xdsclient.go
Labels: Type: Internal Cleanup

#8427 xdsclient: add an e2e style test for fallback involving more than 2 servers #7817
  xds/internal/xdsclient/tests/fallback_test.go
Labels: Type: Testing

#8509 deps: bump go version to 1.24
  .github/workflows/testing.yml
  cmd/protoc-gen-go-grpc/go.mod
  examples/go.mod
  gcp/observability/go.mod
  go.mod
  interop/observability/go.mod
  interop/xds/go.mod
  scripts/vet.sh
  security/advancedtls/examples/go.mod
  security/advancedtls/go.mod
  stats/opencensus/go.mod
  test/tools/go.mod
Labels: Type: Dependencies

#8519 transport: ensure header mutex is held while copying trailers in handler_server
  internal/transport/handler_server.go
  internal/transport/handler_server_test.go
Labels: Type: Bug

#8524 github: add PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: Type: Meta

#8533 CONTRIBUTING.md: minor text tweaks for linters
  CONTRIBUTING.md
Labels: Type: Documentation

#8523 client: Roll-forward PR #8278(with changes): Restore the existing behavior to return io.EOF on repeated RecvMsg() calls for client-streaming RPCs
  stream.go
  test/end2end_test.go
Labels: Type: Bug

#8483 xdsclient: create LRSClient at time of initialisation
  internal/xds/clients/lrsclient/lrsclient.go
  internal/xds/xdsclient/clientimpl.go
  internal/xds/xdsclient/clientimpl_loadreport.go
  internal/xds/xdsclient/tests/loadreport_test.go
Labels: Type: Bug, Area: xDS

#8541 Cherry pick #8483 into v1.75.x
  xds/internal/clients/lrsclient/lrsclient.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/clientimpl_loadreport.go
  xds/internal/xdsclient/tests/loadreport_test.go
Labels: Type: Bug

#8537 xds: add xds metadata registry
  internal/envconfig/xds.go
  internal/xds/xdsclient/xdsresource/metadata.go
  internal/xds/xdsclient/xdsresource/metadata_test.go
  internal/xds/xdsclient/xdsresource/type_eds.go
  internal/xds/xdsclient/xdsresource/unmarshal_eds.go
  internal/xds/xdsclient/xdsresource/unmarshal_eds_test.go
Labels: Type: Feature, Area: xDS
