Repository grpc/grpc-go, pull requests merged in 2025-03, with the labels that each got.

#8105 Change version to 1.71.0
  version.go
Labels: Type: Meta

#8106 Change version to 1.71.1-dev
  version.go
Labels: Type: Meta

#8131 xds: ensure xDS node ID is populated in errors from xds resolver and cds lb policy
  test/xds/xds_client_ignore_resource_deletion_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/priority/balancer.go
  xds/internal/resolver/cluster_specifier_plugin_test.go
  xds/internal/resolver/helpers_test.go
  xds/internal/resolver/serviceconfig.go
  xds/internal/resolver/watch_service_test.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/resolver/xds_resolver_test.go
  xds/internal/xdsclient/xdsresource/errors.go
Labels: Type: Feature

#8141 interop: Wait for server to become ready in alts tests
  interop/alts/client/client.go
Labels: Type: Testing

#8142 *: Regenerate protos
  internal/proto/grpc_lookup_v1/rls_config.pb.go
Labels: Type: Dependencies

#8042 xds: introduce generic xds clients xDS and LRS Client API signatures
  xds/internal/clients/config.go
  xds/internal/clients/config_test.go
  xds/internal/clients/grpctransport/grpc_transport.go
  xds/internal/clients/grpctransport/grpc_transport_test.go
  xds/internal/clients/internal/internal.go
  xds/internal/clients/internal/internal_test.go
  xds/internal/clients/lrsclient/load_store.go
  xds/internal/clients/lrsclient/lrsclient.go
  xds/internal/clients/lrsclient/lrsconfig.go
  xds/internal/clients/transport_builder.go
  xds/internal/clients/xdsclient/resource_type.go
  xds/internal/clients/xdsclient/resource_watcher.go
  xds/internal/clients/xdsclient/xdsclient.go
  xds/internal/clients/xdsclient/xdsconfig.go
Labels: Type: Feature, Area: xDS

#8149 grpc: Add endpoints in resolverWrapper.NewAddresses
  resolver_test.go
  resolver_wrapper.go
  scripts/vet.sh
Labels: Type: Bug

#8151 Cherry pick #8149 to v1.71.x
  resolver_test.go
  resolver_wrapper.go
  scripts/vet.sh
Labels: Type: Bug

#8150 resolver/manual: allow calling UpdateState with an un-Built resolver
  balancer/endpointsharding/endpointsharding_test.go
  balancer/grpclb/grpclb_test.go
  balancer/lazy/lazy_ext_test.go
  balancer/pickfirst/pickfirst_ext_test.go
  balancer/weightedroundrobin/balancer_test.go
  clientconn_test.go
  internal/stubserver/stubserver.go
  resolver/manual/manual.go
  resolver/manual/manual_test.go
  resolver_test.go
  test/balancer_switching_test.go
  test/balancer_test.go
  test/parse_config.go
  test/resolver_update_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
  xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
Labels: Type: Testing

#8140 xds: ensure node ID is populated in errors from the server
  internal/testutils/xds/e2e/clientresources.go
  test/xds/xds_server_rbac_test.go
  test/xds/xds_server_serving_mode_test.go
  test/xds/xds_server_test.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/listener_wrapper_test.go
  xds/internal/server/rds_handler.go
  xds/internal/xdsclient/xdsresource/filter_chain.go
  xds/server.go
  xds/server_ext_test.go
  xds/server_resource_ext_test.go
  xds/server_security_ext_test.go
  xds/server_serving_mode_ext_test.go
Labels: Type: Feature

#8158 xds: emit resource-not-found logs at Warning level
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterresolver/resource_resolver_eds.go
  xds/internal/resolver/xds_resolver.go
  xds/internal/server/listener_wrapper.go
  xds/internal/server/rds_handler.go
Labels: Type: Feature

#8137 balancer/rls: allow maxAge to exceed 5m if staleAge is set
  balancer/rls/config.go
  balancer/rls/config_test.go
Labels: Type: Feature, Area: Resolvers/Balancers

#8124 [Security] Add support for parsing SPIFFE Bundle Maps
  .github/workflows/testing.yml
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  internal/credentials/spiffe/spiffe.go
  internal/credentials/spiffe/spiffe_test.go
  interop/observability/go.sum
  scripts/vet-proto.sh
  security/advancedtls/examples/go.mod
  security/advancedtls/go.mod
  stats/opencensus/go.sum
  testdata/spiffe/README.md
  testdata/spiffe/client_spiffe.pem
  testdata/spiffe/server1_spiffe.pem
  testdata/spiffe/spiffe-openssl.cnf
  testdata/spiffe/spiffe_cert.pem
  testdata/spiffe/spiffe_multi_uri_san_cert.pem
  testdata/spiffe/spiffe_test.json
  testdata/spiffe/spiffebundle.json
  testdata/spiffe/spiffebundle_corrupted_cert.json
  testdata/spiffe/spiffebundle_invalid_trustdomain.json
  testdata/spiffe/spiffebundle_malformed.json
  testdata/spiffe/spiffebundle_wrong_kid.json
  testdata/spiffe/spiffebundle_wrong_kty.json
  testdata/spiffe/spiffebundle_wrong_multi_certs.json
  testdata/spiffe/spiffebundle_wrong_root.json
  testdata/spiffe/spiffebundle_wrong_seq_type.json
  testdata/spiffe/spiffebundle_wrong_use.json
Labels: Type: Security, Area: xDS, Area: Auth

#8163 example/features/retry: fix grpc.NewClient call in documentation
  examples/features/retry/README.md
Labels: Type: Documentation, Area: Documentation

#8166 stats/opentelemetry: use TextMapProvider and TracerProvider from TraceOptions instead of otel global
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/server_tracing.go
Labels: Type: Bug, Area: Observability

#8164 xdsclient: read bootstrap config before creating the first xDS client in DefaultPool
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/pool.go
  xds/internal/xdsclient/pool/pool_test.go
  xds/server_test.go
Labels: Type: Bug

#8144 xds: generic xDS client transport channel and ads stream implementation
  xds/internal/clients/internal/backoff/backoff.go
  xds/internal/clients/internal/buffer/unbounded.go
  xds/internal/clients/internal/buffer/unbounded_test.go
  xds/internal/clients/internal/pretty/pretty.go
  xds/internal/clients/internal/syncutil/callback_serializer.go
  xds/internal/clients/internal/syncutil/callback_serializer_test.go
  xds/internal/clients/internal/syncutil/event.go
  xds/internal/clients/internal/syncutil/event_test.go
  xds/internal/clients/internal/testutils/channel.go
  xds/internal/clients/internal/testutils/e2e/clientresources.go
  xds/internal/clients/internal/testutils/e2e/logging.go
  xds/internal/clients/internal/testutils/e2e/server.go
  xds/internal/clients/internal/testutils/fakeserver/server.go
  xds/internal/clients/internal/testutils/marshal_any.go
  xds/internal/clients/internal/testutils/restartable_listener.go
  xds/internal/clients/xdsclient/ads_stream.go
  xds/internal/clients/xdsclient/channel.go
  xds/internal/clients/xdsclient/channel_test.go
  xds/internal/clients/xdsclient/helpers_test.go
  xds/internal/clients/xdsclient/internal/xdsresource/errors.go
  xds/internal/clients/xdsclient/internal/xdsresource/name.go
  xds/internal/clients/xdsclient/internal/xdsresource/type.go
  xds/internal/clients/xdsclient/internal/xdsresource/version.go
Labels: Type: Feature, Area: xDS

#8178 grpc: fix bug causing an extra Read if a compressed message is the same size as the limit
  clientconn_test.go
  rpc_util.go
  rpc_util_test.go
Labels: Type: Bug

#7885 stats: Improved sequencing documentation for server-side stats events and added tests.
  stats/stats.go
Labels: Type: Documentation

#8179 resolver: Make EndpointMap's Get, Set and Delete operations O(1)
  resolver/map.go
  resolver/map_test.go
Labels: Type: Performance, Area: Resolvers/Balancers

#8184 Cherry-pick #8179 into v1.71.x
  resolver/map.go
  resolver/map_test.go
Labels: Type: Performance

#8181 Cherry-pick #8178 to v1.71.x release branch
  clientconn_test.go
  rpc_util.go
  rpc_util_test.go
Labels: Type: Bug

#8169 xds: fix support for circuit breakers in LOGICAL_DNS clusters
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
Labels: Type: Bug

#8170 xds: fix support for load reporting in LOGICAL_DNS clusters
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
  xds/internal/balancer/clusterresolver/configbuilder.go
Labels: Type: Bug

#8182 Cherry-pick #8164 #8166 to v1.71.x
  stats/opentelemetry/client_tracing.go
  stats/opentelemetry/e2e_test.go
  stats/opentelemetry/server_metrics.go
  stats/opentelemetry/server_tracing.go
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/pool.go
  xds/internal/xdsclient/pool/pool_test.go
  xds/server_test.go
Labels: Type: Bug

#8188 internal/balancer/clusterimpl: replace testpb with testgrpc
  xds/internal/balancer/clusterimpl/tests/balancer_test.go
Labels: Type: Internal Cleanup, Area: Testing

#8187 resolver: create AddressMapV2 with generics to replace AddressMap
  balancer/base/balancer.go
  balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  balancer/weightedroundrobin/balancer.go
  resolver/map.go
  resolver/map_test.go
Labels: Type: API Change

#8189 resolver: convert EndpointMap to use generics
  balancer/endpointsharding/endpointsharding.go
  balancer/leastrequest/leastrequest.go
  balancer/weightedroundrobin/balancer.go
  resolver/map.go
  resolver/map_test.go
  xds/internal/balancer/outlierdetection/balancer.go
  xds/internal/balancer/ringhash/ring.go
  xds/internal/balancer/ringhash/ring_test.go
  xds/internal/balancer/ringhash/ringhash.go
  xds/internal/balancer/ringhash/ringhash_test.go
Labels: Type: API Change

#8195 delegatingresolver: Stop calls into delegates once the parent resolver is closed.
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Labels: Type: Bug

#8202 Cherry-pick #8195 into v1.71.x
  internal/resolver/delegatingresolver/delegatingresolver.go
  internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Labels: Type: Bug

#8206 Change version to v1.71.1
  version.go
Labels: Type: Meta

#8208 grpc: regenerate protos
  health/grpc_health_v1/health.pb.go
  health/grpc_health_v1/health_grpc.pb.go
Labels: Type: Meta

#8203 xdsclient: add grpc.xds_client.server_failure counter mertric
  xds/internal/xdsclient/clientimpl.go
  xds/internal/xdsclient/metrics_test.go
Labels: Type: Feature, Area: Observability
