Repository grpc/grpc-go, pull requests merged in 2025-07, with the labels that each got.

#8419 xds: Avoid error logs when setting fallback bootstrap config
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  xds/internal/xdsclient/pool.go
  xds/internal/xdsclient/pool/pool_test.go
Labels: Type: Internal Cleanup, Area: xDS

#8377 dns: add environment variable to disable TXT lookups in DNS resolver
  internal/envconfig/envconfig.go
  internal/resolver/dns/dns_resolver.go
  internal/resolver/dns/dns_resolver_test.go
Labels: Type: Feature

#8413 xds: cleanup internal testing functions for env vars that have long been removed
  internal/internal.go
  test/xds/xds_rls_clusterspecifier_plugin_test.go
  test/xds/xds_server_rbac_test.go
  xds/internal/clusterspecifier/rls/rls.go
  xds/internal/httpfilter/rbac/rbac.go
Labels: Type: Internal Cleanup

#8428 xds/cdsbalancer: correctly remove the unwanted cds watchers
  xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
  xds/internal/balancer/cdsbalancer/cdsbalancer.go
  xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Labels: Type: Bug

#8434 deps: update dependencies for all modules
  examples/go.mod
  examples/go.sum
  gcp/observability/go.mod
  gcp/observability/go.sum
  go.mod
  go.sum
  interop/observability/go.mod
  interop/observability/go.sum
  interop/xds/go.mod
  interop/xds/go.sum
  security/advancedtls/examples/go.mod
  security/advancedtls/examples/go.sum
  security/advancedtls/go.mod
  security/advancedtls/go.sum
  stats/opencensus/go.mod
  stats/opencensus/go.sum
  test/tools/go.mod
  test/tools/go.sum
Labels: Type: Dependencies

#8440 Cherry-pick #8439 to v1.74 release branch
  internal/transport/http2_server.go
  internal/transport/http_util.go
  internal/transport/http_util_test.go
Labels: Type: Behavior Change

#8442 credentials: allow audience to be configured (#8421)
  Documentation/grpc-auth-support.md
  internal/envconfig/envconfig.go
  internal/transport/http2_client.go
  test/creds_test.go
Labels: Type: Feature, Type: Security, Area: Auth

#8448 xds: add a test for deadlocks in nested xDS channels
  xds/internal/xdsclient/pool/pool_ext_test.go
  xds/internal/xdsclient/pool/pool_test.go
Labels: Type: Testing, Area: xDS

#8451 transport: release mutex before returning on expired deadlines in server streams
  internal/transport/http2_server.go
Labels: Type: Bug, Area: Transport

#8450 Revert "credentials: allow audience to be configured (#8421)"
  Documentation/grpc-auth-support.md
  internal/envconfig/envconfig.go
  internal/transport/http2_client.go
  test/creds_test.go
Labels: Type: Feature

#8454 Cherry-pick #8411, #8419, #8422, #8445 and #8451 to v1.74.x
  internal/transport/http2_server.go
  internal/xds/bootstrap/bootstrap.go
  internal/xds/bootstrap/bootstrap_test.go
  xds/internal/clients/xdsclient/channel.go
  xds/internal/clients/xdsclient/helpers_test.go
  xds/internal/clients/xdsclient/resource_type.go
  xds/internal/clients/xdsclient/test/helpers_test.go
  xds/internal/xdsclient/pool.go
  xds/internal/xdsclient/pool/pool_test.go
  xds/internal/xdsclient/xdsresource/resource_type.go
Labels: Type: Feature

#8408 Change version to 1.74.1-dev
  version.go
Labels: Type: Meta

#8456 Retract v1.74.0 and v1.74.1
  go.mod
Labels: Type: Meta

#8457 Cherry-pick #8456 into v1.74.x release branch
  go.mod
Labels: Type: Meta

#8461 Change version to 1.74.2-dev
  version.go
Labels: Type: Meta

#8459 testutils/roundrobin: Improve validation of WRR distribution
  balancer/grpclb/grpclb_test.go
  examples/go.sum
  gcp/observability/go.sum
  go.mod
  go.sum
  internal/testutils/roundrobin/roundrobin.go
  interop/observability/go.sum
  interop/xds/go.sum
  security/advancedtls/examples/go.sum
  security/advancedtls/go.sum
  stats/opencensus/go.sum
  test/xds/xds_client_custom_lb_test.go
  xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Labels: Type: Testing

#8465 stats: add DelayedPickComplete and follow correct semantics
  clientconn.go
  picker_wrapper.go
  picker_wrapper_test.go
  scripts/vet.sh
  stats/opentelemetry/trace.go
  stats/stats.go
  stream.go
  test/end2end_test.go
  test/retry_test.go
  test/stats_test.go
Labels: Type: Behavior Change

#8470 Change version to 1.74.2
  version.go
Labels: Type: Meta

#8469 advancedtls: avoid txt lookups in test and use test logger instead of Printf
  security/advancedtls/advancedtls_integration_test.go
  security/advancedtls/crl_provider_test.go
Labels: Type: Testing

#8471 Change version to 1.74.3-dev
  version.go
Labels: Type: Meta

#8476 xds: allow empty nodeID in bootstrap configuration
  xds/internal/clients/xdsclient/xdsclient.go
  xds/internal/clients/xdsclient/xdsclient_test.go
Labels: Type: Bug, Area: xDS
